<?php

/**
 * Hotel Front-Office Solution
 *
 * LICENSE
 *
 * This source file is subject to license that is bundled
 * with this package in the file docs/LICENSE.txt.
 *
 * @package 	Back-Office
 * @copyright 	BH-TECK Inc. 2009-2010
 * @version		$Id$
 */

?>

<div class="resultados"></div>

<?php echo HfosTag::iconTitle('cartera.png', 'Cartera por Edades') ?>

<?php echo Tag::form('informe_cartera/generar', 'class: informeCarteraForm', 'autocomplete: off') ?>
<table align="center">
	<tr>
		<td valign="top">
			<table>
				<tr>
					<td align="right"><label for="fechaLimite">Fecha Límite</label></td>
					<td><?php echo Tag::dateField('fechaLimite') ?></td>
				</tr>
				<tr>
					<td align="right"><label for="socios_id">Socio</label></td>
					<td><?php
						echo HfosTag::addHyperFormSpecialField(array(
								'type' => 'Socio',
								'name' => 'socios_id',
								'classForm' => 'informeCarteraForm'
							));
						?>
					</td>
				</tr>
				<!--<tr>
					<td align="right"><label for="activos">Solo Socios con Genera Cobro: "Si"</label></td>
					<td> 
						<input type='checkbox' name='activos' value='1'>
					</td>
				</tr>-->
                <tr>
                    <td align="right"><label for="consolidado">Genera Solo consolidados</label></td>
                    <td>
                        <input type='checkbox' name='consolidado' value='1'>
                    </td>
                </tr>
				<tr>
					<td align="right"></td>
					<td>
						<table cellspacing="0">
							<tr>
								<td>
									<input type="submit" value="Generar"/>
								</td>
								<td>
									<div class="formSpinner" style="display:none"></div>
								</td>
							</tr>
						</table>
					</td>
				</tr>
			</table>
		</td>
	</tr>
</table>
<?php echo HfosTag::reportTypeTag(true, false) ?>
<?php echo Tag::endForm() ?>