<?php

/**
 * Hotel Front-Office Solution
 *
 * LICENSE
 *
 * This source file is subject to license that is bundled
 * with this package in the file docs/LICENSE.txt.
 *
 * @package 	Back-Office
 * @copyright 	BH-TECK Inc. 2009-2010
 * @version		$Id$
 */

?>

<div class="resultados"></div>

<?php echo HfosTag::iconTitle('deprec.png', 'Depreciación Mensual de Activos Fijos') ?>

<?php echo Tag::form('depreciacion/generar', 'class: depreciacionForm') ?>
<table align="center">
	<tr>
		<td valign="top">
			<table>
				<tr>
					<td align="right"><label for="definitivo">Definitivo?</label></td>
					<td><?php echo Tag::selectStatic('definitivo', array(
						'N' => 'NO',
						'S' => 'SI'
					)) ?></td>
				</tr>
				<tr>
					<td align="right"></td>
					<td>
						<table cellspacing="0">
							<tr>
								<td>
									<input type="submit" value="Generar"/>
								</td>
								<td>
									<div class="formSpinner" style="display:none"></div>
								</td>
							</tr>
						</table>
					</td>
				</tr>
			</table>
		</td>
		<td valign="top">
			<div class="cuadro-cierre">
				<table>
					<tr>
						<td align="right"><b>Última Depreciación</b></td>
						<td><?php echo $ultimaDepreciacion ?></td>
					</tr>
				</table>
			</div>
		</td>
	</tr>
</table>
<?php echo HfosTag::reportTypeTag(true, false) ?>
<?php echo Tag::endForm() ?>