<?php

/**
 * Hotel Front-Office Solution
 *
 * LICENSE
 *
 * This source file is subject to license that is bundled
 * with this package in the file docs/LICENSE.txt.
 *
 * @package 	Back-Office
 * @copyright 	BH-TECK Inc. 2009-2010
 * @version		$Id$
 */

?>

<br><br>
<table class='lista_res' align="center" cellspacing="0">
	<tr>
		<th></th>
		<th align="center">Tipo Pedido</th>
	</tr>
	<?php
		foreach($TipoVenta->find() as $tipoVenta){
			if(in_array($tipoVenta->id, $servicios)){
				$checked = "checked";
			} else {
				$checked = "";
			}
			echo "<tr><td><input type='checkbox' $checked onclick='savePerm(\"{$tipoVenta->id}\")'></td><td>{$tipoVenta->detalle}</td></tr>";
		}
	?>
</table>