<?php

/**
 * Hotel Front-Office Solution
 *
 * LICENSE
 *
 * This source file is subject to license that is bundled
 * with this package in the file docs/LICENSE.txt.
 *
 * @package 	Back-Office
 * @copyright 	BH-TECK Inc. 2009-2010
 * @version		$Id$
 */

$config = CoreConfig::readAppConfig();
if ($config->application->mode == 'production') {
	echo Tag::javascriptInclude('pos2/production/factura', true, 'v='.ControllerBase::APP_VERSION);
}

View::getContent();

?>

<style type='text/css'>
	td, span, div, th, pre {
		font-family: 'Lucida Console', 'Courier New';
		font-size: 12px;
	}
	body {
		margin: 0px;
		margin-left:2px;
	}
</style>
<div style='width:270px;'>
<pre>
<?php
if(!function_exists('center')){
	function center($text, $size) {
		if (mb_strlen($text) >= $size) {
			return $text;
		}
		$spaces = str_repeat(' ', ($size - mb_strlen($text))/2);
		return $spaces . $text . $spaces;
	}
}

echo center($factura->nombre_cadena, 35), "\n";
echo center($factura->nota_contribuyentes, 35), "\n";
echo center($factura->documento." No. : ".$factura->nit, 35)."\n";
echo center($factura->nombre_hotel, 35)."\n";
echo center($factura->direccion, 35)."\n";
echo center("Tel. ".$factura->telefonos, 35)."\n";
if ($preview == false) {
	$nombre_documento = '';
	if($factura->tipo=='O'){
		$nombre_documento = 'ORDEN DE SERVICIO ';
	}else{
		$nombre_documento = $factura->tipo_factura == 'E' ? 'COMPROBANTE DE PAGO' : 'FACTURA DE VENTA';
	}
	echo center($nombre_documento.' No. '.
	($factura->tipo=='O' ? '' : $factura->prefijo_facturacion.'-').$factura->consecutivo_facturacion, 35)."\n";
	if ($factura->tipo == "F") {
		echo center("RESOLUCIÓN NO ".$factura->resolucion, 35)."\n";
		echo center("DEL ".$factura->fecha_resolucion, 35)."\n";
		echo center("NUMER. No ".$factura->prefijo_facturacion." ".sprintf("%06s", $factura->numero_inicial)." AL ".
		$factura->prefijo_facturacion.' '.sprintf("%06s", $factura->numero_final), 35)."\n";
	}
} else {
	echo center("ESTADO DE CUENTA", 35)."\n";
}
echo center("Fecha factura: {$factura->fecha} $factura->hora" , 35)."\n";
echo center("Cajero: ".$factura->usuarios_nombre, 35)."\n";
echo center("Ubicación: {$factura->salon_nombre} Mesa: {$factura->salonmesas_numero}", 40)."\n";
echo center("Comanda #: {$factura->comanda}", 35)."\n";
?>
</pre>
<?php
if($factura->tipo_venta=='F'): ?>
<div align="left">
<pre>
 <?php 
 	echo center( "CLIENTE: ".$factura->nombre, 35)."\n";
 	echo center( "NIT o CC ".$factura->cedula, 35)."\n";
 ?>
</pre>
</div>
<?php endif ?>
<table width="250" cellspacing="0" border="0" align='left'>
	<tr>
		<th>Cant.</th>
		<th>Descrip.</th>
		<th>Vr Venta</th>
		<th>Imp.</th>
	</tr>
	<?php

	$bases = array();

	foreach ($detalleFactura as $detalle) {

		echo "<tr>";
		echo "<td align='center'>$detalle->cantidad</td>";
		echo '<td>', nl2br($detalle->menus_items_nombre), '</td>';
		echo "<td align='right'>", Currency::number($detalle->total), "</td>";
		echo "<td align='right'>", $detalle->porcentaje_iva, "</td>";
		echo "</tr>";

		if($detalle->porcentaje_iva > 0){
			$bases[$detalle->porcentaje_iva] = isset($bases[$detalle->porcentaje_iva]) ? $bases[$detalle->porcentaje_iva] + $detalle->valor : $detalle->valor;
			$impuesto[$detalle->porcentaje_iva] = isset($impuesto[$detalle->porcentaje_iva]) ? $impuesto[$detalle->porcentaje_iva] + $detalle->iva : $detalle->iva;
		}
		

	}
?>
</table>
<br><br><br>
<div style='pading: 0px; width:250px' align='right'>
<br>
===================================
</div>
<table width='250'>
	<tr>
		<td></td>
	</tr>
	<tr>
		<td align="right">
			SUB-TOTAL:
		</td>
		<td align='right'>
			<?php echo Currency::number($factura->subtotal) ?>
		</td>
	</tr>
	<tr>
		<td align="right">
			I. V. A.
		</td>
		<td align="right">
			<?php echo Currency::number($factura->total_iva) ?>
		</td>
	</tr>
	<tr>
		<td align="right">
			IMPOCONSUMO
		</td>
		<td align="right">
			<?php echo Currency::number($factura->total_impoconsumo) ?>
		</td>
	</tr>
	<tr>
		<td align="right">
			PROPINA VOLUNTARIA SUGERIDA:
		</td>
		<td align='right'>
			<?php echo Currency::number($factura->propina) ?>
		</td>
	</tr>
</table>
</div>
<div style='pading: 0px; width:250px' align="right">
----------------------------------
GRAN TOTAL: <?php echo Currency::number($factura->total) ?>
<br>
===================================
</div>
<br>
<div style='pading: 0px; width:250px'>
----------------------------------
FORMAS DE PAGO<br>
===================================
</div>
<?php
echo "<table width='250'>";
foreach ($pagosFactura as $pago) {
	$formapago = $pago->getFormasPago()->detalle;  
	echo "<tr>";
	echo "<td align='left' with='50%'>$formapago</td>";
	echo "<td align='right'>", Currency::number($pago->pago), "</td>";
	echo "</tr>";
}
echo "</table>";
echo "<br>";

?>
<div style='pading: 0px; width:250px'>
Detalles impuesto:<br>
===================================
</div>
<?php
echo "<table width='250'>";
foreach ($bases as $iva => $base) {
	echo "<tr>";
	echo "<td align='left' with='50%'>$iva%</td>";
	echo "<td align='right'>Base ", Currency::number($base), "</td>";
	echo "<td align='right'>Impuesto ", Currency::number($impuesto[$iva]), "</td>";
	echo "</tr>";
}
echo "</table>";

if(!$preview&&$factura->propina>0&&$factura->leyenda_propina=='S'){
	echo "<pre style='width:270px;text-align:justify'>", $factura->texto_propina, "</pre>";
}

echo "<div align='left' style='width:270px'>";
if($factura->tipo_venta=='H'){
		echo "<br/>
Autorizo a Cargar a mi Cuenta
<br>
<br>
<pre style='width:270px'>";
if(!$factura->habitacion_numero){
echo"	  Firma:---------------------
          ", $factura->nombre; ?>
<?php } else {
echo 'Hab: ', sprintf("% 4s", $factura->habitacion_numero), ' Firma:---------------------', "\n";
echo '                ', $factura->nombre;
}
echo '</pre>
</div>
<div align="left">';
if(!$factura->habitacion_numero){
	echo 'CARGO A CUENTA: ', Currency::number($factura->total);
} else {
	echo 'CARGO HABITACIÓN: ', Currency::number($factura->total);
}
echo '</div>';
}
if($factura->tipo_venta=='P'){
echo '<br>
<br>
<pre>
Hab: ', sprintf("% 4s", $factura->habitacion_numero), ' Firma:---------------------', "\n";
echo '                ', $factura->nombre;
echo '</pre>
</div>
<div align="left">'; ?>
CARGO POR PLAN: <?php echo Currency::number($factura->total) ?>
</div>
<?php } ?>

<?php if($factura->tipo_venta=='U'): ?>
<pre>



 Firma:---------------------
 <?php echo $factura->nombre."\n" ?>
 C.C. <?php echo $factura->cedula ?>
</pre>
</div>
<div align='left'>
&nbsp;COSTO A FUNCIONARIO: <?php echo Currency::number($factura->total) ?>
</div>
<?php endif ?>


<?php if($factura->tipo_venta=='C'): ?>
<pre>



 Firma:---------------------
 <?php echo $factura->nombre."\n" ?>
 C.C. <?php echo $factura->cedula ?>
</pre>
</div>
<div align='left'>
 &nbsp;COSTO DE LA CORTESIA: <?php echo Currency::number($factura->total) ?>
</div>
<?php endif ?>

<div align='center' style='width:270px'>
<?php
if($factura->tipo_venta != "F"):
if(!$preview):
?>
<br>
ESTE DOCUMENTO NO ES UNA <br>FACTURA DE VENTA
<br><br>
<?php echo $factura->texto_impresion ?>
<?php else: ?>
<br><br>
ESTE DOCUMENTO ES UN ESTADO DE CUENTA, NO DEBE SER
PAGADO NI CARGADO A SU CUENTA
<?php endif ?>
<?php else:
if(!$preview):
?>
<br>
<?php echo $factura->texto_impresion ?><br/>
<?php else: ?>
ESTE DOCUMENTO NO ES UNA <br>FACTURA DE VENTA
<br><br>
<?php echo $factura->texto_impresion ?>
<?php endif ?>
<?php endif ?>
</div>
</div>
</td>
</tr>
</table>
<?php
	if($factura->tipo_venta=='F' && !$preview)
	{
?>
	<div align='justify' style='width:270px'>No valida como factura. La representación gráfica de la factura, le llegara al correo electrónico</div>
<?php
	}
?>

<?php

?>

<script type='text/javascript'>
	new Event.observe(window, "load", function(){
		
		window.setTimeout(function(){
			<?php  
			if($redirec_pay){
			?>
			<?php if($preview==false&&$reprint==false): ?>
			new Utils.redirectOpenerToAction("pay/index/<?php echo $factura->account_master_id ?>:<?php echo $accountCuenta->cuenta ?>");
			<?php endif; ?>
			<?php 
			}
			?>
			window.print();
		}, 500);
		
	});
</script>

</div>
