<?php

/**
 * Hotel Front-Office Solution
 *
 * LICENSE
 *
 * This source file is subject to license that is bundled
 * with this package in the file docs/LICENSE.txt.
 *
 * @package 	Back-Office
 * @copyright 	BH-TECK Inc. 2009-2010
 * @version		$Id$
 */

$config = CoreConfig::readAppConfig();
if($config->application->mode=='development'){
	Tag::stylesheetLink('pos2/pay');
	Tag::stylesheetLink('pos2/numero');
	echo Tag::javascriptInclude("pos2/pay");
	echo Tag::javascriptInclude("pos2/modal");
	echo Tag::javascriptInclude('pos2/keyboard');
	echo Tag::javascriptInclude('pos2/windows');
} else {
	Tag::stylesheetLink('pos2/production/pay', false, 'v='.ControllerBase::APP_VERSION);
	echo Tag::javascriptInclude('pos2/production/pay', true, 'v='.ControllerBase::APP_VERSION);
}

?>
<div id="pay" align="center">
	<table cellspacing="0" cellpadding='0' align="center">
		<tr>
			<td class='sh_left'></td>
			<td>
				<div align='center'>
					<?php View::getContent() ?>
				</div>
			</td>
			<td class='sh_right'></td>
		</tr>
		<tr>
			<td></td>
			<td class='sh_down'></td>
			<td></td>
		</tr>
	</table>
</div>