<?php

/**
 * Hotel Front-Office Solution
 *
 * LICENSE
 *
 * This source file is subject to license that is bundled
 * with this package in the file docs/LICENSE.txt.
 *
 * @package 	Back-Office
 * @copyright 	BH-TECK Inc. 2009-2010
 * @version		$Id$
 */

?>
<style type='text/css'>
	td, span, div, th, pre {
		font-family: 'Lucida Console', 'Courier New';
		font-size: 12px;
	}
	body {
		margin: 0px;
		margin-left:2px;
	}
</style>
<div style='width:270px;'>
<pre>
<?php

function center($text, $size){
	if(strlen(html_entity_decode($text))>=$size){
		return $text;
	}
	$spaces = str_repeat(" ", ($size-strlen(html_entity_decode($text, ENT_COMPAT, 'UTF-8')))/2);
	return $spaces.$text.$spaces;
}

if(!$id){
	$cuentas[0][0] = $current_master;
	$cuentas[0][1] = $numero_cuenta;
} else {
	$cuentas = explode("-", $id);
	$c = array();
	foreach($cuentas as $cue){
		$c[] = explode(":", $cue);
	}
	$cuentas = $c;
}
if(!isset($_REQUEST['documento'])){
	Flash::error("No ha el documento del cliente");
	return;
}

try {
	$transaction = new ActiveRecordTransaction(true);
	$Account->setTransaction($transaction);
	$Datos->findFirst();
	$Clientes->findFirst("id='{$_REQUEST['documento']}'");
	$AccountMaster->setTransaction($transaction);
	$AccountMaster->findFirst($cuentas[0][0]);
	$AccountCuentas->setTransaction($transaction);
	$accountCuenta = $AccountCuentas->findFirst("account_master_id='{$cuentas[0][0]}' AND cuenta='{$cuentas[0][1]}'");
	if($accountCuenta==false){
		Flash::error("No existe la cuenta");
		$transaction->rollback();
	}
	$tipo_venta = $AccountCuentas->tipo_venta;
	$habitacion_id = $AccountCuentas->habitacion_id;
	$Habitacion->find($habitacion_id);
	$Salon->setTransaction($transaction);
	$SalonMesas->setTransaction($transaction);
	if($AccountMaster->salon_mesas_id!=""){
		$SalonMesas->findFirst($AccountMaster->salon_mesas_id);
		$Salon->setTransaction($transaction);
		$Salon->findFirst($SalonMesas->salon_id);
	} else {
		$Salon->findFirst(Session::get("salon_id"));
		$SalonMesas->findFirst("salon_id='{$Salon->id}'");
	}

	$factura = new Factura();
	$factura->setTransaction($transaction);

	if($tipo_venta!="F"){
		if($AccountCuentas->estado!='B'&&$AccountCuentas->estado!='L'){
			$numero = $AccountCuentas->numero = ++$Salon->consecutivo_orden;
		} else {
			$numero = $AccountCuentas->numero;
		}
	} else {
		if($AccountCuentas->estado!='B'&&$AccountCuentas->estado!='L'){
			$numero = $AccountCuentas->numero = ++$Salon->consecutivo_facturacion;
		} else {
			$numero = $AccountCuentas->numero;
		}
	}

	$comanda = 0;
	$conditions = "account_master_id='{$cuentas[0][0]}' and cuenta='{$cuentas[0][1]}' and estado <> 'C'";
	foreach($Account->find($conditions) as $AccountItem){
		$AccountItem->setTransaction($transaction);
		if(!$AccountItem->tiempo_final){
			$AccountItem->tiempo_final = Date::getCurrentTime();
		}
		$comanda = $AccountItem->comanda;
		$AccountItem->estado = 'B';
		if($AccountCuentas->estado=='A'||$AccountCuentas->estado=='S'){
			if(!$preview){
				if($AccountItem->save()==false){
					foreach($AccountItem->getMessages() as $message){
						Flash::error($message->getMessage());
					}
					$transaction->rollback();
				}
			}
		}
	}

	if(!$preview){
		if($AccountCuentas->estado=='A'){
			$AccountCuentas->estado = 'B';
			if($AccountCuentas->save()==false){
				foreach($AccountCuentas->getMessages() as $message){
					Flash::error($message->getMessage());
				}
				$transaction->rollback();
			}
			if(!$Salon->save()){
				foreach($AccountCuentas->getMessages() as $message){
					Flash::error($message->getMessage());
				}
				$transaction->rollback();
			}
		}
	}

echo center($Datos->nombre_cadena, 35)."\n";
echo center("REGIMEN COMUN", 35)."\n";
echo center($Datos->documento." No. : ".$Datos->nit, 35)."\n";
echo center(strtoupper($Datos->nombre_hotel), 35)."\n";
echo center(strtoupper($Datos->direccion), 35)."\n";
echo center("Tel. ".$Datos->telefonos, 35)."\n";
if(!$preview){
	echo center(($tipo_venta != "F" ? "ORDEN DE SERVICIO " : "FACTURA DE VENTA")." No. ".
	($tipo_venta != "F" ? "" : $Salon->prefijo_facturacion."-").$numero, 35)."\n";
	if($tipo_venta=="F"){
		echo center("RESOLUCI&Oacute;N NO ".$Salon->autorizacion, 35)."\n";
		echo center("DEL ".$Salon->fecha_autorizacion, 35)."\n";
		echo center("NUMER. No ".sprintf("%06s", $Salon->consecutivo_inicial)." AL ".sprintf("%06s", $Salon->consecutivo_final), 35)."\n";
	}
} else {
	echo center("PRE-FACTURA", 35)."\n";
}
echo center("Fecha: {$Datos->fecha}" , 35)."\n";
echo center("Cajero: ".strtoupper(Session::getData("usuarios_nombre")), 35)."\n";
echo center("Ubicación: {$Salon->nombre} Mesa: {$SalonMesas->numero}", 40)."\n";
echo center("Comanda #: {$comanda} Hora: ".Date::getCurrentTime("H:i"), 35)."\n";

?>
</pre>
<table width="250" cellspacing="0" border="0" align='left'>
	<tr>
		<th>Cant.</th>
		<th>Descrip.</th>
		<th>Vr Venta</th>
		<th>Iv</th>
	</tr>
	<?php

	$total = 0;
	$subtotal = 0;
	$tiva = 0;
	$tser = 0;
	$resumen = array();
	foreach($cuentas as $cuen) {
		if($cuen){
			$conditions = "cuenta='{$cuen[1]}' and account_master_id='{$cuen[0]}' and estado in ('A', 'B', 'S', 'L')";
			foreach($Account->find($conditions) as $AccountItem){
				$AccountItem->setTransaction($transaction);
				$MenusItems->find($AccountItem->menus_items_id);

				if(!isset($resumen[$MenusItems->tipo])){
					$resumen[$MenusItems->tipo] = 0;
				}

				$t = $AccountItem->total * $AccountItem->cantidad;
				$ts = $AccountItem->valor * $AccountItem->cantidad;

				$nombreItem = $MenusItems->nombre;
				$accountModifiers = $AccountModifiers->find("account_id='".$AccountItem->id."'");
				if(count($AccountModifiers)){
					echo '<br/>';
					foreach($accountModifiers as $accountModifier){
						$modifier = $Modifiers->findFirst($accountModifier->modifiers_id);
						if($modifier!=false){
							$nombreItem.=' + '.$modifier->nombre.'<br/>';
							if($modifier!=false){
								$t+=$modifier->valor;
								$ts+=$modifier->valor;
							}
						}
					}
				}

				if($AccountItem->descuento>0){
					$t-=($t * $AccountItem->descuento / 100);
					$ts-=($ts * $AccountItem->descuento / 100);
					$tser += ($AccountItem->servicio - ($AccountItem->servicio*$AccountItem->descuento/100)) * $AccountItem->cantidad;
					$tiva += ($AccountItem->iva - ($AccountItem->iva * $AccountItem->descuento/100)) * $AccountItem->cantidad;
				} else {
					$tser += $AccountItem->servicio * $AccountItem->cantidad;
					$tiva += $AccountItem->iva * $AccountItem->cantidad;
				}

				$t = Locale::round($t);
				$subtotal+=$ts;
				//$total+=$t+$tiva+$tser;
				$total+=$t;
				$resumen[$MenusItems->tipo]+=$ts;

				echo "<tr>";
				echo "<td align='center'>$AccountItem->cantidad</td>";
				if($AccountItem->descuento>0){
					echo utf8_encode("<td>$nombreItem (Descuento {$AccountItem->descuento}%)</td>");
				} else {
					echo utf8_encode("<td>$nombreItem</td>");
				}
				echo "<td align='right'>".Locale::money($t)."</td>";
				echo "<td align='right'>".$MenusItems->porcentaje_iva."</td>";
				echo "</tr>";
				$AccountItem->cantidad_atendida = $AccountItem->cantidad;
				if($preview==false){
					if($AccountItem->estado!='L'){
						if($AccountItem->save()==false){
							foreach($AccountItem->getMessages() as $message){
								Flash::error($message->getMessage());
							}
							$transaction->rollback();
						}
					}
				}
			}
		}
	}
	?>
</table>
<br><br><br>
<div style='pading: 0px; width:250px' align='right'>
-----------------------------------
TOTAL PEDIDO: <?php echo Locale::money($total) ?><br>
===================================
</div>
<table width='250'>
<tr>
<td align='right'>
ALIMENTOS:
</td>
<td align='right'>
<?php echo isset($resumen['A']) ? Locale::money($resumen['A']) : 0.00 ?>
</td>
</tr>
<tr>
<td align='right'>
BEBIDAS:
</td>
<td align='right'>
<?php echo isset($resumen['B']) ? Locale::money($resumen['B']) : 0.00 ?>
</td>
</tr>
<tr>
<td></td>
</tr>
<tr>
<td align="right">
Subtotal:
</td>
<td align='right'>
<?php echo Locale::money($subtotal) ?>
</td>
</tr>
<tr>
<td align="right">
I. V. A.
</td>
<td align="right">
<?php echo Locale::money($tiva) ?>
</td>
</tr>
<tr>
<td align="right">
	PROPINA VOLUNTARIA SUGERIDA:
</td>
<td align='right'>
<?php
if(!isset($resumen['A'])){
	$resumen['A'] = 0;
}
if(!isset($resumen['B'])){
	$resumen['B'] = 0;
}
$subtotalp = $resumen['A']+$resumen['B'];
$propina = $subtotalp*($Salon->porcentaje_servicio/100);
$total+=$propina
?>
<?php echo Locale::money($propina) ?>
</td>
</tr>
<tr>
<td align="right" style='font-size:14px'>
T O T A L:
</td>
<td align="right" style='font-size:14px'>
<?php echo Locale::money($total) ?>
</td>
</tr>
<tr>
<td></td>
</tr>
</table>
</div>
<?php if(!$preview&&$propina>0&&$Salon->leyenda_propina=='S'): ?>
<div style='width:270px;text-align:justify'>
<br>
ADVERTENCIA PROPINA<br>
Por disposici&oacute;n de la Superintendencia
de Industria y Comercio se informa que, en este
establecimiento la propina es sugerida al
consumidor y corresponde a un porcentaje del
10% sobre el valor total de la cuenta, el cual
podr&aacute; ser aceptado, rechazado &oacute;
modificado por usted, de acuerdo con su
valorizaci&oacute;n del servicio prestado. Si no
desea cancelar dicho valor haga caso omiso del
mismo. Si desea cancelar un valor diferente
indiquelo asi para hacer el ajuste correspondiente.
$ _____________
</div>
<?php endif; ?>

<div align='left' style='width:270px'>
<?php if($tipo_venta=='H'): ?>
<br>
Autorizo a Cargar a mi Cuenta
<br>
<br>
<br>
<pre style='width:270px'>
<?php if(!$Habitacion->numhab): ?>
          Firma:---------------------
          <?php echo $AccountCuentas->clientes_nombre ?>
<?php else: ?>
Hab: <?php echo sprintf("% 4d", $Habitacion->numhab) ?> Firma:---------------------
                <?php echo $AccountCuentas->clientes_nombre ?>
<?php endif; ?>
</pre>
</div>
<div align='left'>
<?php if(!$Habitacion->numhab): ?>
CARGO A CUENTA: <?php echo Locale::money($total) ?>
<?php else: ?>
CARGO HABITACION: <?php echo Locale::money($total) ?>
<?php endif; ?>
</div>
<?php endif; ?>
<?php if($tipo_venta=='P'): ?>
<br>
<br>
<pre>
Hab: <?php echo sprintf("% 4d", $Habitacion->numhab) ?> Firma:---------------------
                <?php echo $AccountCuentas->clientes_nombre ?>
</pre>
</div>
<div align='left'>
CARGO POR PLAN: <?php echo Locale::money($total) ?>
</div>
<?php endif; ?>
<?php if($tipo_venta=='F'): ?>
<pre>



 Firma:---------------------
 <?php echo $AccountCuentas->clientes_nombre."\n" ?>
 C.C. <?php echo $AccountCuentas->clientes_cedula ?>
</pre>
</div>
<?php endif ?>

<?php if($tipo_venta=='U'): ?>
<pre>



 Firma:---------------------
 <?php echo $AccountCuentas->clientes_nombre."\n" ?>
 C.C. <?php echo $AccountCuentas->clientes_cedula ?>
</pre>
</div>
<div align='left'>
&nbsp;COSTO A FUNCIONARIO: <?php echo Locale::money($total) ?>
</div>
<?php endif ?>


<?php if($tipo_venta=='C'): ?>
<pre>



 Firma:---------------------
 <?php echo $AccountCuentas->clientes_nombre."\n" ?>
 C.C. <?php echo $AccountCuentas->clientes_cedula ?>
</pre>
</div>
<div align='left'>
 &nbsp;COSTO DE LA CORTESIA: <?php echo Locale::money($total) ?>
</div>
<?php endif ?>

<div align='center' style='width:270px'>
<?
if($tipo_venta != "F"):
if(!$preview):
?>
<br>
ESTE DOCUMENTO NO ES UNA <br>FACTURA DE VENTA
<br><br>
GRACIAS POR SU COMPRA
<?php else: ?>
<br><br>
ESTE DOCUMENTO ES UNA PRE-FACTURA, NO DEBE SER
PAGADO NI CARGADO A SU CUENTA
<?php endif ?>
<?php else:
if(!$preview):
?>
<br>
GRACIAS POR SU COMPRA
<?php else: ?>
ESTE DOCUMENTO NO ES UNA <br>FACTURA DE VENTA
<br><br>
GRACIAS POR SU COMPRA
<?php endif ?>
<?php endif ?>
</div>
</div>
</td>
</tr>
</table>
<?php

if($tipo_venta=="F"){
	$tipo = "F";
} else {
	$tipo = "O";
}

if($AccountCuentas->estado!='L'){
	if(!$factura->findFirst("salon_id='{$Salon->id}' AND prefijo_facturacion = '{$Salon->prefijo_facturacion}' and consecutivo_facturacion = {$AccountCuentas->numero} and tipo = '$tipo'")){
		$factura->prefijo_facturacion = $Salon->prefijo_facturacion;
		$factura->consecutivo_facturacion = $numero;
		$factura->account_master_id = $cuen[0];
		$factura->documento = $Datos->documento;
		$factura->nit = $Datos->nit;
		$factura->nombre_hotel = $Datos->nombre_hotel;
		$factura->nombre_cadena = $Datos->nombre_cadena;
		$factura->direccion = $Datos->direccion;
		$factura->telefonos = $Datos->telefonos;
		$factura->fax = $Datos->fax;
		$factura->po_box = $Datos->po_box;
		$factura->ciudad = $Datos->ciudad;
		$factura->pais = $Datos->pais;
		$factura->entidad = $Datos->entidad;
		$factura->moneda = $Datos->moneda;
		$factura->centavos = $Datos->centavos;
		$factura->nota_contribuyentes = $Datos->nota_contribuyentes;
		$factura->cedula = $Clientes->id;
		$factura->nombre = $Clientes->nombre;
		$factura->clientes_direccion = $Clientes->direccion;
		$factura->clientes_telefono = $Clientes->telefono;
		$factura->salon_id = $Salon->id;
		$factura->salon_nombre = $Salon->nombre ? $Salon->nombre : "ORDEN DIRECTA";
		$factura->salonmesas_numero = $SalonMesas->numero ? $SalonMesas->numero : "0";
		$factura->usuarios_id = Session::getData("usuarios_id");
		$factura->usuarios_nombre = Session::getData("usuarios_nombre");
		$factura->fecha = $Datos->fecha;
		$factura->tipo = $tipo;
		$factura->tipo_venta = $tipo_venta;
		$factura->total = $total;
		$factura->total_iva = $tiva;
		$factura->total_servicio = $tser;
		$factura->estado = 'A';
		if(!$preview){
			if($factura->save()==false){
				foreach($factura->getMessages() as $message){
					Flash::error($message->getMessage());
				}
				$transaction->rollback();
			} else {
				if($tipo_venta=='F'){
					new POSAudit("GENERO LA FACTURA {$Salon->prefijo_facturacion}-$numero", $transaction);
				}  else {
					new POSAudit("GENERO LA ORDEN DE SERVICIO {$Salon->prefijo_facturacion}-$numero", $transaction);
				}
			}
		}
		foreach($Account->find("cuenta='{$cuen[1]}' AND account_master_id='{$cuen[0]}' AND estado = 'B'") as $AccountItem){
			$detalle = new DetalleFactura();
			$detalle->setTransaction($transaction);
			$detalle->prefijo_facturacion = $Salon->prefijo_facturacion;
			$detalle->consecutivo_facturacion = $numero;
			$detalle->tipo = $habitacion_id ? 'O' : 'F';

			$MenusItems->find($AccountItem->menus_items_id);
			$t = $AccountItem->valor;
			$ModifiersTotal = 0;
			foreach($AccountModifiers->find("account_id='".$AccountItem->id."'") as $accountModifier){
				$modifier = $Modifiers->findFirst($accountModifier->modifiers_id);
				if($modifier!=false){
					$total+=$modifier->valor;
					$ModifiersTotal+=$modifier->valor;
					$t+=$modifier->valor;
				}
			}

			if($AccountItem->descuento){
				$detalle->menus_items_nombre = "$MenusItems->nombre (Descuento {$AccountItem->descuento}%)";
			} else {
				$detalle->menus_items_nombre = $MenusItems->nombre;
			}

			$t+=$ModifiersTotal;
			if($AccountItem->descuento){
				$t-=($t * $AccountItem->descuento / 100);
			}
			$detalle->valor = $t;
			$detalle->total = ($t * $AccountItem->cantidad);

			$detalle->menus_items_id = $MenusItems->id;
			$detalle->cantidad = $AccountItem->cantidad;
			$detalle->descuento = $AccountItem->descuento;

			if(!$preview){
				if($detalle->save()==false){
					foreach($detalle->getMessages() as $message){
						Flash::error($message->getMessage());
					}
				}
			}

		}
	}

if(!$preview): ?>

<?php endif; ?>

<?php } ?>

<script type='text/javascript'>
	new Event.observe(window, "load", function(){
		window.setTimeout(function(){
			new Utils.redirectOpenerToAction("pay/index/<?php echo $AccountMaster->id ?>:<?php echo $AccountCuentas->cuenta ?>");
			window.print();
		}, 500);
	});
</script>

<?php

	$transaction->commit();

}
catch(TransactionFailed $e){
	Flash::error("Han ocurrido errores al generar la orden/factura");
	Flash::error($e->getMessage());
}

?>

</div>