<?php

/**
 * Hotel Front-Office Solution
 *
 * LICENSE
 *
 * This source file is subject to license that is bundled
 * with this package in the file docs/LICENSE.txt.
 *
 * @package 	Back-Office
 * @copyright 	BH-TECK Inc. 2009-2010
 * @version		$Id$
 */

echo HfosTag::iconTitle('attibutes.png', 'Generar Cheques') ?>

<div class="formContent">

	<div class="formPannel" align="right">

		<?php echo Tag::form('cheque/generar', 'autocomplete: off', 'class: formGrabar') ?>
			<fieldset class="tabbed">
				<legend>Datos Cheque</legend>
				<table align="center">
					<tr>
						<td align="right"><label for="nit">Tercero</label></td>
						<td>
							<table class="terceroCompleter" cellspacing="0">
								<tr>
									<td><?php echo Tag::textField(array('nit', 'size' => 12)) ?></td>
									<td><?php echo Tag::textField(array('nit_det', 'size' => 35, 'class' => 'terceroDetalle')) ?></td>
									<td><input type="button" class="crearNit" id="nit_create" value="Crear"/></td>
								</tr>
							</table>
						</td>
					</tr>
					<tr>
						<td align="right"><label for="fechaMovi">Fecha Comprobante</label></td>
						<td><?php echo Tag::dateField(array('fechaMovi', 'value' => Date::getCurrentDate(), 'class' => 'date-field')) ?></td>
					</tr>
					<tr>
						<td align="right"><label for="fecha">Fecha Cheque</label></td>
						<td><?php echo Tag::dateField(array('fecha', 'value' => Date::getCurrentDate(), 'class' => 'date-field')) ?></td>
					</tr>
					<tr>
						<td align="right"><label for="beneficiario">Beneficiario</label></td>
						<td><?php echo Tag::textField(array('beneficiario', 'size' => 50)) ?></td>
					</tr>
					<tr>
						<td align="right"><label for="chequeraId">Chequera</label></td>
						<td><?php echo Tag::selectStatic('chequeraId', $chequeras, 'useDummy: yes') ?></td>
					</tr>
					<tr>
						<td align="right"><label for="numeroCheque">Número Cheque</label></td>
						<td><?php echo Tag::selectStatic(array('numeroCheque', array())) ?></td>
					</tr>
					<tr>
						<td align="right"><label for="valor">Valor</label></td>
						<td><?php echo Tag::numericField(array('valor', 'size' => 10, 'class' => 'numeric')) ?></td>
					</tr>
					<tr>
						<td align="right"><label for="observacion">Observaciones</label></td>
						<td><?php echo Tag::textArea('observacion', 'rows: 2', 'cols: 70') ?></td>
					</tr>
				</table>
			</fieldset>
			<fieldset class="tabbed">
				<legend>Contabilización</legend>
				<table align="center">
					<tr>
						<td align="right"><label for="cuenta">Cuenta</label></td>
						<td>
							<table class="cuentaCompleter" cellspacing="0">
								<tr>
									<td><?php echo Tag::textField(array('cuenta', 'size' => 12)) ?></td>
									<td><?php echo Tag::textField(array('cuenta_det', 'size' => 35, 'class' => 'cuentaDetalle')) ?></td>
								</tr>
							</table>
						</td>
					</tr>
					<tr>
						<td align="right"><label for="naturaleza">Naturaleza</label></td>
						<td><?php echo Tag::selectStatic(array('naturaleza', array('D' => 'DEBITO', 'C' => 'CREDITO'))) ?></td>
					</tr>
					<tr>
						<td align="right"><label for="nit2">Tercero</label></td>
						<td>
							<table class="terceroCompleter" cellspacing="0">
								<tr>
									<td><?php echo Tag::textField(array('nit2', 'size' => 12)) ?></td>
									<td><?php echo Tag::textField(array('nit2_det', 'size' => 35, 'class' => 'terceroDetalle')) ?></td>
								</tr>
							</table>
						</td>
					</tr>
					<tr>
						<td align="right"><label for="centroCosto">Centro Costo</label></td>
						<td><?php echo Tag::select('centroCosto', $centros, 'using: codigo,nom_centro') ?></td>
					</tr>
					<tr>
						<td align="right"><label for="descripcion">Descripción</label></td>
						<td><?php echo Tag::textField(array('descripcion', 'size' => 40)) ?></td>
					</tr>
					<tr>
						<td align="right"><label for="valor2">Valor</label></td>
						<td><?php echo Tag::numericField(array('valor2', 'size' => 12)) ?></td>
					</tr>
					<tr>
						<td></td>
						<td><?php echo Tag::button('Agregar', 'id: addMovi', 'class: controlButton') ?>&nbsp;
						<?php echo Tag::button('Nuevo', 'id: nuevoMovi', 'class: controlButton', 'style: display:none') ?>
						</td>
					</tr>
				</table>

				<table align="center" width="75%" class="hyBrowseTab zebraSt sortable" cellspacing="0">
					<thead>
						<th class="nosort sortasc"></th>
						<th class="sortcol">Cuenta</th>
						<th class="sortcol">Descripción</th>
						<th class="sortcol">Centro Costo</th>
						<th class="sortcol">Valor</th>
						<th class="nosort"></th>
						<th class="nosort"></th>
					</thead>
					<tbody id="cmovi">
						<tr>
							<td align="center" colspan="6">NO HAY CONTRAPARTIDAS</td>
						</tr>
					</tbody>
				</table>

			</fieldset>

			<fieldset class="tabbed">
				<legend>Cartera</legend>

				<div align="center">
					<div class="infoBox infoTercero">
						<table align="center">
							<tr>
								<td>Seleccione un tercero para visualizar su cartera</td>
							</tr>
						</table>
					</div>
				</div>

				<div class="carteraContent"></div>

			</fieldset>

			<!--<table align="center" width="75%" class="hyBrowseTab zebraSt sortable" cellspacing="0">
				<tr>
					<td align="right">Débitos:</td>
					<td id="debitos" align="right">0</td>
					<td align="right">Créditos:</td>
					<td id="creditos" align="right">0</td>
					<td align="right">Diferencia:</td>
					<td id="diferencia" align="right">0</td>
				</tr>
			</table>-->

		<?php echo Tag::endForm() ?>

	</div>

</div>