<?php

/**
 * Hotel Front-Office Solution
 *
 * LICENSE
 *
 * This source file is subject to license that is bundled
 * with this package in the file docs/LICENSE.txt.
 *
 * @package 	Back-Office
 * @copyright 	BH-TECK Inc. 2009-2010
 * @version		$Id$
 */

?>

<?php echo HfosTag::iconTitle('finance-2.png', 'Socios Suspendidos por Mora') ?>

<div class="formContent">

<table align="center" width="100%">
	<tr>
		<td valign="top" width="50%" align="center">

			<?php echo Tag::form('suspendidos_mora/generar', 'class: suspendidosMoraForm', 'autocomplete: off') ?>
				<table align="center">
					<tr>
						<td colspan="2">
							Este reporte solo muestra los socios suspendidos que al cerrar periodo tienen mora y se les cambio su estado por estar en mora.
						</td>
					</tr>
					<tr>
						<td align="right"><label for="periodo">Periodos</label></td>
						<td> 
							<?php
								echo Tag::select('periodo',$periodos, 'using: periodo,periodo');
							?>
						</td>
					</tr>
				</table>

			<?php echo HfosTag::reportTypeTag(true, false) ?>
			<?php echo Tag::endForm() ?>
		</td>
	</tr>
</table>
</div>
