<?php

/**
 * Hotel Front-Office Solution
 *
 * LICENSE
 *
 * This source file is subject to license that is bundled
 * with this package in the file docs/LICENSE.txt.
 *
 * @package 	Back-Office
 * @copyright 	BH-TECK Inc. 2009-2010
 * @version		$Id$
 */

echo Tag::form('fisico/guardar', 'class: saveForm', 'autocomplete: off'), '<table align="center">
	<tr>
		<td align="right"><label>Almacén</label></td>
		<td>', $almacen->getCodigo(), Tag::hiddenField('almacen', "value: {$almacen->getCodigo()}"), '</td>
		<td align="right"><label>Nombre</label></td>
		<td>', $almacen->getNomAlmacen(), '</td>
	</tr>
</table>
<br/>';

echo '<table class="hyBrowseTab zebraSt sortable" cellspacing="0" align="center" width="85%">
<thead>
	<th class="sortcol sortdesc"></th>
	<th class="sortcol">Referencia</th>
	<th class="sortcol">Descripción</th>
	<th class="sortcol">Saldo Actual</th>
	<th class="sortcol">Costo Almacén</th>
	<th class="sortcol">Saldo Almacén</th>
	<th class="sortcol">Cantidad Utilizada</th>
</thead><tbody>';
$n = 1;
foreach($saldos as $saldo){
	echo '<tr><td>', $n, '</td>';
	echo '<td>', $saldo->getItem(), Tag::hiddenField('item[]', "value: {$saldo->getItem()}"), '</td>';
	echo '<td>', $saldo->getDescripcion(), '</td>';
	echo '<td align="right">', Currency::number($saldo->getSaldoActual()), '</td>';
	echo '<td align="right">', Currency::number($saldo->getCosto()), '</td>';
	echo '<td align="right">', Currency::number($saldo->getSaldo()), '</td>';
	echo '<td align="right">', Tag::numericField('cantidad[]','size: 10','maxlength: 10','class: cantidadesFisicas','style: text-align:right', 'value: '.LocaleMath::round($saldo->getSaldo(), 2)), '</td>';
	echo '</tr>';
	$n++;
}
echo '</table>', Tag::endForm();
