<?php

/**
 * Hotel Front-Office Solution
 *
 * LICENSE
 *
 * This source file is subject to license that is bundled
 * with this package in the file docs/LICENSE.txt.
 *
 * @package 	Back-Office
 * @copyright 	BH-TECK Inc. 2009-2010
 * @version		$Id$
 */

View::getContent();

?>

<?php echo HfosTag::iconTitle('order-149.png', 'Salidas por Buffet') ?>

<?php echo Tag::form('fisico/consultar', 'class: consultarForm', 'autocomplete: off') ?>
	<table align="center">
		<tr>
			<td align="right">
				<label for="lineaInicial">Línea Inicial</b>
			</td>
			<td>
				<?php echo Tag::select('lineaInicial', $lineas, 'using: linea,nombre') ?>
			</td>
		</tr>
		<tr>
			<td align="right">
				<label for="lineaFinal">Línea Final</label>
			</td>
			<td>
				<?php echo Tag::select('lineaFinal', $lineas, 'using: linea,nombre') ?>
			</td>
		</tr>
		<tr>
			<td align="right">
				<label for="almacen">Almacén</label>
			</td>
			<td>
				<?php echo Tag::select('almacen', $almacenes, 'using: codigo,nom_almacen') ?>
			</td>
		</tr>
		<tr>
			<td></td>
			<td colspan="2">
				<table cellspacing="0">
					<tr>
						<td>
							<input type="button" class="consultarButton" value="Consultar"/>
						</td>
						<td>
							<div class="formSpinner" style="display:none"></div>
						</td>
					</tr>
				</table>
			</td>
		</tr>
	</table>
<?php echo Tag::endForm() ?>
