<?php

/**
 * Hotel Front-Office Solution
 *
 * LICENSE
 *
 * This source file is subject to license that is bundled
 * with this package in the file docs/LICENSE.txt.
 *
 * @package 	Back-Office
 * @copyright 	BH-TECK Inc. 2009-2010
 * @version		$Id$
 */

View::getContent();

?>
<div align="center">
	<div class="formExternal">
		<div class="externalHeader">
			<table width="95%" align="center" cellpadding="0" cellspacing="0">
				<tr>
					<td>
						<h1>
							<?php echo $title; ?>
						</h1>
					</td>
					<td align="right"><div class="window-close"></div></td>
				</tr>
			</table>
		</div>
		<div class="messages"></div>
		<table align="center">
			<?php
				//Si se da Personal es para un solo socio
				if ($personal) {
					?>
					<tr>
						<td align="right"><label for="sociosId">Socio</label></td>
						<td align="left">
							<?php
								echo HfosTag::addHyperFormSpecialField(array(
									'type' => 'Socio',
									'name' => 'sociosId',
									'classForm' => 'formExternal',
									'class' => 'sociosId'
								));
							?>
						</td>
					</tr>
					<?php
				}
			?>
			<tr>
				<td align="right"><label for="dateIni">Fecha de Factura (yyyy-mm-dd)</label></td>
				<td align="left">
					<?php
						echo Tag::select('dateIni',$facturasObj,'using: fecha_factura,fecha_factura');
					?>
				</td>
			</tr>
			<tr>
				<td align="right" colspan="2">
					<input type="button" value="Aceptar" class='selectFechaButton'/>
				</td>
				<td align="left">
					<div class="formSpinner" style="display:none"></div>
				</td>
			</tr>
		</table>
	</div>
</div>
