<?php

/**
 * Hotel Front-Office Solution
 *
 * LICENSE
 *
 * This source file is subject to license that is bundled
 * with this package in the file docs/LICENSE.txt.
 *
 * @package 	Back-Office
 * @copyright 	BH-TECK Inc. 2009-2010
 * @version		$Id$
 */

View::getContent();

?>
<div align="center">
	<div class="formExternal">
		<div class="externalHeader">
			<table width="95%" align="center" cellpadding="0" cellspacing="0">
				<tr>
					<td><h1>Envío de facturas a correos de Socios <?php if (isset($periodo)) { echo $periodo; } ?><h1></td>
					<td align="right"><div class="window-close"></div></td>
				</tr>
			</table>
		</div>
		<div class="messages"></div>
		<?php echo Tag::form('facturar/sendDelivery', 'onbeforesubmit: return false', 'autocomplete: off') ?>
			<table align="center">
                <tr>
                    <td align="right"><?php echo Tag::select('periodoAct', $periodoObj, "using: periodo,periodo", "useDummy: true", "onchange: showListToSend(this)") ?></td>
                    <td align="left"><?php echo Tag::submitButton('Enviar','class: sendButton') ?></td>
				</tr>
			</table>
			<div class="maxHeigth">
                <!-- Lista de correos a enviar-->
                <div id="listToSend"></div>
            </div>
		<?php echo Tag::endForm() ?>
	</div>
</div>
