<?php

/**
 * Hotel Front-Office Solution
 *
 * LICENSE
 *
 * This source file is subject to license that is bundled
 * with this package in the file docs/LICENSE.txt.
 *
 * @package 	Back-Office
 * @copyright 	BH-TECK Inc. 2009-2010
 * @version		$Id$
 */

$config = CoreConfig::readAppConfig();
if($config->application->mode=='development'){
	Tag::stylesheetLink('pos2/order');
	echo Tag::javascriptLibrary('windows');
	echo Tag::javascriptInclude('pos2/modal');
	echo Tag::javascriptInclude('pos2/order');
	echo Tag::javascriptInclude('pos2/numero');
} else {
	Tag::stylesheetLink('pos2/production/order', false, 'v='.ControllerBase::APP_VERSION);
	echo Tag::javascriptInclude('pos2/production/order', true, 'v='.ControllerBase::APP_VERSION);
}

View::getContent();

echo Tag::form('order/saveIngredients');

?>
<div id="modifiers">
	<div id='messages'></div>
	<table cellspacing="0" align='center' cellpadding="0" class="shadow-table" width="80%">
		<tr>
			<td class='titulo' align='left'>
				Editar Ingredientes
			</td>
		</tr>
		<tr>
			<td class="ingredients">
				<table cellspacing="0" width="100%">
					<tr>
						<td align="center">
							<div class="ingredients-div">
								<table cellspacing="0" id="tabAccount" class="lista" width="90%">
									<tbody>
										<?php
											$delete = Core::getInstancePath()."img/pos2/delete-l.gif";
											$conditions = "salon_mesas_id='".$account_id."' AND estado in ('S', 'A')";
											$accounts = $Account->find(array($conditions, 'order' => 'cuenta'));
											foreach($accounts as $account){
												echo '<tr>
													<th width="70">Comanda</th>
													<th width="70">Cuenta</th>
													<th width="70">Asiento</th>
													<th>Item</th>
													<th width="70">Cantidad</th>
												</tr>';
												$menuItem = $MenusItems->findFirst($account->menus_items_id);
												echo "<tr id='tr{$account->id}' class='orderRow'>";
												echo "<td align='right'>{$account->comanda}</td>";
												echo "<td align='right'>{$account->cuenta}</td>";
												echo "<td align='right'>{$account->asiento}</td>";
												echo "<td width='100'>{$MenusItems->nombre}</td>";
												echo "<td align='right'>{$account->cantidad}</td>";
												echo '</tr><tr><td colspan="5" align="right">
												<table cellspacing="0" width="80%" class="lista_res">
													<tr>
														<th></th>
														<th>Referencia</th>
														<th width="70">Unidad</th>
														<th width="2"></th>
														<th width="70">Cantidad</th>
														<th width="22"></th>
													</tr>
												<tr>';
												foreach($AccountInve->find("account_id='{$account->id}'") as $accountInve){
													$inve = BackCacher::getInve($accountInve->codigo);
													$unidad = BackCacher::getUnidad($inve->unidad);
													echo '<tr>
														<td>', Tag::hiddenField(array('inve[]', 'value' => $accountInve->id)), '</td>
														<td>', $inve->descripcion, '</td>
														<td>', $unidad->nom_unidad, '</td>
														<td>', Tag::hiddenField(array('estado[]', 'value' => $accountInve->estado)), '</td>
														<td align="right">', Tag::numericField(array('cantidad[]', 'size' => 7, 'class' => 'numeric', 'value' => $accountInve->cantidad)), '</td>';
														echo "<td align='center'>
															<img src='$delete' class='delete' style='cursor:pointer' alt='Borrar' title='Eliminar esta Referencia' onclick='deleteThisItem({$accountInve->id})'/>
														</td>
													</tr>";
												}

												/*foreach($AccountModifiers->find("account_id='{$account->id}'") as $acc_mod){
													$modifier = $Modifiers->findFirst($acc_mod->modifiers_id);
													if($modifier->valor>0){
														echo '+ '.$modifier->nombre;
													} else {
														if($modifier->valor<0){
															echo '- '.$modifier->nombre;
														} else {
															echo '&gt; '.$modifier->nombre;
														}
													}
													if($modifier->valor!=0){
														echo "(".sprintf("% .2f", $modifier->valor).")";
													}
												}*/
												echo '</tr></table></td></tr><tr><td>';
											}
										?>
									</tbody>
								</table>
							</div>
						<td>
						<td width="180" valign="top">
							<br/>
							<table align="center">
								<tr>
									<td>
								 		<button class='okButton'>Guardar</button>
								 	</td>
								 	<td>
								 		<input type="button" class='cancelButton' onclick='new Utils.redirectToAction("order/add/<?php echo $account_id ?>")' value="Volver"/>
								 	</td>
								</tr>
							</table>
						</td>
					</tr>
				</table>
			</td>
		</tr>
	</table>
</div>

<?php echo Tag::endForm(); ?>

<script type="text/javascript">
new Event.observe(window, "load", addIngredientsCallback)
</script>