<?php

/**
 * Hotel Front-Office Solution
 *
 * LICENSE
 *
 * This source file is subject to license that is bundled
 * with this package in the file docs/LICENSE.txt.
 *
 * @package 	Back-Office
 * @copyright 	BH-TECK Inc. 2009-2010
 * @version		$Id$
 */

$config = CoreConfig::readAppConfig();
if($config->application->mode=='development'){
	Tag::stylesheetLink('pos2/order');
	echo Tag::javascriptLibrary('windows');
	echo Tag::javascriptInclude('pos2/modal');
	echo Tag::javascriptInclude('pos2/order');
	echo Tag::javascriptInclude('pos2/numero');
	echo Tag::javascriptInclude('pos2/keyboard');
} else {
	Tag::stylesheetLink('pos2/production/order', false, 'v='.ControllerBase::APP_VERSION);
	echo Tag::javascriptInclude('pos2/production/order', true, 'v='.ControllerBase::APP_VERSION);
}

View::getContent();

?>
<table cellspacing="0" align='center' class='shadow-table'>
	<tr>
		<td class='titulo'>Agregar una Nota a un Item del Pedido</td>
	</tr>
	<tr>
		<td class="notes">
			Nota para: <?php echo $menuItem->nombre; ?><br/>
			<?php echo Tag::form('order/saveNotes') ?>
			<table cellspacing="0" cellpadding="0" align="center">
				<tr>
				 	<td valign="top">
					 	<?php echo Tag::textarea(array('texto', 'cols' => '60', 'rows' => '10', 'value' => $account->note)); ?>
				 	</td>
			 	</tr>
 				<tr>
 					<td align="right" style="padding: 10px">
						<?php echo Tag::submitButton('Guardar', 'class: okButton') ?>
						<?php echo Tag::buttonToAction('Cancelar', 'order/add/'.Session::getData('account_id'), 'cancelButton') ?>
 					</td>
 				</tr>
 			</table>
 			<?php echo Tag::endForm() ?>
		</td>
	</tr>
</table>

<script type="text/javascript">
new Event.observe(window, "load", function(){
	$('texto').activate();
})
</script>