<?php

/**
 * Hotel Front-Office Solution
 *
 * LICENSE
 *
 * This source file is subject to license that is bundled
 * with this package in the file docs/LICENSE.txt.
 *
 * @package 	Back-Office
 * @copyright 	BH-TECK Inc. 2009-2010
 * @version		$Id$
 */

$config = CoreConfig::readAppConfig();
if($config->application->mode=='development'){
	Tag::stylesheetLink('pos2/status');
} else {
	Tag::stylesheetLink('pos2/production/status', false, 'v='.ControllerBase::APP_VERSION);
	echo Tag::javascriptInclude('pos2/production/status', true, 'v='.ControllerBase::APP_VERSION);
}

?>
<div align='center'>
				<table cellspacing="0" width="800" class="shadow-table">
					<tr>
						<td class='titulo' align='left'>
							Estado del Pedido
						</td>
					</tr>
					<tr>
						<td id="statusMain" align="center">
							<br>
								<?php
									$salonMesas = $SalonMesas->find("estado='A'");
									if(count($salonMesas)){
										echo '<table cellspacing="0" cellpadding="5" align="center" class="lista_res">
										<thead>
											<th>Número Mesa</th>
											<th>Ambiente</th>
											<th>Estado</th>
											<th>Mesero</th>
											<th></th>
										</thead>
										<tbody>';
										foreach($salonMesas as $salonMesa){
											Tag::trColor(array('#CCDEFF', '#FFFFFF'));
											echo "<td align='center'>{$salonMesa->numero}</td>";
											$salon = $salonMesa->getSalon();
											$accountMaster = $AccountMaster->findFirst("salon_mesas_id=".$salonMesa->id." and estado = 'N'");
											echo "<td>{$salon->nombre}</td>";
											echo "<td>PENDIENTE</td>";
											echo "<td>{$accountMaster->nombre}</td>";
											$time = ActiveRecord::singleSelect("time_format(timediff(now(),'{$accountMaster->hora}'), '%k:%i')");
											echo "<td>$time</td>";
											echo "</tr>";
										}
										echo '</tbody>
										</table>';
									} else {
										echo '<div align="center">
											<div id="noPedidos">
												<table width="450">
													<tr>
														<td>', Tag::image("pos2/advert.png", "width: 72"), '</td>
														<td width="350">No hay pedidos activos</td>
													</tr>
												</table>
											</div>
										</div>';
									}
								?>
							<br/>
							<div align='center'>
								<button class='commandButton' onclick='new Utils.redirectToAction("appmenu")'>
									<?php echo Tag::image("pos2/home-p.png", "width: 23") ?><br>
									<b>Salir</b>
								</button>
							</div>
						</td>
					</tr>
				</table>




