<?php

/**
 * Hotel Front-Office Solution
 *
 * LICENSE
 *
 * This source file is subject to license that is bundled
 * with this package in the file docs/LICENSE.txt.
 *
 * @package 	Back-Office
 * @copyright 	BH-TECK Inc. 2009-2010
 * @version		$Id$
 */

View::getContent();

?>

<?php echo HfosTag::iconTitle('publish.png', 'Consultas de Movimiento') ?>

<?php echo Tag::form('consultas/consultar', 'class: consultasForm') ?>
<table align="center">
	<tr>
		<td valign="top">
			<table>
				<tr>
					<td align="right"><label for="cuenta">Cuenta</label></td>
					<td><?php echo HfosTag::cuentaField('cuenta') ?></td>
				</tr>
				<tr>
					<td align="right"><label for="tipo">Consultar Por</label></td>
					<td><?php echo Tag::selectStatic('tipo', array(
						'F' => 'FECHA',
						'N' => 'TERCERO',
						'D' => 'DOCUMENTOS'
					)) ?></td>
				</tr>
				<tr id="trFechaInicial" class="consulta-tr">
					<td align="right"><label for="fechaInicial">Fecha Inicial</label></td>
					<td><?php echo Tag::dateField('fechaInicial') ?></td>
				</tr>
				<tr id="trFechaFinal" class="consulta-tr">
					<td align="right"><label for="fechaFinal">Fecha Final</label></td>
					<td><?php echo Tag::dateField('fechaFinal') ?></td>
				</tr>
				<tr id="trNitInicial" class="consulta-tr" style="display:none">
					<td align="right"><label for="nitInicial">Tercero Inicial</label></td>
					<td><?php echo HfosTag::terceroField('nitInicial') ?></td>
				</tr>
				<tr id="trNitFinal" class="consulta-tr" style="display:none">
					<td align="right"><label for="nitFinal">Tercero Final</label></td>
					<td><?php echo HfosTag::terceroField('nitFinal') ?></td>
				</tr>
				<tr id="trNumeroInicial" class="consulta-tr" style="display:none">
					<td align="right"><label for="numeroInicial">Número Inicial</label></td>
					<td><?php echo Tag::numericField('numeroInicial', 'size: 5') ?></td>
				</tr>
				<tr id="trNumeroFinal" class="consulta-tr" style="display:none">
					<td align="right"><label for="numeroFinal">Número Final</label></td>
					<td><?php echo Tag::numericField('numeroFinal', 'size: 5') ?></td>
				</tr>
				<tr>
					<td align="right"></td>
					<td>
						<table cellspacing="0">
							<tr>
								<td>
									<input type="button" value="Consultar" class="buscarButton"/>
								</td>
								<td>
									<div class="formSpinner" style="display:none"></div>
								</td>
							</tr>
						</table>
					</td>
				</tr>
			</table>
		</td>
		<td valign="top">
			<div class="cuadro-cierre">
				<table>
					<tr>
						<td align="right"><b>Último Cierre</b></td>
						<td><?php echo $fechaCierre->getLocaleDate('short') ?></td>
					</tr>
					<tr>
						<td align="right"><b>Año Cierre</b></td>
						<td><?php echo $anoCierre ?></td>
					</tr>
				</table>
			</div>
		</td>
	</tr>
</table>
<?php echo Tag::endForm() ?>