<?php

/**
 * Hotel Front-Office Solution
 *
 * LICENSE
 *
 * This source file is subject to license that is bundled
 * with this package in the file docs/LICENSE.txt.
 *
 * @package 	Back-Office
 * @copyright 	BH-TECK Inc. 2009-2010
 * @version		$Id$
 */

?>
<div class="permisosPerfiles hfosContent">

	<!--  <div class="messages">
		<div class="notice">Ingrese los permisos de perfil.</div>
	</div>-->

	<?php View::getContent() ?>

</div>
