<?php

/**
 * Hotel Front-Office Solution
 *
 * LICENSE
 *
 * This source file is subject to license that is bundled
 * with this package in the file docs/LICENSE.txt.
 *
 * @package 	Back-Office
 * @copyright 	BH-TECK Inc. 2009-2010
 * @version		$Id$
 */

echo View::getContent() ?>

<script type="text/javascript">
function getCustomerId(x, li){
	$('item').setValue(li.id);
}
new Event.observe(document, 'dom:loaded', function(){
	$('item').observe('blur', function(){
		if(this.getValue()!=''){
			new Ajax.Request(Utils.getKumbiaURL('recalcula_saldos/queryByItem'), {
				parameters: 'item='+this.getValue(),
				onSuccess: function(transport){
					$('nombre').setValue(transport.responseText.evalJSON());
				}
			});
		}
	});
})
</script>

<h1>Kardex Inventario</h1>

<div align="center">
	<?php echo Tag::form(array('recalcula_saldos/proceso', 'method' => 'get', 'target' => '_blank', 'autocomplete' => 'off')) ?>
	<table>
		<tr>
			<td align="right">
				<b>Código Referencia</b>
			</td>
			<td>
				<?php echo Tag::textField('item', 'size: 7') ?>
				<?php echo Tag::textFieldWithAutocomplete('nombre', 'action: recalcula_saldos/queryReferencias', 'size: 40', 'after_update: getCustomerId') ?>
			</td>
		</tr>
		<tr>
			<td align="right">
				<b>Código Almacén</b>
			</td>
			<td>
				<?php echo Tag::select('almacen', $Almacenes->find(), 'using: codigo,nom_almacen') ?>
			</td>
		</tr>
		<tr>
			<td align="right">
				<b>Visualizar Desde</b>
			</td>
			<td>
				<?php echo Tag::dateField('fecha', 'startYear: 2004') ?>
			</td>
		</tr>
		<tr>
			<td align="right"></td>
			<td><?php echo Tag::submitButton('Consultar', 'class: controlButton') ?></td>
		</tr>
	</table>
	<?php echo Tag::endForm(); ?>
</div>