<?php

/**
 * Hotel Front-Office Solution
 *
 * LICENSE
 *
 * This source file is subject to license that is bundled
 * with this package in the file docs/LICENSE.txt.
 *
 * @package 	Back-Office
 * @copyright 	BH-TECK Inc. 2009-2010
 * @version		$Id$
 */

?>
<html>
	<head>
		<title>Planificador </title>
<style type='text/css'>

@font-face {
	font-family: 'Anivers';
	src: local('Anivers'),
		url('/h/files/pos2/Anivers.otf') format('opentype');
}

h1, h2 {
	font-family: Anivers;
}

th, td, b, span {
	font-family: Verdana;
}

h1 {
	font-size: 28px;
}

h2 {
	font-size: 22px;
}

b, span {
	font-size: 11px;
}

h1, h2 {
	margin: 0px;
}

table {
	border-top: 1px solid #969696;
	border-right: 1px solid #969696;
}

table td {
	border-left: 1px solid #969696;
	border-bottom: 1px solid #969696;
	font-size: 11px;
	padding-left: 5px;
	padding-right: 5px;
}

table th {
	background: #eaeaea;
	border-left: 1px solid #969696;
	border-bottom: 1px solid #969696;
	font-size: 11px;
	padding-left: 5px;
	padding-right: 5px;
}

table {
	background: #fff;
}


</style>

</head>
<body>
<?php View::getContent() ?>
</body>
</html>