<?php

/**
 * Hotel Front-Office Solution
 *
 * LICENSE
 *
 * This source file is subject to license that is bundled
 * with this package in the file docs/LICENSE.txt.
 *
 * @author 		BH-TECK Inc. 2009-2010
 * @version		$Id$
 */

?>

<div id="gardien">
	<table class="noAccess" align="center">
		<tr>
			<td><?php echo Tag::image('backoffice/padlock-closed.png') ?></td>
			<td>
				<h2>No tiene permiso</h2>
				<p>
					No tiene permiso para:
					<?php
						if(isset($resourceName)){
							$accessInfo = Gardien::getAccessInfo($resourceName, $actionName);
							echo $accessInfo['description'];
						}
					?>
				</p>
			</td>
		</tr>
	</table>
</div>
