<?php

/**
 * Hotel Front-Office Solution
 *
 * LICENSE
 *
 * This source file is subject to license that is bundled
 * with this package in the file docs/LICENSE.txt.
 *
 * @package 	Back-Office
 * @copyright 	BH-TECK Inc. 2009-2010
 * @version		$Id$
 */

?>

<div class="resultados"></div>

<?php echo HfosTag::iconTitle('issue.png', 'Balance de Comprobación') ?>

<?php echo Tag::form('balance/generar', 'class: balanceForm', 'autocomplete: off') ?>
<table align="center">
	<tr>
		<td valign="top">
			<table>
				<tr>
					<td align="right"><label for="tipo">Tipo</label></td>
					<td><?php echo Tag::selectStatic('tipo', array(
						'M' => 'NORMAL',
						'N' => 'NIIF'
					)) ?></td>
				</tr>
				<tr>
					<td align="right"><label for="fechaInicial">Fecha Inicial</label></td>
					<td><?php echo Tag::dateField('fechaInicial') ?></td>
				</tr>
				<tr>
					<td align="right"><label for="fechaFinal">Fecha Final</label></td>
					<td><?php echo Tag::dateField('fechaFinal') ?></td>
				</tr>
				<tr>
					<td align="right"><label for="cuentaInicial">Cuenta Inicial</label></td>
					<td><?php echo HfosTag::cuentaField('cuentaInicial') ?></td>
				</tr>
				<tr>
					<td align="right"><label for="cuentaFinal">Cuenta Final</label></td>
					<td><?php echo HfosTag::cuentaField('cuentaFinal') ?></td>
				</tr>
				<tr>
					<td align="right"><label for="nivel">Nivel</label></td>
					<td><?php echo Tag::selectStatic('nivel', array(
						'1' => '1',
						'2' => '2',
						'3' => '3',
						'4' => '4',
						'5' => '5',
						'6' => '6'
					)) ?></td>
				</tr>
				<tr>
					<td></td>
					<td>
						<table>
							<tr>
								<td><input type="checkbox" name="detallado" id="detallado" value="S"/></td>
								<td><label for="detallado">Agregar detalle de Terceros?</label></td>
							</tr>
							<tr>
								<td><input type="checkbox" id="noIncluirCierre" name="noIncluirCierre" value="S"/></td>
								<td><label for="noIncluirCierre">No incluir comprobante de cierre?</label></td>
							</tr>
							<tr>
								<td><input type="checkbox" id="soloRangoCuentas" name="soloRangoCuentas" value="S"/></td>
								<td><label for="soloRangoCuentas">Solo rango de cuentas?</label></td>
							</tr>
                            <tr>
                                <td><input type="checkbox" id="datosTercero" name="datosTercero" value="S"/></td>
                                <td><label for="datosTercero">Mostrar datos de Tercero?</label></td>
                            </tr>
						</table>
					</td>
				</tr>
				<tr>
					<td align="right"></td>
					<td>
						<table cellspacing="0">
							<tr>
								<td>
									<input type="submit" value="Generar"/>
								</td>
								<td>
									<div class="formSpinner" style="display:none"></div>
								</td>
							</tr>
						</table>
					</td>
				</tr>
			</table>
		</td>
		<td valign="top">
			<div class="cuadro-cierre">
				<table>
					<tr>
						<td align="right"><b>Último Cierre</b></td>
						<td><?php echo $fechaCierre->getLocaleDate('short') ?></td>
					</tr>
					<tr>
						<td align="right"><b>Año Cierre</b></td>
						<td><?php echo $anoCierre ?></td>
					</tr>
				</table>
			</div>
		</td>
	</tr>
</table>
<?php echo HfosTag::reportTypeTag(true, false) ?>
<?php echo Tag::endForm() ?>
