<?php

/**
 * Hotel Front-Office Solution
 *
 * LICENSE
 *
 * This source file is subject to license that is bundled
 * with this package in the file docs/LICENSE.txt.
 *
 * @author 		BH-TECK Inc. 2009-2010
 * @version		$Id$
 */

?>

<h3>CORREO INTERNO</h3>
<div class="left-panel-item inbox-div">
	Bandeja de Entrada
	<b class="badge" style="display:none">0</b>
</div>
<div class="left-panel-item compose-div">
	Redactar Mensaje
</div>
<div class="left-panel-item sent-div">
	Mensajes Enviados
</div>
<div class="left-panel-item trash-div">
	Papelera
</div>