<?php

/**
 * Hotel Front-Office Solution
 *
 * LICENSE
 *
 * This source file is subject to license that is bundled
 * with this package in the file docs/LICENSE.txt.
 *
 * @author 		BH-TECK Inc. 2009-2010
 * @version		$Id$
 */

?>
<div class="no-mail-user" align="left">
	<table>
		<tr>
			<td valign="top"><?php echo Tag::image('backoffice/icon-inbox.png') ?></td>
			<td>
				<h4>No se puede visualizar la Bandeja de Entrada</h4>
				<p>
					Es necesario enlazar su cuenta del front-office con este
					usuario del back-office para poder recibir y enviar
					mensajes a otros usuarios.
				</p>
			</td>
		</tr>
	</table>
</div>