<?php

/**
 * Hotel Front-Office Solution
 *
 * LICENSE
 *
 * This source file is subject to license that is bundled
 * with this package in the file docs/LICENSE.txt.
 *
 * @author 		BH-TECK Inc. 2009-2010
 * @version		$Id$
 */

?>
<table width='100%'>
	<tr>
		<td id='imgCon' valign='top'>
			<?php echo Tag::image(array('backoffice/blank.gif', 'class' => 'lock32')) ?>
		</td>
		<td>
    		<h1>Autenticación en el Front</h1>
    		<h2>Es necesario enlazar su cuenta del back-office a su cuenta del sistema front-office.</h2>
    	</td>
    </tr>
    <tr>
    	<td></td>
    	<td>
    		<table width="100%">
    			<tr>
    				<td><input type="radio" name="frontAccount" checked id="haveFrontAccount" value="Y"/></td>
    				<td><label for="haveFrontAccount">Tengo un usuario en el front-office</label></td>
    			</tr>
    			<tr id="haveUserForm">
    				<td></td>
    				<td align="right">
    					<table class='loginUAC'>
			    			<tr>
			    				<td align='right'><label for="login">Usuario</label></td>
			    				<td><?php echo Tag::select('usuarioFrontId', $usuarios, 'using: codusu,nombre') ?></td>
			    			</tr>
			    			<tr>
			    				<td align='right'><label for="password">Contraseña</label></td>
			    				<td><input type='password' id='password'/></td>
			    			</tr>
			    		</table>
    				</td>
    			</tr>
    			<tr>
    				<td><input type="radio" name="frontAccount" id="noHaveFrontAccount" value="N"/></td>
    				<td><label for="noHaveFrontAccount">No tengo un usuario en el front-office</label></td>
    			</tr>
    		</table>
    	</td>
    </tr>
    <tr>
    	<td align='right' colspan='2'>

    	</td>
    </tr>
    <tr>
    	<td align='right' colspan='2'>
    		<div class='buttonContainer'>
    			<table>
    				<tr>
    					<td><input type='button' value='Cerrar' class='controlButton controlButtonShadow' id='acceptButton'></td>
    					<td><input type='button' value='Continuar' class='controlButton controlButtonShadow' id='authButton'></td>
    					<td><div class='loadUAC' style='display:none'></div></td>
    				</tr>
    			</table>
    		</div>
    	</td>
    </tr>
</table>