<?php

/**
 * Hotel Front-Office Solution
 *
 * LICENSE
 *
 * This source file is subject to license that is bundled
 * with this package in the file docs/LICENSE.txt.
 *
 * @package 	Back-Office
 * @copyright 	BH-TECK Inc. 2009-2010
 * @version		$Id$
 */

?>

<?php echo HfosTag::iconTitle('limited-edition.png', 'Validación de Categorías') ?>

<div class="formContent">

<table align="center" width="100%">
	<tr>
		<td valign="top" width="50%" align="center">
			<?php echo Tag::form('validacion_categorias/reporte', 'class: validacionCategorias', 'autocomplete: off') ?>
				<table align="center">
					<tr>
						<td align="right"><label for="reportType">Formato</label></td>
						<td align="left"><?php echo Tag::selectStatic('reportType', array(
							'html' => 'HTML',
							'excel' => 'EXCEL',
							'pdf' => 'PDF',
						)) ?></td>
					</tr>
				</table>
			<?php echo Tag::endForm() ?>
		</td>
	</tr>
</table>
</div>
