<?php

/**
 * Hotel Front-Office Solution
 *
 * LICENSE
 *
 * This source file is subject to license that is bundled
 * with this package in the file docs/LICENSE.txt.
 *
 * @package 	Back-Office
 * @copyright 	BH-TECK Inc. 2009-2010
 * @version		$Id$
 */

View::getContent();

echo HfosTag::iconTitle('attibutes.png', 'Informe de socios al día');

echo Tag::form('socios_aldia/generar', 'class: sociosAldiaForm', 'target: _new') ?>
<table align="center">
	<tr>
		<td valign="top">
			<table>
				<tr>
					<td align="right"><b>Fecha Inicial</b></td>
					<td><?php echo Tag::dateField(array('fecha_ini', 'value'=>date('Y-m-01'))); ?></td>
				</tr>
				<tr>
					<td align="right"><b>Fecha Final</b></td>
					<td><?php echo Tag::dateField(array('fecha_fin', 'value'=>date('Y-m-30'))); ?></td>
				</tr>
			</table>
		</td>
	</tr>
</table>
<?php echo HfosTag::reportTypeTag(true, false) ?>
<?php echo Tag::endForm() ?>
