<?php Tag::stylesheetLink('pos2/firefox') ?>

<div id="bg-fire">
	<h1>Su explorador está desactualizado</h1>
	<p>
		Versiones anteriores de Mozilla Firefox ya no son soportadas por
		Hotel Front-Office Solution.
	</p>
	<p>
		Algunas ventajas de la última versión son:
		<ul>
			<li>Mayor velocidad y rendimiento</li>
			<li>Mejor seguridad y protección de sus datos privados</li>
			<li>Fluídez en la navegación entre menús</li>
		</ul>

		<div id="learn_more">
			<a target="_blank" href="https://affiliates.mozilla.org/link/banner/1728/3/19">Aprender más sobre Firefox</a>
		</div>

		<div align="right">
			<div align="right" class="awesome">
				<a href="https://affiliates.mozilla.org/link/banner/1728/3/19" target="_blank">Actualizar</a>
			</div>
		</div>

		<div class="small_text">
			Una vez descargado el archivo, abralo y siga los pasos del asistente hasta la pantalla "Finalizar".
			Si necesita ayuda para actualizar el navegador consulte con soporte técnico.
		</div>

	</p>
</div>
