<?php

/**
 * Hotel Front-Office Solution
 *
 * LICENSE
 *
 * This source file is subject to license that is bundled
 * with this package in the file docs/LICENSE.txt.
 *
 * @package 	Back-Office
 * @copyright 	BH-TECK Inc. 2009-2010
 * @version		$Id$
 */

?>

<?php echo HfosTag::iconTitle('transfer.png', 'Importar Movimiento Contable') ?>

<iframe class="subirFrame" name="subirFrame" style="display:none"></iframe>

<div align="center">

	<div class="subirArchivo" align="center">
		<?php echo Tag::form('incluir/subir', 'target: subirFrame', 'class: subirForm', 'enctype: multipart/form-data') ?>
			<div align="left">
				<b>Seleccione el archivo con el movimiento:</b>
			</div>
			<table align="center" width="100%">
				<tr>
					<td align="left">
						<b>Seleccione el destino del movimiento:</b>
					</td>
					<td align="left">
						<?php echo Tag::selectStatic('destino', array("M" => "Normal", "N" => "NIIF")) ?>
					</td>
				</tr>
				<tr>
					<td align="left">
						<b>Seleccione el archivo con el movimiento:</b>
					</td>
					<td align="center">
						<?php echo Tag::fileField('archivo') ?>
					</td>
				</tr>
			</table>
		<?php echo Tag::endForm() ?>
	</div>

	<div class="subirBar" style="display:none">
		<div class="subirLoadBar" align="center">
			<?php echo Tag::image('backoffice/load-bar.gif') ?>
			Subiendo archivo...
		</div>
	</div>

</div>
