<?php

/**
 * Hotel Front-Office Solution
 *
 * LICENSE
 *
 * This source file is subject to license that is bundled
 * with this package in the file docs/LICENSE.txt.
 *
 * @package 	Back-Office
 * @copyright 	BH-TECK Inc. 2009-2010
 * @version		$Id$
 */
?>

<h2>Plan de Cuentas</h2>

<div class="formContent">

	<div class="cuentasForm" align="center">
		<table cellspacing="0" cellpadding="0" class="hyBrowseTab zebraSt sortable">
			<tbody>
				<tr>
					<th><label for="cuenta">Código</label></th>
					<th colspan="2"><label for="nombreCuenta">Nombre</label></th>
				</tr>
				<tr>
					<td><input type="text" id="cuenta" size="12" class="cuenta"/></td>
					<td colspan="2"><input type="text" id="nombreCuenta" size="50"/></td>
				</tr>
			</tbody>
			<tbody class="resultadoCuentas"></tbody>
		</table>
	</div>

</div>
