<?php

/**
 * Hotel Front-Office Solution
 *
 * LICENSE
 *
 * This source file is subject to license that is bundled
 * with this package in the file docs/LICENSE.txt.
 *
 * @package 	Back-Office
 * @copyright 	BH-TECK Inc. 2009-2010
 * @version		$Id$
 */

$config = CoreConfig::readAppConfig();
if($config->application->mode=='development'){
	Tag::stylesheetLink('pos2/tables');
	echo Tag::javascriptInclude('pos2/tables');
	echo Tag::javascriptInclude('pos2/keyboard');
} else {
	Tag::stylesheetLink('pos2/production/tables', false, 'v='.ControllerBase::APP_VERSION);
	echo Tag::javascriptInclude('pos2/production/tables', true, 'v='.ControllerBase::APP_VERSION);
}

View::getContent();

$Datos->findFirst();
if ($salon->venta_a=='H') {
	$habitaciones = array();
	foreach ($Habitacion->find() as $habitacion) {
		$habitaciones[$habitacion->numhab] = true;
	}
}

?>

<div align="center">
<div id='messages'></div>
<div>
	<table cellspacing='0' cellpadding='0' class="shadow-table" style="width:97%">
		<tr>
			<td class='titulo'>
				Seleccione un Ambiente<br>
				<div id='selectMesa'>
					<?php echo Tag::form("tables/openTable") ?>
					<?php if(Session::get("salon_type")!="H"): ?>
						<span class='selamesa'>Seleccione ó digite el número de mesa <?php echo Tag::numericField("numero", "size: 4", "autocomplete: off") ?> </span>
					<?php else: ?>
						<span class='selamesa'>Seleccione ó digite el número de habitación <?php echo Tag::numericField("numero", "size: 4", "autocomplete: off") ?></span>
					<?php endif ?>
					</td>
					<?php echo Tag::endForm() ?>
				</div>
			</td>
		</tr>
	<tr>
	<td valign="top">
	    <table cellspacing='0' cellpadding='0' width="100%">
	    <tr>
	    <td valign="top" class="mesasPanel">
	 	<table cellspacing='0' align="center" class="mesasTable">
	 		<tr>
	 		<?php

	 			$libre = null;
	 			$usuarioId = Session::get("usuarios_id");
	 			if($salon->venta_a=='H'){
		 			$pictureHtml = Tag::image("pos2/users-p.png");
		 			$pictureHtmlDisabled = Tag::image("pos2/users-pb.png");
	 			} else {
	 				$pictureTable = Tag::image('pos2/mesa.png');
	 			}
	 			for($j=0;$j<$salon->alto_mesas;++$j){
				  	echo "<tr>";
				  	for($i=0;$i<$salon->ancho_mesas;++$i){
				  		echo "<td class='tableCell' id='tx$i"."_"."$j'>";
				  		$salonMesa = $SalonMesas->findFirst("salon_id='{$salon->id}' AND vpos='$j' AND hpos='$i'");
						if($salonMesa){
							if($salonMesa->estado=='N'){
								if($libre===null){
									$libre = $salonMesa->numero;
								}
								echo "<div class='mesaB mesaButton mesaLibre numero", $salonMesa->numero, "' id='{$salonMesa->id}'>";
								if($salon->venta_a=='H'){
									if(isset($habitaciones[$salonMesa->numero])){
										echo $pictureHtml;
										echo "<div>", $salonMesa->numero, "</div>";
									} else {
										echo $pictureHtmlDisabled;
										echo "<div class='numeroHab'>", $salonMesa->numero, "</div>";
									}
								} else {
									echo $pictureTable;
									echo '<div class="numeroMesa">', $salonMesa->numero, '</div>';
								}
								echo "</div></td>";
				 			} else {
				 				echo "<div class='mesaB mesaButton2 mesaOcupada numero{$salonMesa->numero} mesero".$usuarioId."' id='{$salonMesa->id}'>";
								$accountMaster = $AccountMaster->findFirst("salon_mesas_id='{$salonMesa->id}' and estado='N'");
								if($accountMaster){
									$nombre = i18n::substr(i18n::substr($accountMaster->nombre, 0, strpos($accountMaster->nombre." ", " ")), 0, 8);
									$nombreCliente = "PARTICULAR";
									foreach($AccountCuentas->find("account_master_id='$accountMaster->id'") as $accountCuenta){
										if($accountCuenta->clientes_nombre!='PARTICULAR'){
											$nombreCliente = i18n::substr(i18n::substr($accountCuenta->clientes_nombre, 0, strpos($accountCuenta->clientes_nombre." ", " ")), 0, 8);
										}
									}
								} else {
									$nombre = "";
									$nombreCliente = 'PARTICULAR';
								}
								echo "<span class='mesero_name'><br>", i18n::strtoupper($nombre), "<br></span>";
								echo "<span style='display:none' class='cliente_name'><br>", i18n::strtoupper($nombreCliente), "<br></span>";
								echo '<span class="tiempo">', ActiveRecord::singleSelect("time_format(timediff(concat('{$Datos->getFecha()} ', current_time()), '$AccountMaster->hora'), '%H:%i')"), '</span>';
								echo "<br/>";
								echo '<span class="numeroOcupado">', $salonMesa->numero, '</span>';
								echo "</div>";
				 			}
						} else {
							echo "&nbsp;";
						}
						echo "</td>";
				  	}
	 			}

			?>
			</tr>
	 	</table>
	 	</td>
	 	<td class='rightSide' valign="top">

			<p class='subTitle' align='center' id="salonOptions">
		 		<b>SELECCIONAR AMBIENTE</b>
	 		<?php
	 			$usuarioId = Session::get("usuarios_id");
	 			$query = new ActiveRecordJoin(array(
	 				'fields' => array('{#Salon}.id', '{#Salon}.nombre'),
	 				'entities' => array('Salon', 'Permisos'),
	 				'conditions' => "salon.estado = 'A' AND usuarios_id='$usuarioId'"
	 			));
	 			foreach($query->getResultSet() as $usuarioSalon){
	 			  	if($usuarioSalon->id==$salon->id){
	 			  		echo "<input type='button' value='".$usuarioSalon->nombre."' class='salonButton salonSelected' onclick='showSalon(".$usuarioSalon->id.")'><br>";
	 			  	} else {
				 		echo "<input type='button' value='".$usuarioSalon->nombre."' class='salonButton salonUnselected' onclick='showSalon(".$usuarioSalon->id.")'><br>";
	 			  	}
				}
			?>
			</p>

			<?php if ($salon->venta_a=='C'): ?>
	 		<p class='subTitle' align='center' id="viewOptions">
		 		<b>VISUALIZAR</b>
		 		<button id='showTodas' class='salonOption' onclick='showTodas(this)'>Ver To<u>d</u>as</button><br>
		 		<button id='showAbiertas' class='salonOption salonOptionUnselected' onclick='showAbiertas(this)'>Ver Mesas <u>A</u>biertas</button><br>
		 		<button id='showLibres' class='salonOption salonOptionUnselected' onclick='showLibres(this)'>Ver Mesas <u>L</u>ibres</button><br>
		 		<button id='showMisMesas' class='salonOption salonOptionUnselected' onclick='showMisMesas(<?php echo Session::get("usuarios_id") ?>, this)'>Ver <u>M</u>is Mesas</button><br>
		 		<button id='showClientes' class='salonOption salonOptionUnselected' onclick='showClientes(this)'>Ver <u>C</u>liente</button><br>
			</p>
			<?php endif; ?>
			<br/>
			<?php if(Session::get('role')=='Administradores'){ ?>
				<p class='subTitle' align='center' id='viewOptions'>
					<button id='editarButton' title='<?php echo $salon->id ?>'>
						<?php echo Tag::image("pos2/tools-pb.png", "width: 23") ?><br>
						<b>Editar Ambiente</b>
					</button>
				</p>
			<?php } ?>
				<button id='cancelButton' onclick='new Utils.redirectToAction("appmenu")'>
					<?php echo Tag::image("pos2/home-pb.png", "width: 23") ?><br>
					<b>Volver al Menú</b>
				</button>
			<br/>
			<br/><br/>
			<div id="basura" style="display:none" align="center">
				<?php echo Tag::image(array('pos2/trash.gif')) ?>
			</div>
	 	</td>
	 	</table>
	 </td>
 	</tr>
 </table>
</div>

<!--<div id="virtualkb-button" onclick="new VirtualKeyBoard(this); return false">
 	<?php echo Tag::image('pos2/keyboard.png') ?>
</div>-->

</div>

<?php

if($sendkitchen){
	if(file_exists('public/temp/'.$sendkitchen.'.html')){
		echo "
		<script type='text/javascript'>
			window.open(\"" . Core::getInstancePath() . "temp/$sendkitchen.html\", null, 'width=300, height=700, toolbar=no, statusbar=no');
		</script>";
	}
}

?>
<script type='text/javascript'>
new Event.observe(window, "load", function(){
	$("numero").setValue("<?php echo $libre===null ? "" : $libre ?>");
	//$("numero").activate();
	$$(".numero<?php echo $libre ?>").each(function(element){
		element.addClassName("mesaSelected");
	});
	$("numero").observe("keyup", function(event) {
		var numero = this.value;
		$$(".mesaSelected").each(function(element) {
			element.removeClassName("mesaSelected");
		});
		$$(".numero" + numero).each(function(element) {
			element.addClassName("mesaSelected");
		});
	});
	<?php echo "Mesas.venta_a = '".$salon->venta_a."'\n" ?>
});
</script>