<?php

/**
 * Hotel Front-Office Solution
 *
 * LICENSE
 *
 * This source file is subject to license that is bundled
 * with this package in the file docs/LICENSE.txt.
 *
 * @package 	Back-Office
 * @copyright 	BH-TECK Inc. 2009-2010
 * @version		$Id$
 */

View::getContent();

if (!count($movimientos)){
	echo Flash::error("No existe el movimiento a mostrar");
	exit;
}

echo '
<table cellspacing="0" cellpadding="0" width="98%">
	<tr>
		<td><h2>', $nombreComprobante, '/', $numero, '</h2></td>
		<td align="right">
			<div class="fecha-comprob">Fecha: ', $fechaComprobante->getLocaleDate('medium'), '</div>
		</td>
	</tr>
</table>

<form method="post" onbeforesubmit="return false">

<div class="formContent formEdit">';

$numero = -1;
echo '<div class="gridEdit">
<table class="sortable movimiento-grid" cellspacing="0" align="center"><thead>
<tr>
	<th class="sortcol sortasc" colspan="2">&nbsp;</th>
	<th class="sortcol">Cuenta</th>
	<th class="sortcol">Nombre Cuenta</th>
	<th class="sortcol">Descripción</th>
	<th class="sortcol">Valor</th>
	<th class="sortcol">Naturaleza</th>
</tr></thead><tbody>';
foreach($movimientos as $movimiento){
	echo '<tr class="movimiento', $movimiento['numero'], ' naturaleza', $movimiento['naturaleza'], '">
	<td class="numero">', ($movimiento['numero']+1), '</td>
	<td>',
	Tag::checkboxField(array(
		'cuentaCheck'
	)),
	'</td><td>',
	Tag::numericField(array(
		'cuenta'.$movimiento['numero'],
		'value' => $movimiento['cuenta'],
		'class' => 'cuenta',
		'size' => 10
	)),
	'</td><td>',
	Tag::textField(array(
		'nombreCuenta'.$movimiento['numero'],
		'value' => $movimiento['nombreCuenta'],
		'class' => 'nombreCuenta',
		'size' => 25
	)),
	'</td><td>',
	Tag::textField(array(
		'descripcion'.$movimiento['numero'],
		'value' => $movimiento['descripcion'],
		'class' => 'descripcion',
		'size' => 25
	)),
	'</td><td>',
	Tag::numericField(array(
		'valor'.$movimiento['numero'],
		'value' => $movimiento['valor'],
		'class' => 'valor',
		'size' => 13,
		'maxlength' => 17
	)),
	'</td>
	<td>',
	Tag::selectStatic(array(
		'naturaleza'.$movimiento['numero'],
		array(
			'D' => 'DEBITO',
			'C' => 'CREDITO'
		),
		'value' => $movimiento['naturaleza'],
		'class' => 'naturaleza'
	)),
	'</td>
	</tr>';
	$numero = $movimiento['numero'];
}
$numero++;
echo '<tr class="movimiento', $numero, ' naturalezaD">
	<td class="numero">', ($numero+1), '</td>
	<td>',
	Tag::checkboxField(array(
		'cuentaCheck'
	)),
	'</td><td>',
	Tag::numericField(array(
		'cuenta'.$numero,
		'class' => 'cuenta',
		'size' => 10
	)),
	'</td><td>',
	Tag::textField(array(
		'nombreCuenta'.$numero,
		'class' => 'nombreCuenta',
		'size' => 25
	)),
	'</td><td>',
	Tag::textField(array(
		'descripcion'.$numero,
		'class' => 'descripcion',
		'size' => 25
	)),
	'</td><td>',
	Tag::numericField(array(
		'valor'.$numero,
		'class' => 'valor',
		'size' => 13,
		'maxlength' => 17
	)),
	'</td>
	<td>',
	Tag::selectStatic(array(
		'naturaleza'.$numero,
		array(
			'D' => 'DEBITO',
			'C' => 'CREDITO'
		),
		'class' => 'naturaleza'
	)),
	'</td>
</tr>';

echo '</tbody></table>

</form>

</div></div>';