<?php

/**
 * Hotel Front-Office Solution
 *
 * LICENSE
 *
 * This source file is subject to license that is bundled
 * with this package in the file docs/LICENSE.txt.
 *
 * @package 	Back-Office
 * @copyright 	BH-TECK Inc. 2009-2014
 * @version		$Id$
 */

View::getContent();

?>
<div align="center">
	<div class="formExternal">
		<div class="externalHeader">
			<table width="95%" align="center" cellpadding="0" cellspacing="0">
				<tr>
					<td><h1>Imprimir<h1></td>
					<td align="right"><div class="window-close"></div></td>
				</tr>
			</table>
		</div>
		<div class="messages"></div>
		<?php echo Tag::form(array('movimiento_niif/reporte', 'onbeforesubmit' => 'return false', 'autocomplete' => 'off')) ?>
			<table align="center">
				<tr>
					<td align="right"><label for="reportType">Formato</label></td>
					<td align="left"><?php echo Tag::selectStatic('reportType', array(
						'html' => 'HTML',
						'excel' => 'EXCEL',
						'text' => 'TEXTO PLANO',
					)) ?></td>
					<td align="right"><?php echo Tag::submitButton('Imprimir') ?></td>
				</tr>
				<tr>
					<td align="right"><label for="orden">Orden</label></td>
					<td align="left"><?php echo Tag::selectStatic('orden', array(
						'F' => 'FOLIO',
						'C' => 'CUENTA',
						'N' => 'NATURALEZA',
						'S' => 'SIN ORDEN'
					)) ?></td>
				</tr>
				<tr>
					<td align="right"><label for="reportType">Tipo</label></td>
					<td align="left"><?php echo Tag::selectStatic('tipo', array(
						//'N' => 'NORMAL',
						'I' => 'NIIF',
					)) ?></td>
				</tr>
			</table>
			<?php echo Tag::hiddenField('codigoComprobante', 'value: ' . $codigoComprobante) ?>
			<?php echo Tag::hiddenField('numero', 'value: ' . $numero) ?>
		<?php echo Tag::endForm() ?>
	</div>
</div>
