<?php

/**
 * Hotel Front-Office Solution
 *
 * LICENSE
 *
 * This source file is subject to license that is bundled
 * with this package in the file docs/LICENSE.txt.
 *
 * @package 	Back-Office
 * @copyright 	BH-TECK Inc. 2009-2010
 * @version		$Id$
 */

?>
<div align="center">
	<div class="formExternal">
		<div class="externalHeader">
			<table width="95%" align="center" cellpadding="0" cellspacing="0">
				<tr>
					<td><h1>Ver Cartera<h1></td>
					<td align="right"><div class="window-close"></div></td>
				</tr>
			</table>
		</div>
		<div class="messages"><?php View::getContent() ?></div>
		<?php
			echo Tag::form('movimiento_niif/tomarCartera', 'onbeforesubmit: return false', 'autocomplete: off');
			if(isset($carteras)){
				echo '<table class="tablaDatosCartera">
					<tr>
						<td align="right"><b>Documento</b></td><td>', $tercero->getNit(), '</td>
					</tr>
					<tr>
						<td align="right"><b>Nombre</b></td><td>', $tercero->getNombre(), '</td>
					</tr>
				</table>
				<table class="hyBrowseTab zebraSt sortable" cellspacing="0" cellpadding="0" id="carteraTable" width="90%">
					<thead>
						<tr>
							<th class="nosort"></th>
							<th class="sortcol">Documento</th>
							<th class="sortcol">F. Emisión</th>
							<th class="sortcol">F. Vence</th>
							<th class="sortcol">Saldo</th>
						</tr>
					</thead>
					<tbody>';
				foreach ($carteras as $cartera)
				{
					echo '<tr>
						<td><input type="radio" name="numeroDoc" value="', $cartera->getTipoDoc(), '-', $cartera->getNumeroDoc(), '"/></td>
						<td>', $cartera->getTipoDoc(), '-', $cartera->getNumeroDoc(), '</td>
						<td>', $cartera->getFEmision(), '</td>
						<td>', $cartera->getFVence(), '</td>
						<td align="right">', Currency::number($cartera->getSaldo()), '</td>
					</tr>';
					unset($cartera);
				}
				echo '</tbody></table>';
				echo '<div align="right">', Tag::submitButton('Tomar'), '</div>';
				echo Tag::hiddenField(array('cuenta', 'value' => $codigoCuenta));
				echo Tag::hiddenField(array('nit', 'value' => $tercero->getNit()));
			} else {
				echo '<div align="right">', Tag::submitButton('Cerrar'), '</div>';
			}
			echo Tag::endForm();
		?>
	</div>
</div>
