<?php

/**
 * Hotel Front-Office Solution
 *
 * LICENSE
 *
 * This source file is subject to license that is bundled
 * with this package in the file docs/LICENSE.txt.
 *
 * @package 	Back-Office
 * @copyright 	BH-TECK Inc. 2009-2010
 * @version		$Id$
 */

View::getContent();

echo HfosTag::iconTitle('credit-card.png', 'Importar Pagos');

?>

<div style="" class="hyImportDiv hyFormDiv">
	<div align="center">
		<div style="display:none" class="subirBar">
			<div align="center" class="subirLoadBar">
				<img alt="" src="/payande/h/img/backoffice/load-bar.gif">
				Importando archivo, por favor espere...
			</div>
		</div>
	</div>

	<iframe style="display:none" name="importar_pagosSubirFrame" class="subirFrame"></iframe>

	<table width="100%" class="importTable">
		<tbody>
			<tr>
				<td width="50%" valign="top" align="center">
					<div align="center" class="subirArchivo">
						<?php echo Tag::form('importar_pagos/generar', 'class: importarPagosForm', 'enctype: multipart/form-data', 'target: importar_pagosSubirFrame'); ?>
							<div align="left">
								<label>Seleccione el archivo</label>
							</div>
							<table width="100%" align="center">
								<tbody>
									<tr>
										<td align="center" colspan="2">
											<input type="file" name="archivo" id="archivo" class="archivo">
										</td>
									</tr>
									<tr>
										<td align="left">
											<label for="comprob"><b>Comprobante</b></label>
										</td>
										<td align="left">
											<?php 
												$comprobsPagos = Settings::get("comprobs_pagos", "SO");
												$c = explode(",", $comprobsPagos);
												$d = implode($c, "','"); 
												echo Tag::select("comprob", EntityManager::get("Comprob")->find(array("conditions" => "codigo IN ('$d')", "order" => "codigo ASC")), "using: codigo,nom_comprob");
											?>
										</td>
									</tr>
									<tr>
										<td align="left">
											<label for="fecha"><b>Fecha Pago</b></label>
										</td>
										<td align="left">	
											<?php 
												echo Tag::dateField("fecha");
											?>
										</td>
									</tr>
								</tbody>
							</table>
						</form>
					</div>
				</td>
				<td width="50%">
					<div class="infoBox">Por medio de esta opción se puede importar pagos de socios <br>
						desde un archivo de Microsoft Excel 2007 ó superior.</div>
					<div class="infoBox">Para una correcta importación de los datos, el archivo debe <br>
						tener las siguientes columnas:<br><br>	
						<table cellspacing="0" class="importInfo">
							<tbody>
								<tr>
									<td align="right">
										<label>Número de Acción</label>
									</td>
									<td>Texto. Máximo 10 carácteres. Obligatorio</td>
								</tr>
								<tr>
									<td align="right">
										<label>Valor Pago</label>
									</td>
									<td>Valor númerico, sin decimales. Obligatorio</td>
								</tr>
							</tbody>
						</table>
					</div>
				</td>
			</tr>
		</tbody>
	</table>
</div>