<?php

/**
 * Hotel Front-Office Solution
 *
 * LICENSE
 *
 * This source file is subject to license that is bundled
 * with this package in the file docs/LICENSE.txt.
 *
 * @package 	Back-Office
 * @copyright 	BH-TECK Inc. 2009-2010
 * @version		$Id$
 */

?>
<select name='cuenta<?php echo $_GET['n'] ?>' style='width:250px;font-size:12px'>
	<option value='@'>Seleccione...</option>
	<?php
		foreach($cuentas as $cuenta){
			echo "<option value='$cuenta->numcue'>$cuenta->nombre\n";
		}
	?>
</select>