<?php

/**
 * Hotel Front-Office Solution
 *
 * LICENSE
 *
 * This source file is subject to license that is bundled
 * with this package in the file docs/LICENSE.txt.
 *
 * @package 	Back-Office
 * @copyright 	BH-TECK Inc. 2009-2010
 * @version		$Id$
 */

?>
<h2>Mesa #<?php echo  Session::get_data('numero_mesa') ?></h2>
<table>
<tr>
<td>Comanda Activa:</td>
<td>
<select id='comandas' onchange='new AJAX.execute({ action:"order/setComanda/"+$("comandas").options[$("comandas").selectedIndex].value })'>
<?php
	$sessionNumeroComanda = Session::get_data('numero_comanda');
	if($Account->count("distinct: comanda", "conditions: salon_mesas_id=".Session::get_data("account_id")." and estado <> 'C'")){
		foreach($Account->distinct("comanda") as $comanda){
			if($comanda==$sessionNumeroComanda){
				print "<option value='$comanda' selected>$comanda\n";
			} else {
				print "<option value='$comanda'>$comanda\n";
			}
		}
	}
?>
</select>
</td>
<td>
<?php echo  img_tag('plus.gif', 'style: cursor:pointer', 'onclick: addComanda()', 'title: Agregar Comanda') ?>
</td>
<td>
<?php echo  img_tag('minus.gif', 'style: cursor:pointer', 'onclick: deleteComanda()', 'title: Eliminar Comanda Actual') ?>
</td>
</tr>
</table>
<textarea rows="35" cols="33" class="smallTextArea" readonly="yes">
 -------------------------------
 Cajero: <?php echo  Session::get_data('usuarios_nombre'); ?>
 -------------------------------
<?php

		$total = 0;
		$tiva = 0;
		$tser = 0;
		$totr = 0;
		$comanda = "";
		$sessionAccountId = Session::get_data("account_id");
		foreach ($Account->find("conditions: salon_mesas_id=" . $sessionAccountId . " and estado <> 'C'", "order: comanda desc" ) as $AccountItem){
			if ($comanda != $AccountItem->comanda) {
				print "\nComanda {$AccountItem->comanda}:\n";
				$comanda = $AccountItem->comanda;
			}
			$MenusItems->find($AccountItem->menus_items_id);
			$t = $AccountItem->valor * $AccountItem->cantidad;
			$total+=$t;
		  	print " ".sprintf("% 2s", $AccountItem->cantidad)." *".
			sprintf("% -".(23-strlen($AccountItem->valor))."s", i18n::substr($MenusItems->nombre, 0, 17)).
			sprintf("% 8.2f", $t)."\n";
			foreach($AccountModifiers->find("salon_mesas_id=".$sessionAccountId." and menus_items_id=".$MenusItems->id) as $acc_mod){
				$Modifiers->find($acc_mod->modifiers_id);
				#print "    + ".$Modifiers->nombre." ({$Modifiers->valor})\n";
				print "   + ".sprintf("% -".(23-strlen($Modifiers->valor))."s", substr($Modifiers->nombre, 0, 15)).
				sprintf("% 8.2f", $Modifiers->valor)."\n";;
				$total+=$Modifiers->valor;
			}
			$tiva += $t * $AccountItem->porcentaje_iva/100;
			$tser += $t * $AccountItem->porcentaje_servicio/100;
			$totr += $t * $AccountItem->porcentaje_otros/100;
		}

		if($AccountDiscount->findFirst("salon_mesas_id=".Session::getData("account_id"))){
		  	$Discount->find($AccountDiscount->discount_id);
		  	print "\n ".
			sprintf("% -20s", "Desc. ".
			substr($Discount->nombre, 0, 12));
		  	if($AccountDiscount->tipo=='P'){
		  	  	print ($AccountDiscount->valor*100)."% ";
		  	  	$desc = $AccountDiscount->valor * $total;
		 		print "($desc)";
		 	} else {
		 	  	$desc = $AccountDiscount->valor;
		 		print "(".$AccountDiscount->valor.")";
		 	}
		 	print "\n";
		}
?>

      &gt;&gt; <?php echo  date("d-m-Y h:i") ?> &lt;&lt;
</textarea>
<table align='center' width="200" cellspacing="0" style='border:1px solid #808080;background:white'>
<tr>
	<td colspan="2" style='font-size:30px;color:#BF0000;background:#FFD7EB;border:1px solid #BF0000' align="center">
	<b>TOTAL:<br>
	<?php echo  number_format($total-$desc, 2, ".", ",") ?></b></td>
</tr>
</table>