<?php

/**
 * Hotel Front-Office Solution
 *
 * LICENSE
 *
 * This source file is subject to license that is bundled
 * with this package in the file docs/LICENSE.txt.
 *
 * @package 	Back-Office
 * @copyright 	BH-TECK Inc. 2009-2010
 * @version		$Id$
 */

View::getContent() ?>

<table cellspacing="0" width="830" align='center' summary="" cellpadding="0">
	<tr>
		<td class='titulo' align="center">
			Liquidación de Cuentas/Facturas
		</td>
	</tr>
	<tr>
		<td align="center" class="pay_content">

			<div id="abrir_cajas">
				<table align='center'>
					<tr>
						<td><?php echo Tag::image('pos2/advert.png') ?></td>
						<td>
							Debe abrir una caja antes de liquidar cuentas<br><br>
							<div align="right">
								<?php  echo Tag::buttonToAction('Ir a Cajas', "cashouttro/?pay=".$id, 'flowButton') ?>
							</div>
						</td>
					</tr>
				</table>
			</div>

			<br>
				<button class='commandButton' onclick='new Utils.redirectToAction("appmenu")'>
					<?php echo Tag::image("pos2/home-p.png", "width: 23") ?><br>
					<b>Salir</b>
				</button>
			</br>

		</td>
	</tr>
</table>