<?php

/**
 * Hotel Front-Office Solution
 *
 * LICENSE
 *
 * This source file is subject to license that is bundled
 * with this package in the file docs/LICENSE.txt.
 *
 * @package 	Back-Office
 * @copyright 	BH-TECK Inc. 2009-2010
 * @version		$Id$
 */

?>
<div style="padding:20px">
	<div align="right">
		<?php echo Tag::submitButton('Guardar', 'class: controlButton') ?>
	</div>
	<table class="lista_res sortable" cellspacing="0" id="modifiersTable">
		<thead>
			<tr>
				<th></th>
				<th class="sortcol">Nombre</th>
				<th class="sortcol">Tipo</th>
			</tr>
		</thead>
		<tbody>
			<?php foreach($modifiers as $modifier){ ?>
				<?php
					$rowCount = $MenusItemsModifiers->count("menus_items_id = '$menuItemId' AND modifiers_id = '{$modifier->id}'");
					if($rowCount>0){
						echo '<tr class="selectedRow">';
					} else {
						echo '<tr>';
					}
				?>
					<td><input type="checkbox" class="check_mod" name="modifier[]" value="<?php echo $modifier->id ?>" <?php echo $rowCount>0 ? "checked='checked'" : "" ?>/></td>
					<td><?php echo $modifier->nombre ?></td>
					<td><?php echo $modifier->getTipoDetalle() ?></td>
				</tr>
			<?php } ?>
		</tbody>
	</table>

	<div align="right">
		<?php echo Tag::submitButton('Guardar', 'class: controlButton') ?>
	</div>

</div>
