<?php

/**
 * Hotel Front-Office Solution
 *
 * LICENSE
 *
 * This source file is subject to license that is bundled
 * with this package in the file docs/LICENSE.txt.
 *
 * @package 	Back-Office
 * @copyright 	BH-TECK Inc. 2009-2010
 * @version		$Id$
 */

?>

<script type="text/javascript">

function getCustomerId(x, li){
	$('item').setValue(li.id);
}

new Event.observe(document, 'dom:loaded', function(){
	$('item').observe('blur', function(){
		if(this.getValue()!=''){
			new Ajax.Request(Utils.getKumbiaURL('recalcula_saldos/queryByItem'), {
				parameters: 'item='+this.getValue(),
				onSuccess: function(transport){
					$('nombre').setValue(transport.responseText.evalJSON());
				}
			});
		}
	});
})
</script>

<h1>Análisis Detallado de Consumos</h1>

<?php echo Tag::form("analisis_detallado/procesar") ?>
<table align="center">
	<tr>
		<td align="right">
			<b>Código Referencia</b>
		</td>
		<td>
			<?php echo Tag::textField('item', 'size: 7') ?>
			<?php echo Tag::textFieldWithAutocomplete('nombre', 'action: recalcula_saldos/queryReferencias', 'size: 40', 'after_update: getCustomerId') ?>
		</td>
	</tr>
	<tr>
		<td align="right">
			<b>Fecha Inicial</b>
		</td>
		<td>
			<?php echo Tag::dateField('fechaInicial') ?>
		</td>
	</tr>
	<tr>
		<td align="right">
			<b>Fecha Final</b>
		</td>
		<td>
			<?php echo Tag::dateField('fechaFinal') ?>
		</td>
	</tr>
	<tr>
		<td align="right"></td>
		<td><?php echo Tag::submitButton('Consultar', 'class: controlButton') ?></td>
	</tr>
</table>
<?php

echo Tag::endForm();

echo View::getContent(); ?>