<?php

/**
 * Hotel Front-Office Solution
 *
 * LICENSE
 *
 * This source file is subject to license that is bundled
 * with this package in the file docs/LICENSE.txt.
 *
 * @package 	Back-Office
 * @copyright 	BH-TECK Inc. 2009-2010
 * @version		$Id$
 */

?>

<div id="virtual-keyboard">
	<div id="keyrow keyrow0" align="center">
		<table>
			<tr>
				<td><div class="key">Q</div></td>
				<td><div class="key">W</div></td>
				<td><div class="key">E</div></td>
				<td><div class="key">R</div></td>
				<td><div class="key">T</div></td>
				<td><div class="key">Y</div></td>
				<td><div class="key">U</div></td>
				<td><div class="key">I</div></td>
				<td><div class="key">O</div></td>
				<td><div class="key">P</div></td>
				<td><div class="key"><?php echo Tag::image('pos2/backspace.png') ?></div></td>
			</tr>
		</table>
	</div>
	<div id="keyrow keyrow1" align="center">
		<table>
			<tr>
				<td><div class="key">A</div></td>
				<td><div class="key">S</div></td>
				<td><div class="key">D</div></td>
				<td><div class="key">F</div></td>
				<td><div class="key">G</div></td>
				<td><div class="key">H</div></td>
				<td><div class="key">J</div></td>
				<td><div class="key">K</div></td>
				<td><div class="key">L</div></td>
				<td><div class="key">Ñ</div></td>
			</tr>
		</table>
	</div>
	<div id="keyrow keyrow2" align="center">
		<table>
			<tr>
				<td><div class="key">Z</div></td>
				<td><div class="key">X</div></td>
				<td><div class="key">C</div></td>
				<td><div class="key">V</div></td>
				<td><div class="key">B</div></td>
				<td><div class="key">N</div></td>
				<td><div class="key">M</div></td>
				<td><div class="key">,</div></td>
				<td><div class="key">.</div></td>
			</tr>
		</table>
	</div>
	<div id="keyrow keyrow2" align="center">
		<table>
			<tr>
				<td><div class="key keyspace">&nbsp;</div></td>
			</tr>
		</table>
	</div>
	<div align="center">
		<div id="exit"></div>
	</div>
</div>