<?php

/**
 * Hotel Front-Office Solution
 *
 * LICENSE
 *
 * This source file is subject to license that is bundled
 * with this package in the file docs/LICENSE.txt.
 *
 * @package 	Back-Office
 * @copyright 	BH-TECK Inc. 2009-2010
 * @version		$Id$
 */

?>
<div align="center">
	<div class="formExternal">
		<div class="externalHeader">
			<table width="95%" align="center" cellpadding="0" cellspacing="0">
				<tr>
					<td><h1>Copiar un Comprobante<h1></td>
					<td align="right"><div class="window-close"></div></td>
				</tr>
			</table>
		</div>
		<div class="messages"></div>
		<?php echo Tag::form('movimiento/prepararCopia', 'onbeforesubmit: return false', 'autocomplete: off') ?>
			<table align="center">
				<tr>
					<td align="right"><label for="nit">Comprobante</label></td>
					<td align="left"><?php echo Tag::select('codigoComprobante', $comprobs, 'using: codigo,nom_comprob') ?></td>
				</tr>
				<tr>
					<td align="right"><label for="fechaComprobante">Fecha</label></td>
					<td align="left"><?php echo Tag::dateField('fechaComprobante', 'startYear: 1995', 'class: date-field') ?></td>
				</tr>
				<tr>
					<td></td>
					<td align="right"><?php echo Tag::submitButton('Copiar') ?></td>
				</tr>
			</table>
			<?php echo Tag::hiddenField('comprobanteOrigen', 'value: '.$codigoComprobante) ?>
			<?php echo Tag::hiddenField('numeroOrigen', 'value: '.$numero) ?>
		<?php echo Tag::endForm() ?>
	</div>
</div>