<?php

/**
 * Hotel Front-Office Solution
 *
 * LICENSE
 *
 * This source file is subject to license that is bundled
 * with this package in the file docs/LICENSE.txt.
 *
 * @package 	Back-Office
 * @copyright 	BH-TECK Inc. 2009-2010
 * @version		$Id$
 */

View::getContent();

?>

<?php echo HfosTag::iconTitle('document-library.png', 'Movimiento Contable') ?>

<div class="formContent">

	<div class="formBusqueda formPannel">

		<?php echo Tag::form('movimiento/buscar', 'class: buscarForm', 'autocomplete: off') ?>
			<table align="center">
				<tr>
					<td align="right">
						<label for="codigoComprabante">Comprobante</b>
					</td>
					<td>
						<?php echo Tag::select('codigoComprobante', $comprobs, 'using: codigo,nom_comprob', 'useDummy: yes') ?>
					</td>
				</tr>
				<tr>
					<td align="right">
						<label for="numero">Número</label>
					</td>
					<td>
						<?php echo Tag::numericField('numero', 'size: 3') ?>
					</td>
				</tr>
				<tr>
					<td align="right">
						<label for="fecha">Fecha</label>
					</td>
					<td>
						<?php echo Tag::dateField('fecha', 'startYear: 1995', 'class: date-field') ?>
					</td>
				</tr>
				<tr>
					<td></td>
					<td colspan="2">
						<table cellspacing="0">
							<tr>
								<td>
									<input type="submit" value="Buscar"/>
								</td>
								<td>
									<div class="formSpinner" style="display:none"></div>
								</td>
							</tr>
						</table>
					</td>
				</tr>
			</table>
		<?php echo Tag::endForm() ?>
	</div>

	<div class="resultados"></div>

</div>
