<table cellspacing="0" align='center'>
	<tr>
		<td>
		    <input id='number' readonly="yes" value="" class='mediumBox'>
		</td>
	<tr>
		<td>
	 	  	<table cellspacing="0">
				<tr>
					<td align='center'><input type='button' value='7' id='b7' class='bigButton' onclick='addToNumber(this, event)' onmousedown="big(this)"></td>
					<td align='center'><input type='button' value='8' id='b8' class='bigButton' onclick='addToNumber(this, event)' onmousedown="big(this)"></td>
					<td align='center'><input type='button' value='9' id='b9' class='bigButton' onclick='addToNumber(this, event)' onmousedown="big(this)"></td>
				</tr>
				<tr>
					<td align='center'><input type='button' value='4' id='b4' class='bigButton' onclick='addToNumber(this, event)' onmousedown="big(this)"></td>
					<td align='center'><input type='button' value='5' id='b5' class='bigButton' onclick='addToNumber(this, event)' onmousedown="big(this)"></td>
					<td align='center'><input type='button' value='6' id='b6' class='bigButton' onclick='addToNumber(this, event)' onmousedown="big(this)"></td>
				</tr>
				<tr>
					<td align='center'><input type='button' value='1' id='b1' class='bigButton' onclick='addToNumber(this, event)' onmousedown="big(this)"></td>
					<td align='center'><input type='button' value='2' id='b2' class='bigButton' onclick='addToNumber(this, event)' onmousedown="big(this)"></td>
					<td align='center'><input type='button' value='3' id='b3' class='bigButton' onclick='addToNumber(this, event)' onmousedown="big(this)"></td>
				</tr>
				<tr>
					<td align='center'><input type='button' value='NO' class='bigButtonCancel' onclick='cancelNumber()'></td>
					<td align='center'><input type='button' value='0' id='b0' class='bigButton'  onclick='addToNumber(this, event)' onmousedown="big(this)"></td>
					<td align='center'><input type='button' value='OK' class='bigButtonOK' id='okButton' disabled onclick='acceptNumber()'></td>
				</tr>
			</table>
		</td>
	</tr>
</table>