<?php

/**
 * Hotel Front-Office Solution
 *
 * LICENSE
 *
 * This source file is subject to license that is bundled
 * with this package in the file docs/LICENSE.txt.
 *
 * @package 	Back-Office
 * @copyright 	BH-TECK Inc. 2009-2010
 * @version		$Id$
 */

?>

<div class="resultados"></div>

<?php echo HfosTag::iconTitle('listado-referencias.png', 'Listado de Proveedores por Referencia') ?>

<?php echo Tag::form('listado_proveedores/generar', 'class: listadoProveedoresForm', 'autocomplete: off') ?>
<table align="center">
	<tr>
		<td valign="top">
			<table>
				<tr>
					<td align="right"><label for="nitInicial">Proveedor Inicial</label></td>
					<td><?php echo HfosTag::terceroField('nitInicial') ?></td>
				</tr>
				<tr>
					<td align="right"><label for="nitFinal">Proveedor Final</label></td>
					<td><?php echo HfosTag::terceroField('nitFinal') ?></td>
				</tr>
				<tr>
					<td align="right"><label for="itemInicial">Referencia Inicial</label></td>
					<td><?php echo HfosTag::itemField('itemInicial') ?></td>
				</tr>
				<tr>
					<td align="right"><label for="itemFinal">Referencia Final</label></td>
					<td><?php echo HfosTag::itemField('itemFinal') ?></td>
				</tr>
				<tr>
					<td align="right"><label for="fechaInicial">Fecha Inicial</label></td>
					<td><?php echo Tag::dateField('fechaInicial') ?></td>
				</tr>
				<tr>
					<td align="right"><label for="fechaFinal">Fecha Final</label></td>
					<td><?php echo Tag::dateField('fechaFinal') ?></td>
				</tr>
				<tr>
					<td align="right"><label for="tipo">Tipo</label></td>
					<td><?php echo Tag::selectStatic('tipo', array("O"=>"Por Ordenes de Compra", "E" => "Por Entradas al Almacen")) ?></td>
				</tr>
				<tr>
					<td align="right"></td>
					<td>
						<table cellspacing="0">
							<tr>
								<td>
									<input type="submit" value="Generar"/>
								</td>
								<td>
									<div class="formSpinner" style="display:none"></div>
								</td>
							</tr>
						</table>
					</td>
				</tr>
			</table>
		</td>
		<td valign="top">
			<div class="cuadro-cierre">
				<table>
					<tr>
						<td align="right"><b>Último Cierre</b></td>
						<td><?php echo $fechaCierre->getLocaleDate('long') ?></td>
					</tr>
				</table>
			</div>
		</td>
	</tr>
</table>
<?php echo HfosTag::reportTypeTag(true, false) ?>
<?php echo Tag::endForm() ?>
