<?php

/**
 * Hotel Front-Office Solution
 *
 * LICENSE
 *
 * This source file is subject to license that is bundled
 * with this package in the file docs/LICENSE.txt.
 *
 * @package 	Back-Office
 * @copyright 	BH-TECK Inc. 2009-2010
 * @version		$Id$
 */

View::getContent();

if(isset($matrizProveedores)){
	echo '<div align="center">
		<div class="addProveedorDiv">
			<table align="center" cellspacing="0" cellpadding="0" class="hyBrowseTab">
				<tr>
					<td align="right"><label for="nuevoProveedor">Proveedor</label></td>
					<td>', HfosTag::terceroField("nuevoProveedor"), '</td>
					<td><input type="button" class="addButton" value="Agregar"/></td>
				</tr>
			</table>
		</div>
	</div>

	<div align="center" id="tableProveedor">
	<table width="80%" cellspacing="0" cellpadding="0" align="center" class="hyBrowseTab zebraSt sortable">
		<tr>
			<th width="7">&nbsp;</th>
			<th width="100" class="sortcol">Documento</th>
			<th class="sortcol">Nombre Proveedor</th>
			<th>&nbsp;</th>
		</tr>
	</table><ul class="proveedorOrder">';
	$numero = 1;
	foreach($matrizProveedores as $proveedor){
		echo '<li id="proovedor_', $numero, '"><table width="80%" cellspacing="0" cellpadding="0" class="hyBrowseTab zebraSt sortable"><tr>
			<td width="7">', Tag::image('backoffice/grippy.png'), '</td>
			<td width="100">', Tag::hiddenField(array('nit[]', 'value' => $proveedor['nitId'])), ' ', $proveedor['nitId'], '</td>
			<td align="left">', $proveedor['nitNombre'], '</td>
			<td width="20">', Tag::image(array('backoffice/delete.gif', 'class' => 'delete')), '</td>
		</table></tr></li>';
		$numero++;
	}
	echo '</ul>';
}
