<?php

/**
 * Hotel Front-Office Solution
 *
 * LICENSE
 *
 * This source file is subject to license that is bundled
 * with this package in the file docs/LICENSE.txt.
 *
 * @package 	Back-Office
 * @copyright 	BH-TECK Inc. 2009-2010
 * @version		$Id$
 */

View::getContent();

echo Tag::form(array('matriz_proveedores/guardar', 'class' => 'matrizForm', 'autocomplete' => 'off'));

?>

<div class="matrizProveedores hfosContent">
	<div class="hfosToolbar">
		<table width="99%">
			<tr>
				<td align="right">
					<table align="right">
						<tr>
							<td><label for="ReferenciaId">Referencia</label></td>
							<td>
								<?php echo HfosTag::itemField("referenciaId") ?>&nbsp;
							</td>
							<td>
								<input type="button" class="saveButton" value="Guardar" style="display:none;">
							</td>
							<td align="left">
								<div class="headerSpinner" style="display:none"></div>
							</td>
						</tr>
					</table>
				</td>
			</tr>
		</table>
	</div>

	<div class="messages">
		<?php
			if(isset($message)){
				echo '<div class="notice">', $message, '</div>';
			}
		?>
	</div>

	<div class="matrizProveedoresContent" style="display:none"></div>

	<div align="right">
		<div class="chooseReferencia infoBox" align="center">
			<table align="center">
				<tr>
					<td><strong>Seleccione una Referencia</strong></td>
					<td><?php echo Tag::image('backoffice/arrow-alt-up.png') ?></td>
				</tr>
			</table>
		</div>
	</div>

</div>

<?php echo Tag::endForm() ?>
