<?php

/**
 * Hotel Front-Office Solution
 *
 * LICENSE
 *
 * This source file is subject to license that is bundled
 * with this package in the file docs/LICENSE.txt.
 *
 * @package 	Back-Office
 * @copyright 	BH-TECK Inc. 2009-2010
 * @version		$Id$
 */

View::getContent();

?>
<div class="settings hfosContent">
	<div class="hfosToolbar">
		<table width="99%">
			<tr>
				<td align="right">
					<table align="right">
						<tr>
							<td>
								<input type="submit" id="submitButton" class="saveButton" value="Guardar">
							</td>
							<td align="left">
								<div class="headerSpinner" style="display:none"></div>
							</td>
						</tr>
					</table>
				</td>
			</tr>
		</table>
	</div>

	<div class="messages">
		<?php
			if(isset($message)){
				echo '<div class="notice">', $message, '</div>';
			}
		?>
	</div>

	<div class="settingsTable">
		<?php echo Settings::getForm($settings); ?>
	</div>

</div>

