<?php

/**
 * Hotel Front-Office Solution
 *
 * LICENSE
 *
 * This source file is subject to license that is bundled
 * with this package in the file docs/LICENSE.txt.
 *
 * @package 	Back-Office
 * @copyright 	BH-TECK Inc. 2009-2010
 * @version		$Id$
 */

?>

<?php echo HfosTag::iconTitle('limited-edition.png', 'Informe de Recibos de Caja') ?>

<div class="formContent">

<table align="center" width="100%">
	<tr>
		<td valign="top" width="50%" align="center">
			<?php echo Tag::form('informe_rc/reporte', 'class: informeRcForm', 'autocomplete: off') ?>
				<table align="center">
					<!--<tr>
						<td align="right">
				        	<label for="periodo">Periodo Limite</label>
				        </td>
				        <td align="left">
				        	<?php
								//echo Tag::select('periodo',$periodos, 'using: periodo,periodo');
							?>
						</td>
					</tr>-->
					<tr>
						<td align="right">
				        	<label for="fechaIni">Fecha Estado Cuenta</label>
				        </td>
				        <td align="left">
				        	<?php
								echo Tag::dateField('fechaIni');
							?>
						</td>
					</tr>
					<tr>
						<td align="right">
				        	<label for="fechaFin">Fecha Limite Estado Cuenta</label>
				        </td>
				        <td align="left">
				        	<?php
								echo Tag::dateField('fechaFin');
							?>
						</td>
					</tr>
					<tr>
						<td align="right">
				        	<label for="sociosId">Socio</label>
				        </td>
				        <td align="left">
				        	<?php
								echo HfosTag::addHyperFormSpecialField(array(
									'type' => 'Socio',
									'name' => 'sociosId',
									'classForm' => 'informeRcForm',
									'class' => 'sociosId'
								));
							?>
						</td>
					</tr>
					<tr>
						<td align="right">
				        	<label for="periodo">Periodo</label>
				        </td>
				        <td align="left">
				        	<?php 
								echo Tag::hiddenField('periodoAct','value: '.$mes);
								echo $mes;
							?>
						</td>
					</tr>
					<tr>
						<td align="right">
				        	<label for="reportType">Formato</label>
				        </td>	
						<td align="left"><?php echo Tag::selectStatic('reportType', array(
							'html' => 'HTML',
							'excel' => 'EXCEL',
							'pdf' => 'PDF',
							//'text' => 'TEXTO PLANO',
						)) ?></td>
					</tr>
				</table>
			<?php echo Tag::endForm() ?>

			<div class="resultados"></div>
		</td>
	</tr>
</table>
</div>
