<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
 <head>
  <meta http-equiv='Content-type' content='text/html; charset=UTF-8' />
  <title>Hotel Front-Office Solution</title>
  <!-- Cargando estilos CSS -->
  <?php Tag::stylesheetLink('style') ?>
  <?php echo Tag::stylesheetLinkTags() ?>
  <!-- Cargando frameworks Javascript -->
  <?php echo Tag::javascriptLibrary('framework/scriptaculous/protoculous') ?>
  <?php echo Tag::javascriptBase() ?>
 </head>
 <body>
  <?php View::getContent(); ?>
 </body>
</html>
