<?php

/**
 * Hotel Front-Office Solution
 *
 * LICENSE
 *
 * This source file is subject to license that is bundled
 * with this package in the file docs/LICENSE.txt.
 *
 * @package 	Back-Office
 * @copyright 	BH-TECK Inc. 2009-2010
 * @version		$Id$
 */

$config = CoreConfig::readAppConfig();
if($config->application->mode=='development'){
	Tag::stylesheetLink('pos2/cashintro');
} else {
	Tag::stylesheetLink('pos2/production/cashouttro', false, 'v='.ControllerBase::APP_VERSION);
	echo Tag::javascriptInclude('pos2/production/cashouttro', true, 'v='.ControllerBase::APP_VERSION);
}

View::getContent();

?>

<div align="center">
	<div class="shadow-div">
		<table cellspacing="0" width="100%">
			<tr>
				<td class='titulo' align='center'>
					Cajas del Sistema
				</td>
			</tr>
			<tr>
				<td id="cashMain">
					<table>
						<tr>
							<td>
								<?php echo Tag::image("pos2/caja.png", "width: 72") ?>
							</td>
							<td>
								<h1>Cajas del Sistema</h1>
							</td>
						</tr>
					</table>
		<?php
			$i = 1;
			echo "<table align='center'><tr>";
			foreach ($CashTray->find() as $cash) {
				$estado = $cash->estado == "N" ? "CERRADA" : "ABIERTA";
				echo "<td valign='top'>";
				echo "<table cellspacing='0' cellpadding='2' class='cash-box'>";
				echo "<tr><td colspan='2' class='cash-box-header'>Caja {$cash->descripcion}</span><span class='cash-status'>[{$estado}]</span></td></tr>";
		  		echo "<tr><td align='center'>
				  <div id='det{$cash->id}'><table><td valign='top'>";
		  		if($cash->estado=='A'){
					$usuario = $UsuariosPos->findFirst($cash->usuarios_id);
					if(!$usuario){
						$usuario = new stdClass();
						$usuario->nombre = "SIN DEFINIR";
					}
			  	  	echo Tag::image('pos2/ocupada.gif', 'width: 96');
					echo "</td><td align='center'>
						<table>
							<tr><td align='right'><b>Último Cajero</b></td><td>", $usuario->nombre, "</td></tr>
							<tr><td align='right'><b>Fecha</b></td><td>", $cash->fecha, "</td></tr>
							<tr><td align='right'><b>Hora</b></td><td>", $cash->hora_abierta, "</td></tr>
							<tr><td align='right'><b>Estado</b></td><td>ABIERTO</td></tr>
						</table>";
					echo "<br>";
					echo Tag::buttonToAction('Cerrar Caja', "cashouttro/close/".$cash->id, 'flowButton');
					echo "<br>";
				} else {
					$usuario = $UsuariosPos->findFirst($cash->usuarios_id);
					if (!$usuario) {
						$usuario = new stdClass();
						$usuario->nombre = "SIN DEFINIR";
					}
					echo Tag::image('pos2/disponible.gif', 'width: 96', 'height: 96');
					echo "</td><td align='center'>
					<table>
						<tr><td align='right'><b>Último Cajero</b></td><td>{$usuario->nombre}</td></tr>
						<tr><td align='right'><b>Fecha</b></td><td>{$cash->fecha}</td></tr>
						<tr><td align='right'><b>Hora</b></td><td>{$cash->hora_cerrada}</td></tr>
						<tr><td align='right'><b>Estado</b></td><td>CERRADA</td></tr>
					</table><br>";
					$pay = isset($_REQUEST['pay']) ? $_REQUEST['pay'] : "";
					echo Tag::buttonToAction('Abrir Caja', "cashouttro/open/".$cash->id."?pay=".$pay, 'flowButton');
					echo "&nbsp;<br>";
				}
				echo "</td></table></div></td></tr>";
				echo "</table></td>";
				if (!($i%2)) {
					echo "</tr><tr>";
				}
				$i++;
			}
			echo "</table>";

		?>

		<div align="right">
			<table>
				<tr>
					<td>
						<button class='commandButton' onclick='new Utils.redirectToAction("tables")'>
							<?php echo Tag::image("pos2/arrow_left-p.png", "width: 23") ?><br>
							<b>Ir a Mesas</b>
						</button>
					</td>
				<?php
				 	if(isset($_REQUEST['pay'])){
				 		if($_REQUEST['pay']){
				 			echo '<td>
					 			<button class="commandButton" onclick="new Utils.redirectToAction(\'pay/index/', $_REQUEST['pay'], '\')">
									', Tag::image("pos2/dollar-p.png", "width: 23"), '<br>
									<b>Volver a Pagar</b>
								</button>
							</td>';
				 		}
				 	}
				?>
					<td>
						<button class='commandButton' onclick='new Utils.redirectToAction("appmenu")'>
							<?php echo Tag::image("pos2/home-p.png", "width: 23") ?><br>
							<b>Salir</b>
						</button>
					</td>
				</tr>
			</table>
		</div>

		</td>
		</table>
	</div>
</div>
