<?php

/**
 * Hotel Front-Office Solution
 *
 * LICENSE
 *
 * This source file is subject to license that is bundled
 * with this package in the file docs/LICENSE.txt.
 *
 * @package 	Back-Office
 * @copyright 	BH-TECK Inc. 2009-2010
 * @version		$Id$
 */

View::getContent();

?>
<div class="formatosCheques hfosContent">
	<div class="hfosToolbar">
		<table width="99%">
			<tr>
				<td align="right">
					<table align="right">
						<tr>
							<td><label for="usuariosId">Chequera</label></td>
							<td>
								<?php echo Tag::selectStatic('chequeraId', $chequeras, 'useDummy: yes') ?>&nbsp;
							</td>
							<td>
								<input type="submit" id="submitButton" class="saveButton" value="Guardar" style="display:none;">								
							</td>
							<td>
								<input type="button" id="copiarButton" class="copyButton" value="Copiar Formato" style="display:nonea;">
							</td>
							<td align="left">
								<div class="headerSpinner" style="display:none"></div>
							</td>
						</tr>
					</table>
				</td>
			</tr>
		</table>
	</div>

	<div class="messages">
		<?php
			if(isset($message)){
				echo '<div class="notice">', $message, '</div>';
			}
		?>
	</div>

	<div class="chequeraFormato"></div>

	<div align="right">
		<div class="chooseChequera infoBox" align="center">
			<table align="center">
				<tr>
					<td><strong>Seleccione una Chequera</strong></td>
					<td><?php echo Tag::image('backoffice/arrow-alt-up.png') ?></td>
				</tr>
			</table>
		</div>
	</div>

</div>
