<?php

/**
 * Hotel Front-Office Solution
 *
 * LICENSE
 *
 * This source file is subject to license that is bundled
 * with this package in the file docs/LICENSE.txt.
 *
 * @package 	Back-Office
 * @copyright 	BH-TECK Inc. 2009-2010
 * @version		$Id$
 */

View::getContent();

?>
<div align="center">
	<div class="formExternal">
		<div class="externalHeader">
			<table width="95%" align="center" cellpadding="0" cellspacing="0">
				<tr>
					<td><h1>Copiar Formato<h1></td>
					<td align="right"><div class="window-close"></div></td>
				</tr>
			</table>
		</div>
		<div class="messages"></div>
		<div class="formatoItems">

			<p>
				<?php echo Tag::form('formato_cheque/copiar', 'onbeforesubmit: return false', 'autocomplete: off') ?>
		
				<table cellpadding="0" cellspacing="0" align="center">
					<tbody>
						<tr>
							<td><label for="chequeraOrigenId">Formato Origen</label></td>
							<td>
								<?php echo Tag::selectStatic('chequeraOrigenId', $chequeras, 'useDummy: yes') ?>&nbsp;
							</td>
						</tr>
						<tr>
							<td></td>
							<td></td>
						</tr>
						<tr>
							<td><label for="chequeraDestinoId">Formato Destino</label></td>
							<td>
								<?php echo Tag::selectStatic('chequeraDestinoId', $chequeras, 'useDummy: yes') ?>&nbsp;
							</td>
						</tr>
						<tr>
							<td colspan="2" align="right">
								<?php echo Tag::submitButton('Copiar') ?>
							</td>
						</tr>
					</tbody>
				</table>
				<?php echo Tag::endForm() ?>
			</p>		
	</div>
</div>		