<html>
	<head>
		<title>Recibo de Caja #12657</title>
		<?php echo Tag::stylesheetLink('hfos/recibo'); ?>
	</head>
	<body>
		<div align="center">
			<div class="page">

				<table width="95%">
					<tr>
						<td>
							<div class="logo">
								<img src="/h/img/tpc/logo.png">
							</div>
						</td>
						<td>
							<div class="datos" align="right">
								Proyecto e Inversiones TPC S.A<br/>
								NIT: 900.141.821-1
							</div>
						</td>
					</tr>
				</table>

				<table width="95%">
					<tr>
						<td>
							<div align="left" class="datos-c">
								<b>Datos del Contrato</b><br/>
								DARLYNA MARTINEZ PANESSO<br>
								Documento: 49556777<br/>
								Contrato: RESERVA-761<br/>
								Código: 3842<br/>
							</div>
						</td>
						<td>
							<div align="right" class="datos-r">
								<div class="title">RECIBO DE CAJA</div>
								<table>
									<tr>
										<td align="right">Número</td>
										<td align="right">12657</td>
									</tr>
									<tr>
										<td align="right">Ciudad</td>
										<td align="right">Bogotá</td>
									</tr>
									<tr>
										<td align="right">Fecha</td>
										<td align="right">2011-06-17</td>
									</tr>
								</table>
							</div>
						</td>
					</tr>
				</table>

				<table width="95%" cellpadding="0" cellspacing="0" class="spacer">
					<tr>
						<td width="20%" bgcolor="#007634"></td>
						<td width="30%" bgcolor="#5BB041"></td>
						<td width="40%" bgcolor="#9BD54D"></td>
					</tr>
				</table>

				<table width="95%">
					<tr>
						<td align="left">
							<b>Activación</b><br/>
							<div align="right">0,00</div>
						</td>
						<td width="25"></td>
						<td align="left">
							<b>Derecho de Afiliación</b><br/>
							<div align="right">0,00</div>
						</td>
						<td width="25"></td>
						<td align="left">
							<b>Interés por mora</b><br/>
							<div align="right">0,00</div>
						</td>
						<td width="25"></td>
						<td align="left">
							<b>Intereses Corrientes</b><br/>
							<div align="right">0,00</div>
						</td>
					</tr>
					<tr>
						<td style="height:10px"></td>
					</tr>
					<tr>
						<td align="left">
							<b>Capital</b><br/>
							<div align="right">0,00</div>
						</td>
						<td width="25"></td>
						<td align="left">
							<b>Valor Cuota Inicial</b><br/>
							<div align="right">0,00</div>
						</td>
						<td width="25"></td>
						<td align="left">
							<b>Valor Cuota Financiación</b><br/>
							<div align="right">0,00</div>
						</td>
						<td width="25"></td>
						<td align="left">
							<b>Otros</b><br/>
							<div align="right">0,00</div>
						</td>
					</tr>
				</table>

				<table width="95%" cellpadding="0" cellspacing="0" class="spacer-small">
					<tr>
						<td width="20%" bgcolor="#007634"></td>
						<td width="30%" bgcolor="#5BB041"></td>
						<td width="40%" bgcolor="#9BD54D"></td>
					</tr>
				</table>

				<table width="80%">
					<tr>
						<th>Forma de Pago</th>
						<th>Cuenta</th>
						<th>Valor</th>
					</tr>
					<tr>
						<td>EFECTIVO</td>
						<td>DAVIVIENDA 00506999866-3 </td>
						<td align="right">150.000,00</td>
					</tr>
					<tr>
						<td>CHEQUE</td>
						<td>DAVIVIENDA 00506999866-3 </td>
						<td align="right">50.000,00</td>
					</tr>
					<tr>
						<td colspan="2" align="right"><b>TOTAL RECIBO</b></td>
						<td align="right" class="total"><b>200.000,00</b></td>
					</tr>
				</table>

				<br/>
				<div align="center">
				 	<div class="concepto" align="left">
						<b>Concepto:</b> ABONO A RESERVA-761
					</div>
				</div>

				<br/>
				<br/>
				<table width="90%" class="firmas">
					<tr>
						<td>
							<b>Elaborado</b><br/><br/>
							<div align="center">______________________</div>
						</td>
						<td>
							<b>Revisado</b><br/><br/>
							<div align="center">______________________</div>
						</td>
						<td>
							<b>Firma y Sello de quien Recibe</b><br/><br/>
							<div align="center">______________________</div>
						</td>
					</tr>
				</table>

				<br/>
			</div>
		</div>
	</body>
</html>