<?php

/**
 * Hotel Front-Office Solution
 *
 * LICENSE
 *
 * This source file is subject to license that is bundled
 * with this package in the file docs/LICENSE.txt.
 *
 * @package 	Back-Office
 * @copyright 	BH-TECK Inc. 2009-2010
 * @version		$Id$
 */

View::getContent();

$Datos->findFirst();

?>
<html>
<head>
<style type='text/css'>
	td, span, div, th, pre {
		font-family: 'Lucida Console', 'Courier New';
		font-size: 12px;
	}
	body {
		margin: 0px;
	}
	table {
		wdith: 270px;
	}
</style>
</head>
<body>
<div align="center">
<?php

echo $Datos->getNombreCadena(), '<br/>';
echo $Datos->getDocumento()." No. : ".$Datos->getNit(), '<br/>';
echo i18n::strtoupper($Datos->getNombreHotel()), '<br/>';
echo "CUADRE DE CAJA TODOS<br/>";
if($fecha_inicial==$fecha_final){
	echo "Fecha: {$fecha_inicial}<br/>" ;
} else {
	echo "Fecha: {$fecha_inicial} - {$fecha_final}<br/>" ;
}
echo "Cajero: ".i18n::strtoupper(Session::getData("usuarios_nombre")), '<br/>';

if($salon_id!='@'){
	if($Salon->find($salon_id)){
		echo "Ambiente: {$Salon->nombre} <br/>";
	}
}
echo "Fecha Impresión: ".Date::now()."<br/>";

?>
</div>
<table width='270' cellspacing="1">
<?php

$total = 0;
$totalIva = 0;
$tipo_venta = "";
$totalPropina = 0;
$totalproponanc = 0;
$cajeros_total = array();
$usuarios = array();
$totalTipoVenta = 0;
$totalAlimentos = 0;
$totalBebidas = 0;
$totalivanc = 0;
$totalnotafull = 0;
$formaspagonc = array();
$totalfinalnc = 0;
if($salon_id!='@'){
	$conditions = "fecha >= '$fecha_inicial' AND fecha <= '$fecha_final' and estado = 'A' AND salon_id = '{$salon_id}'";
} else {
	$conditions = "fecha >= '$fecha_inicial' AND fecha <= '$fecha_final' and estado = 'A'";
}
foreach($Factura->find($conditions, "order: tipo_venta, usuarios_id, consecutivo_facturacion") as $factura){
	if(!isset($usuarios[$factura->usuarios_id])){
		$usuario = $UsuariosPos->findFirst($factura->usuarios_id);
		if($usuario!=false){
			$nombres =	explode(' ', $usuario->nombre);
			$usuarios[$factura->usuarios_id] = i18n::substr(i18n::strtoupper($nombres[0]), 0, 7);
		} else {
			$usuarios[$factura->usuarios_id] = 'USUARIO BORRADO';
		}
	}
	$nombre = $usuarios[$factura->usuarios_id];
	if($tipo_venta!=$factura->tipo_venta){
		if($tipo_venta!=''){
			if($tipo_venta == 'F'){
				echo "<tr><td colspan='3'>---------------------------------------</td></tr>";
				echo '<tr><td align="right" colspan="3">TOTAL</td><td align="right">', Currency::number($totalTipoVenta, 0), '</td></tr>';
				echo '<tr><td align="right" colspan="3">NOTA CREDITO</td><td align="right">', Currency::number($totalnotafull, 0), '</td></tr>';
				echo '<tr><td align="right" colspan="3">TOTAL NETO</td><td align="right">', Currency::number($totalTipoVenta-$totalnotafull, 0), '</td></tr>';
			}else{
				echo "<tr><td colspan='4'>---------------------------------------</td></tr>";
				echo '<tr><td align="right" colspan="3">TOTAL</td><td align="right">', Currency::number($totalTipoVenta, 0), '</td></tr>';
			}
			$totalnotafull = 0;
			$totalTipoVenta = 0;
		}
		$tipoVenta = $TipoVenta->findFirst("id='$factura->tipo_venta'");
		if($tipoVenta){
			echo "<tr><td colspan='4'><br/>{$tipoVenta->detalle}:</td></tr>";
		} else {
			echo "<tr><td colspan='4'>DESCONOCIDO:</td></tr>";
		}
		echo "<tr>
			<td align='center'>Número</td>
			<td align='center'>Descripción</td>
			<td align='center'>Cajero</td>
			<td align='center'>Valor</td>
			</tr>";
		$tipo_venta = $factura->tipo_venta;
	}
	$conditions = "account_master_id='{$factura->account_master_id}' AND prefijo='$factura->prefijo_facturacion' AND numero='$factura->consecutivo_facturacion'";
	$cuenta = $AccountCuentas->findFirst($conditions);
	if($factura->tipo_venta=='P'||$factura->tipo_venta=='H'){
		if($cuenta){
			$habitacion = $HabitacionHistorico->find($cuenta->habitacion_id);
			if($habitacion&&$habitacion->numhab){
				$descripcion = "(".$habitacion->numhab.")";
			} else {
				$descripcion = "";
			}
		} else {
			$descripcion = "";
		}
	} else {
		$descripcion = "";
	}
	if($cuenta){
		if($cuenta->propina>0){
			$propina = "<br>(".$cuenta->propina.")";
			$totalPropina+=$cuenta->propina;
		} else {
			$propina = "";
		}
	} else {
		$propina = "";
	}
	$nombreFactura = i18n::substr($factura->nombre, 0, 20);
	echo "<tr>";
	echo "<td align='center'>{$factura->prefijo_facturacion} {$factura->consecutivo_facturacion}</td>";
	echo "<td align='left'>{$nombreFactura} {$descripcion}</td>";
	echo "<td align='center'>{$nombre} {$propina}</td>";
	echo "<td align='right'>", Currency::number($factura->total), "</td>";
	echo "</tr>";
	if($factura->tipo_venta=='F'){

		# NOTA CREDITO FACTURA
		$totalncfactura = 0;
		$totalpropinanc = 0;

		foreach($NotaCredito->find("factura_id = '$factura->id' AND fecha = '$factura->fecha'") as $key => $nota){
			echo "<tr>";
			echo "<td align='center'>&nbsp;</td>";
			echo "<td align='left' colspan='2'>{$nota->prefijo_documento}-{$nota->consecutivo_documento}&nbsp;</td>";
			echo "<td align='right'>-",Currency::number($nota->total),"</td>";
			echo "</tr>";
			$totalncfactura = $nota->total;
			$totalivanc += $nota->total_iva;
			$totalnotafull += $nota->total;
			$totalpropinanc = $nota->propina;

			# FORMAS PAGO NOTA CREDITO
			foreach($nota->getNotaCreditoPago() as $index => $forpag){
				$detalle = $forpag->getFormasPago()->detalle;
				if(!isset($formaspagonc[$detalle])){
					$formaspagonc[$detalle] = 0;
				}
				$formaspagonc[$detalle] += $forpag->pago;
			}

		}

		if($totalncfactura > 0){
			echo "<tr>";
			echo "<td align='center'>&nbsp;</td>";
			echo "<td align='left'>&nbsp;</td>";
			echo "<td align='left'>&nbsp;</td>";
			echo "<td align='right'>---------</td>";
			echo "</tr>";
			echo "<tr>";
			echo "<td align='center'>&nbsp;</td>";
			echo "<td align='left'>&nbsp;</td>";
			echo "<td align='left'>&nbsp;</td>";
			echo "<td align='right'>",Currency::number($factura->total-$totalncfactura),"</td>";
			echo "</tr>";
		}


		if(!isset($cajeros_total[$UsuariosPos->id])){
			$cajeros_total[$UsuariosPos->id] = array();
			$cajeros_total[$UsuariosPos->id]['nombre'] = $nombre;
			$cajeros_total[$UsuariosPos->id]['valor'] = 0;
			$cajeros_total[$UsuariosPos->id]['valornc'] = 0;
		}

		$cajeros_total[$UsuariosPos->id]['valor'] += $factura->total;
		$cajeros_total[$UsuariosPos->id]['valornc'] += $totalncfactura;


		$conditions = "prefijo_facturacion='{$factura->prefijo_facturacion}' AND consecutivo_facturacion='{$factura->consecutivo_facturacion}' AND tipo='{$factura->tipo}'";
		foreach($PagosFactura->find($conditions) as $pagoFactura){
			$formaPago = $pagoFactura->getFormasPago();
			if($formaPago!=false){
				$detalle = $formaPago->detalle;
			} else {
				$detalle = 'MONEDA NACIONAL';
			}
			echo '<tr><td></td><td colspan="3"> + ', $detalle, '</td></tr>';
			if(!isset($formasPago[$detalle])){
				$formasPago[$detalle] = 0;
			}
			$formasPago[$detalle]+=$pagoFactura->pago;
		}
	}
	$total+=$factura->total;
	$totalfinalnc+=$totalncfactura;
	$totalIva+=$factura->total_iva;
	$totalTipoVenta+=$factura->total;
	$totalAlimentos+=$factura->total_alimentos;
	$totalBebidas+=$factura->total_bebidas;
}
if($tipo_venta!=''){
	echo "<tr><td colspan='4'>---------------------------------------</td></tr>";
	echo '<tr><td align="right" colspan="3">TOTAL</td><td align="right">', Currency::number($totalTipoVenta, 0), '</td></tr>';
}

?>
</table>
<pre>
----------------------------------------
</pre>
<div style='pading: 20px; width:270px' align='right'>
<?php

foreach($cajeros_total as $cajero){
	if($cajero['valornc'] > 0){
		echo 'VALOR FACTURADO '.$cajero['nombre'].': ', Currency::number($cajero['valor']), '<br/>';
		echo 'NOTAS CREDITO '.$cajero['nombre'].': ', Currency::number($cajero['valornc']), '<br/>';
		$cajero['valor'] = $cajero['valor'] - $cajero['valornc'];
	}
	echo 'TOTAL FACTURAS '.$cajero['nombre'].': ', Currency::number($cajero['valor']), '<br/>';
	
}

?>
<br/>
TOTAL PROPINA : <?php echo Currency::number($totalPropina-$totalpropinanc) ?><br/>
TOTAL IVA : <?php echo Currency::number($totalIva-$totalivanc) ?><br/>
TOTAL TODO: <?php echo Currency::number($total-$totalfinalnc) ?><br/>
<br/>
<br/>
<?php

if(isset($formasPago)){
	foreach($formasPago as $formaPago => $valor){
		echo $formaPago.': ', Currency::number($valor), '<br/>';
		if(isset($formaspagonc[$formaPago])){
			$valor = $valor - $formaspagonc[$formaPago];
			echo 'NC-'.$formaPago.': -', Currency::number($formaspagonc[$formaPago]), '<br/>';
			echo 'NETO-'.$formaPago.': ', Currency::number($valor), '<br/>';
			unset($formaspagonc[$formaPago]);
		}
	}

	foreach($formaspagonc as $detalle => $valor){
		echo 'NOTA CREDITO-'.$detalle.': ', Currency::number($valor), '<br/>';
	}
}

?>

</div>
<pre>
----------------------------------------
FACTURAS/ORDENES ANULADAS</pre>
<table width='260'>
<?php

$tipo_venta = "";
if($salon_id!='@'){
	$conditions = "fecha >= '$fecha_inicial' AND fecha <= '$fecha_final' and estado = 'N' AND salon_id = '{$salon_id}'";
} else {
	$conditions = "fecha >= '$fecha_inicial' AND fecha <= '$fecha_final' and estado = 'N'";
}
foreach($Factura->find($conditions, "order: tipo_venta, usuarios_id, consecutivo_facturacion") as $factura){
	if($tipo_venta!=$factura->tipo_venta){
		if(!isset($usuarios[$factura->usuarios_id])){
			$usuario = $UsuariosPos->find($factura->usuarios_id);
			if($usuario==false){
				$nombres =	'NO EXISTE USUARIO';
			} else {
				$nombres =	explode(' ', $usuario->nombre);
			}
			$usuarios[$factura->usuarios_id] = i18n::strtoupper($nombres[0]);
		}
		$nombre = $usuarios[$factura->usuarios_id];
		$tipoVenta = $TipoVenta->findFirst("id='$factura->tipo_venta'");
		if($tipoVenta){
			echo "<tr><td colspan='4'><br/>{$tipoVenta->detalle}:</td></tr>";
		} else {
			echo "<tr><td colspan='4'>DESCONOCIDO:</td></tr>";
		}
		echo "<tr>
		<td align='center'>Número</td>
		<td align='center'>Descripción</td>
		<td align='center'>Nombre</td>
		<td align='center'>Valor</td>
		</tr>";
		$tipo_venta = $factura->tipo_venta;
	}
	$conditions = "account_master_id = '{$factura->account_master_id}' AND numero='$factura->consecutivo_facturacion'";
	$cuenta = $AccountCuentas->findFirst($conditions);
	if($factura->tipo_venta=='P'||$factura->tipo_venta=='H'){
		if($cuenta){
			$habitacion = $HabitacionHistorico->find($cuenta->habitacion_id);
			if($habitacion&&$habitacion->numhab){
				$descripcion = "(".$habitacion->numhab.")";
			} else {
				$descripcion = "";
			}
		} else {
			$descripcion = "";
		}
	} else {
		$descripcion = "";
	}
	if($cuenta){
		if($cuenta->propina>0){
			$propina = "<br>(".$cuenta->propina.")";
		} else {
			$propina = "";
		}
	} else {
		$propina = "";
	}
	echo "<tr>";
	echo "<td align='center'>{$factura->prefijo_facturacion}-{$factura->consecutivo_facturacion}</td>";
	echo "<td align='left'>{$factura->nombre} {$descripcion}</td>";
	echo "<td align='center'>{$nombre} {$propina}</td>";
	echo "<td align='right'>", Currency::number($factura->total), "</td>";
	echo "</tr>";
}

?>
</table>
<div align="center">
<?php
if(!$Factura->getCount()){
	echo "NO HAY FACTURAS/ORDENES ANULADOS<br/>";
}
?>
</div>
<div align="left">
----------------------------------------
</div>
</body>
</html>