<?php

/**
 * Hotel Front-Office Solution
 *
 * LICENSE
 *
 * This source file is subject to license that is bundled
 * with this package in the file docs/LICENSE.txt.
 *
 * @package 	Back-Office
 * @copyright 	BH-TECK Inc. 2009-2010
 * @version		$Id$
 */

?>
<html>
<head>
<meta http-equiv='Content-type' content='text/html; charset=UTF-8' />
<style type='text/css'>

h3 {
	margin: 0px;
	margin-top: 10px;
	margin-bottom: 2px;
	font-size: 13px;
	font-weight: bold;
}

td, th {
	font-size: 11px;
	border-left: 1px solid #969696;
	border-bottom: 1px solid #969696;
	font-family: Verdana;
	padding-left: 5px;
	padding-right: 5px;
}

th {
	background: #eaeaea;
	font-family: Verdana
}

table tr:nth-child(even) {
	background: #fafafa;
}

table tr:nth-child(odd) {
	background: #ffffff;
}

</style>
</head>
<body>

<div style='font-size:12px;font-family:Verdana'>
<?php

$Datos->findFirst();
echo "<b>", $Datos->getNombreCadena(), "</b><br>\n";
echo "<b>", $Datos->getDocumento(), " No. : ", $Datos->getNit(), "</b><br>\n";
echo i18n::strtoupper($Datos->getNombreHotel())."<br>\n";
echo "CUADRE CAJA CONSOLIDADO TODOS<br>";
if($fecha_inicial==$fecha_final){
	echo "Fecha: {$fecha_inicial}"."<br>";
} else {
	echo "Fecha: {$fecha_inicial} - {$fecha_final}<br>\n";
}

if($salon_id!='@'){
	if($Salon->findFirst($salon_id)){
		echo "Ambiente: {$Salon->nombre}<br>";
	}
} else {
	echo "TODOS LOS AMBIENTES<br>";
}
echo "Fecha Impresión: ".Date::now()."<br/><br/>";

$conditions = "fecha >= '$fecha_inicial' AND fecha <= '$fecha_final' AND estado = 'A' AND tipo_venta NOT IN ('U', 'P', 'C')";
if($salon_id!='@'){
	$conditions .= " AND salon_id = '{$salon_id}'";
}

$movimiento = array();
$movimientonc = [];
$tiposFormas = array();
$tiposFormasnc = [];
$facturas = $Factura->find(array($conditions, 'columns' => 'id, fecha, prefijo_facturacion,consecutivo_facturacion,tipo,usuarios_id,salon_id,total'));
$pagosnotascredito = [];
foreach($facturas as $factura){
	if($factura->tipo=='F'){

		foreach($factura->getPagosFactura() as $pagoFactura){
			if(!isset($movimiento[$factura->salon_id][$factura->usuarios_id][$pagoFactura->formas_pago_id])){
				$movimiento[$factura->salon_id][$factura->usuarios_id][$pagoFactura->formas_pago_id] = $pagoFactura->pago;
				$movimiento[$factura->salon_id][$factura->usuarios_id]['NCNETO'.$pagoFactura->formas_pago_id] = $pagoFactura->pago;
			} else {
				$movimiento[$factura->salon_id][$factura->usuarios_id][$pagoFactura->formas_pago_id] += $pagoFactura->pago;
				$movimiento[$factura->salon_id][$factura->usuarios_id]['NCNETO'.$pagoFactura->formas_pago_id] += $pagoFactura->pago;
			}
			$tiposFormas[$pagoFactura->formas_pago_id] = true;
		}

		foreach($NotaCredito->find("factura_id = '$factura->id' AND fecha = '$factura->fecha'") as $key => $nota){

			# FORMAS PAGO NOTA CREDITO
			foreach($nota->getNotaCreditoPago() as $index => $pagoFactura){
				if(!isset($movimiento[$factura->salon_id][$factura->usuarios_id]['NC'.$pagoFactura->formas_pago_id])){
					$movimiento[$factura->salon_id][$factura->usuarios_id]['NC'.$pagoFactura->formas_pago_id] = -$pagoFactura->pago;
					$movimiento[$factura->salon_id][$factura->usuarios_id]['NCNETO'.$pagoFactura->formas_pago_id] -= $pagoFactura->pago;
				} else {
					$movimiento[$factura->salon_id][$factura->usuarios_id]['NC'.$pagoFactura->formas_pago_id] -= $pagoFactura->pago;
					$movimiento[$factura->salon_id][$factura->usuarios_id]['NCNETO'.$pagoFactura->formas_pago_id] -= $pagoFactura->pago;
				}
				$tiposFormasnc[$pagoFactura->formas_pago_id] = true;
			}
		}

	} else {
		if(!isset($movimiento[$factura->salon_id][$factura->usuarios_id][-1])){
			$movimiento[$factura->salon_id][$factura->usuarios_id][-1] = $factura->total;
		} else {
			$movimiento[$factura->salon_id][$factura->usuarios_id][-1] += $factura->total;
		}
		$tiposFormas[-1] = true;
	}
}

$formaspagofinal = [];
foreach ($tiposFormas as $formas_pago_id => $value) {
	if($formas_pago_id != -1){
		$formaPago = $FormasPago->findFirst($formas_pago_id);
		$descripcion = '';
		if($formaPago==false){
			$descripcion = 'NO EXISTE';
		} else {
			$descripcion = $formaPago->detalle;
		}

		$formaspagofinal[] = [
			'formas_pago_id' => $formas_pago_id,
			'detalle' => $descripcion
		];

		if(isset($tiposFormasnc[$formas_pago_id] )){
			$formaspagofinal[] = [
				'formas_pago_id' => 'NC'.$formas_pago_id,
				'detalle' => 'NC '.$descripcion
			];

			$formaspagofinal[] = [
				'formas_pago_id' => 'NCNETO'.$formas_pago_id,
				'detalle' => 'NETO '.$descripcion
			];
		}
	}else{
		$formaspagofinal[] = [
			'formas_pago_id' => $formas_pago_id,
			'detalle' => 'HABITACIÓN/FOLIO'
		];

	}
}

#echo json_encode($formaspagofinal);exit;

echo '<table cellspacing="0" cellpadding="0">';

$usuarios = array();
$formasPago = array();
$tiposFormas = array_keys($tiposFormas);
$totalesFormasTodos = array();
$formaspagoncexist = [];
foreach($movimiento as $salonId => $movimientoSalon){

	$numberRows = count($formaspagofinal)+2;

	echo '<td style="height: 30px;border-left:none;" colspan="'.$numberRows.'" valign="bottom">';
	$salon = $Salon->findFirst($salonId);
	if($salon==false){
		echo '<b>AMBIENTE BORRADO</b><br/>';
	} else {
		echo '<b>'.$salon->nombre.'</b><br/>';
	}
	echo '</td>';

	$totalesFormas = array();
	echo '<tr><th>&nbsp;</th>';
	foreach($formaspagofinal as $formapago){
		if($formapago['formas_pago_id']!=-1){
			echo '<th>', $formapago['detalle'], '</th>';
		} else {
			echo '<th>', $formapago['detalle'], '</th>';
		}

		if(!isset($totalesFormasTodos[$formapago['formas_pago_id']])){
			$totalesFormasTodos[$formapago['formas_pago_id']] = 0;
		}
				
		$totalesFormas[$formapago['formas_pago_id']] = 0;
	}
	echo '<th style="border-right: 1px solid #969696;">TOTAL</th>';
	echo '</tr>';
	foreach($movimientoSalon as $usuarioId => $movimientoUsuario){

		if(!isset($usuarios[$usuarioId])){
			$usuario = $UsuariosPos->findFirst($usuarioId);
			if($usuario!=false){
				$usuarios[$usuarioId] = $usuario->nombre;
			} else {
				$usuarios[$usuarioId] = 'USUARIO BORRADO';
			}
		}

		$totalCajero = 0;
		$nombre = $usuarios[$usuarioId];
		echo '<tr><td>', $nombre, '</td>';
		foreach($formaspagofinal as $pago){
			if(isset($movimientoUsuario[$pago['formas_pago_id']])){

				echo '<td align="right">', Currency::money($movimientoUsuario[$pago['formas_pago_id']]), '</td>';
				if(strpos($pago['formas_pago_id'],'NETO') === false){
					$totalCajero+=$movimientoUsuario[$pago['formas_pago_id']];
				}
				$totalesFormas[$pago['formas_pago_id']] += $movimientoUsuario[$pago['formas_pago_id']];
				$totalesFormasTodos[$pago['formas_pago_id']] += $movimientoUsuario[$pago['formas_pago_id']];

			} else {
				echo '<td align="right">0.00</td>';
			}
		}
		echo '<td align="right" style="border-right: 1px solid #969696;">', Currency::money($totalCajero), '</td>';
		echo '</tr>';
	}

	$totalAmbiente = 0;
	echo '<tr><td align="right"><b>TOTAL</b></td>';
	foreach($formaspagofinal as $formaPago){
		echo '<td align="right">', Currency::money($totalesFormas[$formaPago['formas_pago_id']]), '</td>';
		if(strpos($formaPago['formas_pago_id'],'NETO') === false){
			$totalAmbiente+=$totalesFormas[$formaPago['formas_pago_id']];
		}
	}
	echo '<td align="right" style="border-right: 1px solid #969696;">', Currency::money($totalAmbiente), '</td>';
	echo '</tr>';

}

if(isset($numberRows)){
	echo '<tr><td style="height: 30px;border-left:none;border-bottom: 1px solid #969696;" colspan="'.$numberRows.'" valign="bottom"></td></tr>';

	$totalGeneral = 0;
	echo '<tr><td align="right" style="border-top: 1px solid #969696;"><b>TOTAL TODOS</b></td>';
	foreach($formaspagofinal as $formaPago){
		echo '<td align="right" style="border-top: 1px solid #969696;">', Currency::money($totalesFormasTodos[$formaPago['formas_pago_id']]), '</td>';
		if(strpos($formaPago['formas_pago_id'],'NETO') === false){
			$totalGeneral+=$totalesFormasTodos[$formaPago['formas_pago_id']];
		}
	}
	echo '<td align="right" style="border-right: 1px solid #969696;border-top: 1px solid #969696;">', Currency::money($totalGeneral), '</td>';
	echo '</tr>';
}

echo '</table><br/><br/>';

?>
<br/>

</body>
</html>