<?php

/**
 * Hotel Front-Office Solution
 *
 * LICENSE
 *
 * This source file is subject to license that is bundled
 * with this package in the file docs/LICENSE.txt.
 *
 * @package 	Back-Office
 * @copyright 	BH-TECK Inc. 2009-2010
 * @version		$Id$
 */

$Datos->findFirst();

function center($text, $size){
	if(strlen($text)>=$size){
		return i18n::substr($text, 0, $size);
	}
	$spaces = str_repeat(" ", ($size-strlen($text))/2);
	return $spaces.$text.$spaces;
}

?>
<html>
<head>
<style type='text/css'>
	td, span, div, th, pre {
		font-family: 'Lucida Console', 'Courier New';
		font-size: 12px;
	}
	body {
		margin: 0px;
	}
</style>
</head>
<body>
<pre>
<?php echo center($Datos->getNombreCadena(), 40)."\n" ?>
<?php echo center($Datos->getDocumento()." No. : ".$Datos->getNit(), 40)."\n" ?>
<?php echo center(i18n::strtoupper($Datos->getNombreHotel()), 40)."\n" ?>
<?php echo center("ITEMS MAS VENDIDOS", 40)."\n" ?>
<? if($fecha_inicial==$fecha_final): ?>
	<?php echo center("Fecha: {$fecha_inicial}" , 35)."\n" ?>
<? else: ?>
	<?php echo center("Fecha: {$fecha_inicial} - {$fecha_final}" , 35)."\n" ?>
<? endif; ?>
<?php echo center("Cajero: ".strtoupper(Session::getData("usuarios_nombre")), 35)."\n" ?>
</pre>
<table>
<?php

if($fecha_inicial==$fecha_final){
	$conditions = "date(account_master.hora) = '$fecha_inicial'";
} else {
	$conditions = "date(account_master.hora) >= '$fecha_inicial' AND date(account_master.hora) <= '$fecha_final'";
}

$total = 0;
$total_venta = 0;
$db = DbBase::rawConnect();
$sql = "SELECT menus_items.nombre, SUM(account.cantidad) as cantidad,
SUM(account.total) as valor FROM account, menus_items, account_master
WHERE account_master.id = account.account_master_id AND
menus_items.id = account.menus_items_id AND $conditions
group by 1 order by 2 desc";
$q = $db->query($sql);
echo "<tr>
		<td align='center'>Nombre</td>
		<td align='center'>Cantidad</td>
		<td align='center'>Valor</td>
	   </tr>";
while($row = $db->fetchArray($q)){
	echo "<tr>";
	echo "<td align='left'>{$row['nombre']}</td>";
	echo "<td align='center'>{$row['cantidad']}</td>";
	echo "<td align='right'>{$row['valor']}</td>";
	echo "</tr>";
	$total += $row['cantidad'];
	$total_venta += $row['valor'];
}
?>
</table>
<pre>
-------------------------------------------
</pre>
<div style='pading: 20px; width:280px' align='right'>
TOTAL ITEMS : <?php echo Currency::number($total) ?><br>
TOTAL : <?php echo Currency::number($total_venta) ?>
</div>
</body>
</html>