<?php

/**
 * Hotel Front-Office Solution
 *
 * LICENSE
 *
 * This source file is subject to license that is bundled
 * with this package in the file docs/LICENSE.txt.
 *
 * @package 	Back-Office
 * @copyright 	BH-TECK Inc. 2009-2010
 * @version		$Id$
 */

?>
<html>
<head>
<meta http-equiv='Content-type' content='text/html; charset=UTF-8' />
<style type='text/css'>

h3 {
	margin: 0px;
	margin-top: 10px;
	margin-bottom: 2px;
	font-size: 13px;
	font-weight: bold;
}

table {
	border-top: 1px solid #ababab;
	border-right: 1px solid #ababab;
}

td, th {
	font-size: 11px;
	border-left: 1px solid #ababab;
	border-bottom: 1px solid #ababab;
	font-family: Verdana;
	padding-left: 5px;
	padding-right: 5px;
}

th {
	background: #eaeaea;
	font-family: Verdana;
	text-align: left;
}

table tr:nth-child(even) {
	background: #fafafa;
}

table tr:nth-child(odd) {
	background: #ffffff;
}

</style>
</head>
<body>

<div style='font-size:12px;font-family:Verdana'>
<?php

$Datos->findFirst();
echo "<b>", $Datos->getNombreCadena(), "</b><br>\n";
echo "<b>", $Datos->getDocumento(), " No. : ", $Datos->getNit(), "</b><br>\n";
echo i18n::strtoupper($Datos->getNombreHotel())."<br>\n";
echo "CONTROL SALDOS INVENTARIOS<br>";
if($fecha_inicial==$fecha_final){
	echo "Fecha: {$fecha_inicial}"."<br>";
} else {
	echo "Fecha: {$fecha_inicial} - {$fecha_final}<br>\n";
}

if($salon_id!='@'){
	if($Salon->findFirst($salon_id)){
		echo "Ambiente: {$Salon->nombre}<br>";
	}
} else {
	echo "TODOS LOS AMBIENTES<br>";
}
echo "Fecha Impresión: ".Date::now()."<br/><br/>";

View::getContent();

echo '<table cellspacing="0" cellpadding="0">';
foreach($descargue as $usuarioId => $usuarioItems){
	$usuario = $UsuariosPos->findFirst($usuarioId);
	if($usuario==false){
		echo '<tr><th colspan="8">CAJERO: NO EXISTE EL USUARIO</th></tr>';
	} else {
		echo '<tr><th colspan="8">CAJERO: '.$usuario->nombre.'</th></tr>';
	}
	foreach($usuarioItems as $numeroAlmacen => $items){
		$almacen = BackCacher::getAlmacen($numeroAlmacen);
		if($almacen==false){
			echo '<tr><th colspan="8">ALMACÉN: NO EXISTE EL ALMACÉN</th></tr>';
		} else {
			echo '<tr><th colspan="8">ALMACÉN: '.$almacen->getNomAlmacen().'</th></tr>';
		}
		echo '<tr>
			<th>CÓDIGO</th>
			<th>DESCRIPCIÓN</th>
			<th>UNIDAD</th>
			<th>ALMACÉN</th>
			<th>SALDO INICIAL</th>
			<th>CANTIDAD</th>
			<th>OTROS TURNOS</th>
			<th>SALDO FINAL</th>
		</tr>';
		foreach($items as $codigo => $item){
			$inve = BackCacher::getInve($codigo);
			if($inve==false){
				$descripcion = 'NO EXISTE REFERENCIA';
				$saldoInicial = 0;
			} else {
				$descripcion = $inve->getDescripcion();
				$saldoInicial = Tatico::getSaldo($codigo, $numeroAlmacen);
			}
			$unidad = BackCacher::getUnidad($inve->unidad);
			if($unidad==false){
				$nombreUnidad = 'NO EXISTE UNIDAD';
			} else {
				$nombreUnidad = $unidad->nom_unidad;
			}

			$saldoFinal = $saldoInicial-($item['cantidad']+$item['cantidadu']+$item['otrosCantidad']+$item['otrosCantidadU']);

			echo '<tr>
				<td>'.$codigo.'</td>
				<td>'.$descripcion.'</td>
				<td>'.$nombreUnidad.'</td>
				<td>'.$numeroAlmacen.' / '.$almacen->getNomAlmacen().'</td>
				<td align="right">'.Currency::number($saldoInicial, 2).'</td>
				<td align="right">'.Currency::number($item['cantidad']+$item['cantidadu'], 2).'</td>
				<td align="right">'.Currency::number($item['otrosCantidad']+$item['otrosCantidadU'], 2).'</td>
				<td align="right">'.Currency::number($saldoFinal, 2).'</td>
			</tr>';
		}
	}
	echo '<tr><td colspan="8">&nbsp;</td></tr>';
}
echo '</table>';


?>
<br/>

</body>
</html>