<?php

/**
 * Hotel Front-Office Solution
 *
 * LICENSE
 *
 * This source file is subject to license that is bundled
 * with this package in the file docs/LICENSE.txt.
 *
 * @package 	Back-Office
 * @copyright 	BH-TECK Inc. 2009-2010
 * @version		$Id$
 */

$Datos->findFirst();

function center($text, $size){
	if(i18n::strlen($text)>=$size){
		return i18n::substr($text, 0, $size);
	}
	$spaces = str_repeat(" ", ($size-i18n::strlen($text))/2);
	return $spaces.$text.$spaces;
}

?>
<html>
<head>
<style type='text/css'>
	td, span, div, th, pre {
		font-family: 'Lucida Console', 'Courier New';
		font-size: 12px;
	}
	body {
		margin: 0px;
	}
</style>
</head>
<body>
<pre>
<?php
	echo center($Datos->getNombreCadena(), 40)."\n";
	echo center($Datos->getDocumento()." No. : ".$Datos->getNit(), 40)."\n";
	echo center(i18n::strtoupper($Datos->getNombreHotel()), 40)."\n";
	echo center("RESUMEN DE VENTA POR PLATO", 40)."\n";
	if($fecha_inicial==$fecha_final){
		echo center("Fecha: {$fecha_inicial}" , 40)."\n";
	} else {
		echo center("Fecha: {$fecha_inicial} - {$fecha_final}" , 40)."\n";
	}
	echo center("Cajero: ".i18n::strtoupper(Session::getData("usuarios_nombre")), 40)."\n";
	if ($salon_id != '@') {
		if ($Salon->find($salon_id)) {
			echo center("Ambiente: {$Salon->nombre}" , 40)."\n";
		}
	}
	echo center("Fecha Impresión: ".Date::now(), 40)."\n";
?>
</pre>
<table>
<table style='pading: 20px; width:250px'>
<tr>
	<td align='center'>Descripción</td>
	<td align='center'>Cantidad</td>
	<td align='center'>Valor</td>
</tr>
<?php

	$total = 0;
	$total_iva = 0;
	$items = array();
	if($salon_id=='@'){
		$conditions = "date(hora) >= '$fecha_inicial' AND date(hora) <= '$fecha_final' AND estado='L'";
	} else {
		$conditions = "date(hora) >= '$fecha_inicial' AND date(hora) <= '$fecha_final' AND estado='L' AND salon_id = '{$salon_id}'";
	}
	foreach($AccountMaster->find($conditions) as $accountMaster){
		$accounts = $Account->find("account_master_id='$accountMaster->id' and estado = 'L'");
		foreach($accounts as $account){
			if(!isset($items[$account->menus_items_id])){
				$items[$account->menus_items_id] = array(
					'cantidad' => 0,
					'valor' => 0
				);
			}
			$items[$account->menus_items_id]['cantidad']+=$account->cantidad;
			if($account->descuento>0){
				$items[$account->menus_items_id]['valor']+=($account->total-$account->total*($account->descuento/100))*$account->cantidad;
			} else {
				$items[$account->menus_items_id]['valor']+=$account->total*$account->cantidad;
			}
		}
	}
	foreach($items as $item_id => $item){
		echo "<tr>";
		$menuItem = $MenusItems->findFirst($item_id);
		if($menuItem){
			echo "<td align='left'>{$MenusItems->nombre}</td>";
		} else {
			echo "<td align='left'>NO EXISTE ITEM</td>";
		}
		echo "<td align='center'>{$item['cantidad']}</td>";
		echo "<td align='right'>", Currency::number($item['valor']), "</td>";
		echo "</tr>";
		$total += $item['valor'];
	}
?>
</table>
<pre>
--------------------------------------
</pre>
<div style='pading: 20px; width:250px' align='right'>
TOTAL : <?php echo Currency::number($total) ?>
</div>
</body>
</html>
