<!DOCTYPE html>
<html>
	<head>
	<title>HFOS Housekeeper</title>

	<meta name="viewport" content="width=device-width, initial-scale=1">

	<link rel="stylesheet" href="http://code.jquery.com/mobile/1.0/jquery.mobile-1.0.min.css" />
	<link rel="stylesheet" href="/h/css/housekeeper/style.css" />
	<script type="text/javascript" src="http://code.jquery.com/jquery-1.6.4.min.js"></script>
	<script type="text/javascript" src="http://code.jquery.com/mobile/1.0/jquery.mobile-1.0.min.js"></script>
	<script type="text/javascript" src="/h/javascript/housekeeper/housekeeper.js"></script>

</head>
<body>

<?php echo View::getContent() ?>

</body>
</html>