<?php

/**
 * Hotel Front-Office Solution
 *
 * LICENSE
 *
 * This source file is subject to license that is bundled
 * with this package in the file docs/LICENSE.txt.
 *
 * @package 	Back-Office
 * @copyright 	BH-TECK Inc. 2009-2010
 * @version		$Id$
 */

?>
<html>
	<head>
		<title>Análisis de Costos de Recetas</title>
<style type='text/css'>

@font-face {
	font-family: 'Anivers';
	src: local('Anivers'),
		url('/h/files/pos2/Anivers.otf') format('opentype');
}


h1, h2 {
	margin: 0px;
	font-family: Anivers;
}

table {
	margin-top: 20px;
	width: 670px;
	border-left: 1px solid #c0c0c0;
	border-top: 1px solid #c0c0c0;
}

td {
	font-family: Verdana;
	font-size: 11px;
}

th {
	font-family: Verdana;
	font-size: 11px;
	border-right: 1px solid #c0c0c0;
	border-bottom: 1px solid #c0c0c0;
}

td {
	font-family: Verdana;
	font-size: 11px;
	border-right: 1px solid #c0c0c0;
	border-bottom: 1px solid #c0c0c0;
}

table tr:nth-child(even) {
	background: #fafafa;
}

table tr:nth-child(odd) {
	background: #ffffff;
}

</style>

</head>
<body>

<?php

echo "<h1>Análisis de Costos de las Recetas</h1>";
echo "<h2>", $datos->getNombreHotel(), "</h2>";
echo "<h2>Fecha Impresión: ", Date::now(), "</h2>";

foreach($results as $numero => $datos){
	echo "<table cellspacing=0 cellpadding=2>
		<tr>
			<td align='right' colspan='3'><b>Número</b></td>
			<td colspan='3'>$numero</td>
		</tr>
		<tr>
			<td align='right' colspan='3'><b>Nombre</b></td>
			<td colspan='3'>{$datos['nombre']}</td>
		</tr>
	<tr>
		<th width='10%'>Salon</th>
		<th width='10%'>Valor</th>
		<th width='10%'>% Costo</th>
		<th>Costo</th>
		<th>% Utilidad</th>
		<th>Utilidad</th>
	</tr>
	</thead><tbody>";
	foreach($datos['valores'] as $salon => $valores){
		echo "<tr>";
		if($salon!=0){
			echo "<td>{$valores['nombre']}</td>";
		} else {
			echo "<td>&nbsp;</td>";
		}
		echo "<td align='right'>", Currency::number($valores['valor'], 2), "</td>";
		echo "<td align='right'>", Currency::number($valores['porc_costo'], 2), "</td>";
		echo "<td align='right'>", Currency::number($valores['costo'], 2), "</td>";
		echo "<td align='right'>", Currency::number($valores['porc_utilidad'], 2), "</td>";
		echo "<td align='right'>", Currency::number($valores['utilidad'], 2), "</td>";
		echo "</tr>";
	}
	echo "</tbody></table><br>";
}
?>

</body>
</html>
