<?php

/**
 * Hotel Front-Office Solution
 *
 * LICENSE
 *
 * This source file is subject to license that is bundled
 * with this package in the file docs/LICENSE.txt.
 *
 * @package 	Back-Office
 * @copyright 	BH-TECK Inc. 2009-2010
 * @version		$Id$
 */

View::getContent();
?>

<table width="100%">
	<tr>
		<td><h1>Receta Estándar</h1></td>
		<td align="right">
			<?php echo Tag::linkTo('receta/index', 'Volver') ?>
		</td>
	</tr>
</table>

<?php

echo "<table class='lista_res' cellspacing='0' align='center'>";
echo "<thead>
	<tr>
		<th>Almacén</th>
		<th>Número</th>
		<th>Nombre</th>
		<th>Número Personas</th>
		<th>Costo</th>
	</tr>
</thead>";
foreach($recetas->items as $receta){
	echo '<tr><td align="right">', $receta->almacen,
	'</td><td align="right">', $receta->numero_rec,
	'</td><td>',
	$receta->nombre,
	'</td><td align="right">',
	$receta->num_personas,
	'</td><td align="right">',
	Currency::number($receta->precio_costo),
	'</td><td align="center">',
	Tag::linkTo('receta/editar/'.$receta->almacen.'/'.$receta->numero_rec, '<div class="edit">editar</div>'),
	'</td><td align="center">',
	Tag::linkTo('receta/eliminar/'.$receta->almacen.'/'.$receta->numero_rec, Tag::image('pos2/delete.gif')),
	'</tr>';
}
echo "</table>";
echo "<br /><div align='right'>", 'Visualizando: ', $inicial, ' - ', $final, ' de ', $total_result;
if($recetas->total_pages > 1) {
   if($page != 1) {
      echo ' | ';
      echo Tag::linkTo('receta/buscar?pag='.$recetas->first, 'Primero'),' | ';
      echo Tag::linkTo('receta/buscar?pag='.$recetas->before, 'Anterior');
   }
   if($page != $recetas->total_pages) {
      echo ' | ';
      echo Tag::linkTo('receta/buscar?pag='.$recetas->next, 'Siguiente'),' | ';
      echo Tag::linkTo('receta/buscar?pag='.$recetas->last, 'Último');
   }
}
echo "</div>";

if($total_result>15){
	echo "<br /><div align='right'>";
	echo Tag::linkTo('receta/index', 'Volver');
	echo "</div>";
}

