<?php

/**
 * Hotel Front-Office Solution
 *
 * LICENSE
 *
 * This source file is subject to license that is bundled
 * with this package in the file docs/LICENSE.txt.
 *
 * @package 	Back-Office
 * @copyright 	BH-TECK Inc. 2009-2010
 * @version		$Id$
 */

?>
<html>
	<head>
		<title>Reporte de Recetas</title>
<style type='text/css'>

@font-face {
	font-family: 'Anivers';
	src: local('Anivers'),
		url('/h/files/pos2/Anivers.otf') format('opentype');
}


h1, h2 {
	margin: 0px;
	font-family: Anivers;
}

table {
	margin-top: 20px;
	width: 670px;
}

td {
	font-family: Verdana;
	font-size: 11px;
}

.cabecera td {
	font-family: Verdana;
	font-size: 11px;
}

.detalle td {
	border-bottom: 1px solid #cacaca;
}

.detalle th {
	background-color: #dadada;
}

th {
	font-family: Verdana;
	font-size: 11px;
}

</style>

</head>
<body>

<?php

echo "<h1>Reporte de las Recetas</h1>";
echo "<h2>", $datos->getNombreHotel(), "</h2>";
echo "<h2>Fecha Impresión: ", Date::now(), "</h2>";

?>
<table width='100%' cellspacing='0'>
<?php View::getContent(); ?>
</table>
</body>
</html>