<?php

/**
 * Hotel Front-Office Solution
 *
 * LICENSE
 *
 * This source file is subject to license that is bundled
 * with this package in the file docs/LICENSE.txt.
 *
 * @package 	Back-Office
 * @copyright 	BH-TECK Inc. 2009-2010
 * @version		$Id$
 */

?>

<br><br>
<table class='lista_res' align="center" cellspacing="0">
	<tr>
		<th></th>
		<th align="center">Ambiente</th>
	</tr>
	<?php
		foreach($Salon->find('order: nombre', 'columns: id,nombre') as $salon){
			if(in_array($salon->id, $permisos)){
				$checked = 'checked';
			} else {
				$checked = '';
			}
			echo "<tr><td><input type='checkbox' $checked id='{$salon->id}' onclick='savePerm({$salon->id})'></td><td>{$salon->nombre}</td></tr>";
		}
	?>
</table>