<script type="text/javascript">

var movimiento = [];
var activeMov = -1;

new Event.observe(window, "load", function(){
	$('nit').observe('blur', function(){
		if($F('nit')!=""){
			new Ajax.Request(Utils.getKumbiaURL('cheque/queryByNit'), {
				parameters: {
					"nit": $F('nit')
				},
				onSuccess: function(t){
					var response = t.responseText.evalJSON();
					if(response.status=='OK'){
						$('nombre').value = response.nombre;
						$('beneficiario').value = response.nombre;
					} else {
						alert('No existe el NIT ó está inactivo');
					}
				}
			});
		}
	});
	$('nit2').observe('blur', function(){
		if($F('nit2')!=""){
			new Ajax.Request(Utils.getKumbiaURL('cheque/queryByNit'), {
				parameters: {
					"nit": $F('nit2')
				},
				onSuccess: function(t){
					var response = t.responseText.evalJSON();
					if(response.status=='OK'){
						$('nombre2').value = response.nombre;
					} else {
						alert('No existe el NIT ó está inactivo');
					}
				}
			});
		}
	});
	$('cuenta').observe('blur', function(){
		if($F('cuenta')!=''){
			new Ajax.Request(Utils.getKumbiaURL('cheque/queryByCuenta'), {
				parameters: {
					"cuenta": $F('cuenta')
				},
				onSuccess: function(t){
					var response = t.responseText.evalJSON();
					if(response.status=='OK'){
						$('detalleCuenta').value = response.nombre;
					} else {
						alert('No existe cuenta ó no es auxiliar');
						//$('cuenta').activate();
					}
				}
			});
		}
	});
	$('nombre').observe('blur', function(){
		if($F('beneficiario')==""){
			$('beneficiario').value = $F('nombre');
		}
	});
	$('chequeraId').observe('change', function(){
		if($F('chequeraId')!='@'){
			$('numeroCheque').value = 0;
			new Ajax.Request(Utils.getKumbiaURL('cheque/nextCheque'), {
				parameters: {
					"chequeraId": $F('chequeraId')
				},
				onSuccess: function(t){
					var response = t.responseText.evalJSON();
					if(response.status=='OK'){
						$('numeroCheque').value = response.numero;
					} else {
						alert('La chequera tiene todos sus cheques emitidos')
						$('numeroCheque').value = 0;
					}
				}
			});
		}
	});
	$('addMovi').observe('click', function(){
		if($F("cuenta")==""){
			alert("Debe indicar la cuenta");
			$('cuenta').activate();
			return;
		}
		if($F("valor2")==""||$F("valor2")=="0"){
			alert("Debe indicar el valor");
			$('valor2').activate();
			return;
		};
		var index;
		if(activeMov==-1){
			index = movimiento.length;
		} else {
			index = activeMov;
		};
		movimiento[index] = {
			'cuenta': $F('cuenta'),
			'detalleCuenta': $F('detalleCuenta'),
			'naturaleza': $F('naturaleza'),
			'descripcion': $F('descripcion'),
			'centroCosto': $F('centroCosto'),
			'textoCentro': $('centroCosto').options[$('centroCosto').selectedIndex].innerText,
			'nit2': $F('nit2'),
			'nombre2': $F('nombre2'),
			'valor2': parseFloat($F('valor2')),
			'estado': 'A'
		};
		generaTabla();
		$('nit2').setValue('');
		$('nombre2').setValue('');
		$('cuenta').setValue('');
		$('naturaleza').setValue('');
		$('descripcion').setValue('');
		$('centroCosto').setValue('');
		$('detalleCuenta').setValue('');
		$('valor2').setValue('');
		activeMov = -1;
		$('nuevoMovi').hide();
		$('addMovi').value = "Agregar";
	});
	$('valor').observe('blur', function(){
		var debitos = 0;
		var creditos = $F('valor');
		for(var i=0;i<movimiento.length;i++){
			if(movimiento[i].estado=='A'){
				if(movimiento[i].naturaleza=='D'){
					debitos+=movimiento[i].valor2;
				} else {
					creditos+=movimiento[i].valor2;
				}
			}
		};
		$('debitos').update(debitos);
		$('creditos').update(creditos);
	});
	$('generaBut').observe('click', function(){
		var debitos = 0;
		var creditos = $F('valor');
		for(var i=0;i<movimiento.length;i++){
			if(movimiento[i].estado=='A'){
				if(movimiento[i].naturaleza=='D'){
					debitos+=movimiento[i].valor2;
				} else {
					creditos+=movimiento[i].valor2;
				}
			}
		};
		if(debitos!=creditos){
			alert("Movimientos contables descuadrados, porfavor revise");
		} else {
			var nit = $F('nit');
			if(nit.strip()==''||nit=='0'){
				alert('Debe indicar el tercero');
				$('nit').activate();
				return;
			};
			var chequeraId = $F('chequeraId');
			if(chequeraId=="@"){
				alert('Debe indicar la chequera');
				return;
			};
			var valor = $F('valor');
			if(valor<=0||valor==""){
				alert('Debe indicar el valor del cheque');
				return;
			};
			for(var i=0;i<movimiento.length;i++){
				if(movimiento[i].estado=='A'){
					['nit2', 'nombre2', 'cuenta', 'naturaleza', 'descripcion', 'centroCosto', 'valor2'].each(function(id){
						var input = document.createElement('INPUT');
						input.type = "hidden";
						input.name = "f_"+id+"[]";
						input.value = movimiento[i][id];
						$('fl_form').appendChild(input);
					});
				}
			};
			$('fl_form').submit();
		}
	});
});

function generaTabla(){
	$('cmovi').innerHTML = "";
	var total = 0;
	var debitos = 0;
	var creditos = $F('valor');
	for(var i=0;i<movimiento.length;i++){
		if(movimiento[i].estado=='A'){
			var html = "<tr>"+
			"<td>"+movimiento[i].cuenta+"</td>"+
			"<td>"+movimiento[i].detalleCuenta+"</td>"+
			"<td>"+movimiento[i].textoCentro+"</td>"+
			"<td align='right'>"+movimiento[i].valor2+"</td>"+
			"<td align='center'><input type='button' value='Editar' class='controlButton' onclick='editar("+i+")'/></td>"+
			"<td align='center'><input type='button' value='Quitar' class='controlButton' onclick='quitar("+i+")'/></td>"+
			"</tr>";
			$('cmovi').innerHTML+=html;
			total+=movimiento[i].valor2;
			if(movimiento[i].naturaleza=='D'){
				debitos+=movimiento[i].valor2;
			} else {
				creditos+=movimiento[i].valor2;
			}
		}
	};
	if(total==0){
		$('generaBut').disable();
	} else {
		$('generaBut').enable();
	};
	$('debitos').update(debitos);
	$('creditos').update(creditos);
	return total;
}

function editar(index){
	$('nit2').setValue(movimiento[index].nit2);
	$('nombre2').setValue(movimiento[index].nombre2);
	$('cuenta').setValue(movimiento[index].cuenta);
	$('naturaleza').setValue(movimiento[index].naturaleza);
	$('descripcion').setValue(movimiento[index].descripcion);
	$('centroCosto').setValue(movimiento[index].centroCosto);
	$('detalleCuenta').setValue(movimiento[index].detalleCuenta);
	$('valor2').setValue(movimiento[index].valor2);
	activeMov = index;
	$('addMovi').value = "Guardar";
	$('nuevoMovi').show();
}

function quitar(index){
	movimiento[index].estado = 'B';
	generaTabla();
}

function setCuenta(input, li){
	$('cuenta').value = li.id;
}

function setTercero(input, li){
	$('nit').value = li.id;
}

function setTercero2(input, li){
	$('nit2').value = li.id;
}

</script>

<h1>Transferencia a Proveedores</h1>
<?php View::getContent();
echo Tag::form('cheque/generar', 'autocomplete: off', 'id: fl_form') ?>
	<fieldset>
		<legend>Transferencia Proveedores</legend>
			<div style="padding:10px">
				<table align="center">
					<tr>
						<td align="right"><b><label for="nit">Tercero:</label></b></td>
						<td>
							<table>
								<tr>
									<td><?php echo Tag::textField(array('nit', 'size' => 20)) ?></td>
									<td><?php echo Tag::textFieldWithAutocomplete(array('nombre', 'action' => 'cheque/queryTerceros', 'size' => 40, 'after_update' => 'setTercero')) ?></td>
								</tr>
							</table>
						</td>
					</tr>
					<tr>
						<td align="right"><b><label>Fecha Movimiento:</label></b></td>
						<td><?php
							$fecha = new Date(Date::getCurrentDate());
							echo $fecha->getLocaleDate()
						?></td>
					</tr>
					<tr>
						<td align="right"><b><label>Consecutivo:</label></b></td>
						<td><?php echo Tag::numericField(array('consecutivo', 'size' => 10)) ?></td>
					</tr>
					<tr>
						<td align="right"><b><label>Valor:</label></b></td>
						<td><?php echo Tag::numericField(array('valor', 'size' => 12)) ?></td>
					</tr>
					<tr>
						<td align="right"><b><label>Observaciones:</label></b></td>
						<td><?php echo Tag::textArea('observacion', 'rows: 4', 'cols: 70') ?></td>
					</tr>
				</table>
			</div>
	</fieldset>
	<fieldset>
		<legend>Contabilización</legend>
		<table align="center">
			<tr>
				<td align="right"><b><label for="nit">Cuenta:</label></b></td>
				<td>
					<table>
						<tr>
							<td><?php echo Tag::textField(array('cuenta', 'size' => 20)) ?></td>
							<td><?php echo Tag::textFieldWithAutocomplete(array('detalleCuenta',
								'action' => 'cheque/queryCuentas',
								'size' => 40,
								'after_update' => 'setCuenta'
							)) ?></td>
						</tr>
					</table>
				</td>
			</tr>
			<tr>
				<td align="right"><b><label for="nit">Naturaleza:</label></b></td>
				<td><?php echo Tag::selectStatic(array('naturaleza', array('D' => 'DEBITO', 'C' => 'CREDITO'))) ?></td>
			</tr>
			<tr>
				<td align="right"><b><label for="nit">Tercero:</label></b></td>
				<td>
					<table>
						<tr>
							<td><?php echo Tag::textField(array('nit2', 'size' => 20)) ?></td>
							<td><?php echo Tag::textFieldWithAutocomplete(array('nombre2', 'action' => 'cheque/queryTerceros', 'size' => 40, 'param_name' => 'nombre', 'after_update' => 'setTercero2')) ?></td>
						</tr>
					</table>
				</td>
			</tr>
			<tr>
				<td align="right"><b><label>Centro Costo:</label></b></td>
				<td><?php echo Tag::select('centroCosto', $Centros->find("estado='A'", "order: nom_centro"), 'using: codigo,nom_centro') ?></td>
			</tr>
			<tr>
				<td align="right"><b><label>Descripción:</label></b></td>
				<td><?php echo Tag::textField(array('descripcion', 'size' => 40)) ?></td>
			</tr>
			<tr>
				<td align="right"><b><label>Valor:</label></b></td>
				<td><?php echo Tag::numericField(array('valor2', 'size' => 12)) ?></td>
			</tr>
			<tr>
				<td></td>
				<td><?php echo Tag::button('Agregar', 'id: addMovi', 'class: controlButton') ?>&nbsp;
				<?php echo Tag::button('Nuevo', 'id: nuevoMovi', 'class: controlButton', 'style: display:none') ?>
				</td>
			</tr>
		</table>
		<div style="padding:5px">
			<table align="center" width="90%" class="lista_res" cellspacing="0">
				<thead>
					<th>Cuenta</th>
					<th>Descripción</th>
					<th>Centro Costo</th>
					<th>Valor</th>
					<th></th>
					<th></th>
				</thead>
				<tbody id="cmovi">
					<tr>
						<td align="center" colspan="6">NO HAY CONTRAPARTIDAS</td>
					</tr>
				</tbody>
			</table>
		</div>
		<div style="padding:5px">
			<table align="center" width="90%" class="lista_res" cellspacing="0">
				<tr>
					<td align="right"><b>Debitos:</b></td>
					<td id="debitos" align="right">0</td>
					<td align="right"><b>Créditos:</b></td>
					<td id="creditos" align="right">0</td>
				</tr>
			</table>
		</div>
	</fieldset>
	<div style="padding:5px" align="right">
		<?php echo Tag::button('Generar', 'disabled: disabled', 'class: controlButton', 'id: generaBut') ?>
	</div>
<?php echo Tag::endForm() ?>
