<?php

/**
 * Hotel Front-Office Solution
 *
 * LICENSE
 *
 * This source file is subject to license that is bundled
 * with this package in the file docs/LICENSE.txt.
 *
 * @author 		BH-TECK Inc. 2009-2010
 * @version		$Id$
 */

?>
<table width="100%" align="center" cellspacing="20">
	<tr>
		<td valign="top" width="130" align="center">
			<?php echo Tag::image('backoffice/bug.png', 'width: 128') ?>
		</td>
		<td>
			<h1>Ha ocurrido un problema</h1>
			<p>

				<div class="description" id="problemDescription">
					Se ha producido un problema inesperado en la aplicación, por favor envíe este reporte
					para que podamos evaluarlo y ayudarle a solucionar el problema.
				</div>

				<div class="description" id="emailDescription" style="display:none">
					Su servidor no permite enviar correo electrónico directamente,
					<a href="#" target="_new" id="logFile">haga click aquí</a> para
					descargar el informe de error. Por favor envíe el informe a
					<a href="mailto:soporte@bhteck.com">soporte@bhteck.com</a>
					para que podamos evaluarlo y ayudarle a solucionar el problema.
				</div>

				<div class="description" id="unknownDescription" style="display:none">
					Debido a un error desconocido, no fue posible informar sobre el problema
					a soporte técnico. El reporte será enviado nuevamente más tarde.
				</div>

				<div>
					<div align="center"></div>

					<div align="right">
						<div id="sendMessage" style="display:none" align="center">
							<div id="sendMessageDiv">
								<table align="center">
									<tr>
										<td><?php echo Tag::image('backoffice/load-sm.gif') ?></td>
										<td>Se está enviando el reporte...</td>
									</tr>
								</table>
							</div>
						</div>
					</div>

					<div align="right" id="buttonPanel">
						<input type="submit" class="controlButton" id="sendButton" value="Enviar Reporte">
						<input type="submit" class="controlButtonBack" id="missButton" value="Omitir">
					</div>

				</div>
			</p>
		</td>
	</tr>
</table>