<?php

/**
 * Hotel Front-Office Solution
 *
 * LICENSE
 *
 * This source file is subject to license that is bundled
 * with this package in the file docs/LICENSE.txt.
 *
 * @package 	Back-Office
 * @copyright 	BH-TECK Inc. 2009-2010
 * @version		$Id$
 */

?>

<div align="center">
	<?php echo Tag::form('ventas_default/guardar') ?>
	<div class="opciones_venta">
		<div align="left">
			<b class="bb">Opciones del Tipo de Pedido</b>
			<br/><br/>
		</div>
		<table align="center">
			<tr>
				<td align="right"><label for="cedula">Cliente/Empresa</label></td>
				<td>
					<?php echo Tag::textField('cedula', 'size: 10') ?>
					<?php echo Tag::textFieldWithAutocomplete('nombre', 'action: ventas_default/queryCustomers', 'size: 35', 'after_update: getCustomerId') ?>
				</td>
			</tr>
			<tr>
				<td align="right"><label for="cedula">Valor Mínimo Pedido</label></td>
				<td><?php echo Tag::numericField('valorMinimo', 'size: 7') ?></td>
			</tr>
			<tr>
				<td colspan="2" align="right">
					<?php echo Tag::submitButton('Guardar', 'class: controlButton') ?>
				</td>
			</tr>
		</table>
		<?php echo Tag::hiddenField('tipoVenta', 'value: '.$tipoVenta) ?>
	</div>
	<?php echo Tag::endForm() ?>
</div>