<?php

/**
 * Hotel Front-Office Solution
 *
 * LICENSE
 *
 * This source file is subject to license that is bundled
 * with this package in the file docs/LICENSE.txt.
 *
 * @package 	Back-Office
 * @copyright 	BH-TECK Inc. 2009-2010
 * @version		$Id$
 */

View::getContent();

?>
<div align="center">
	<div class="formExternal">
		<div class="externalHeader">
			<table width="95%" align="center" cellpadding="0" cellspacing="0">
				<tr>
					<td><h1>Cambio de Contrato<h1></td>
					<td align="right"><div class="window-close"></div></td>
				</tr>
			</table>
		</div>
		<div class="messages"></div>
		<?php echo Tag::form('contratos/cambiarContrato', 'onbeforesubmit: return false', 'autocomplete: off') ?>
			<table align="center">
				<tr>
					<td align="right"><label for="TipoContratoId">Tipo de Contrato</label></td>
					<td align="left">
					<?php 
    					echo Tag::select('TipoContratoId', $tiposContratos, 'using: id,nombre'); 
    				?></td>
					<td align="right"><?php echo Tag::submitButton('Cambiar') ?></td>
				</tr>
			</table>
			<?php echo Tag::hiddenField(array('sociosId', 'value' => $sociosId)) ?>
		<?php echo Tag::endForm() ?>
	</div>
</div>