<?php

/**
 * Hotel Front-Office Solution
 *
 * LICENSE
 *
 * This source file is subject to license that is bundled
 * with this package in the file docs/LICENSE.txt.
 *
 * @package 	Back-Office
 * @copyright 	BH-TECK Inc. 2009-2010
 * @version		$Id$
 */

View::getContent();

?>
<div align="center">
	<div class="formExternal">
		<div class="externalHeader">
			<table width="95%" align="center" cellpadding="0" cellspacing="0">
				<tr>
					<td><h1>Desistir Contrato<h1></td>
					<td align="right"><div class="window-close"></div></td>
				</tr>
			</table>
		</div>
		<div class="messages"></div>
		<?php echo Tag::form('contratos/desistir', 'onbeforesubmit: return false', 'autocomplete: off') ?>
			<table align="center" >
				<tr>
					<td align="left"><label for="estado">Tipo de Desistimiento</label></td>
					<td align="left"><?php echo Tag::select('estado', $tipoDesistimiento,'using: codigo,nombre');?></td>
				</tr>
				<tr>
					<td align="left"><label for="fecha">Fecha de Desistimiento</label></td>
					<td align="left"><?php echo Tag::dateField(array('fecha', 'class' => 'date-field')) ?></td>
				</tr>
				<tr>
					<td align="left"><label for="motivo_desistimiento">Motivo de Desistimiento</label></td>
					<td align="left">
					<?php echo Tag::select('motivo_desistimiento', $motivoDesistimiento,'using: id,nombre');?></td>
				</tr>
			</table>
			<div align="right"><?php echo Tag::submitButton('Desistir', 'class: desistirButton') ?></div>
			<?php echo Tag::hiddenField(array('sociosId', 'value' => $sociosId)) ?>
		<?php echo Tag::endForm() ?>
	</div>
</div>
