<?php

/**
 * Hotel Front-Office Solution
 *
 * LICENSE
 *
 * This source file is subject to license that is bundled
 * with this package in the file docs/LICENSE.txt.
 *
 * @package 	Back-Office
 * @copyright 	BH-TECK Inc. 2009-2010
 * @version		$Id$
 */

View::getContent();

$dataI = array();
$i = 0.0;
while($i <= 2.1){
   $dataI["$i"]="$i %";
   $i+=0.1;
}
?>
<div align="center">
	<div class="formExternal">
		<div class="externalHeader">
			<table width="95%" align="center" cellpadding="0" cellspacing="0">
				<tr>
					<td><h1>Refinanciar Contrato<h1></td>
					<td align="right"><div class="window-close"></div></td>
				</tr>
			</table>
		</div>
		<div class="messages"><?php if(isset($messages)){echo $messages;} ?></div>
		<?php 
			if(isset($status) && $status=='OK'){
				echo Tag::form('contratos/refinanciar', 'onbeforesubmit: return false', 'autocomplete: off'); 
		?>
			<table align="center" >
				<tr>
					<td align="right"><label for="valorPagado">Valor Pagado</label></td>
					<td align="left">
					<?php echo Tag::textField(array('valorPagado','readOnly'=>true));?></td>
				</tr>
				<tr>
					<td align="right"><label for="numeroCuotas">Número de Cuotas</label></td>
					<td align="left">
					<?php echo Tag::numericField(array('numeroCuotas','size'=>3));?></td>
				</tr>
				<tr>
					<td align="right"><label for="interesCorriente">Interes Corriente</label></td>
					<td align="left">
					<?php echo Tag::selectStatic('interesCorriente',$dataI);?></td>
				</tr>
				<tr>
					<td align="right"><label for="fechaPrimeraCuota">Fecha Primera Cuota</label></td>
					<td align="left">
					<?php echo Tag::date360Field('fechaPrimeraCuota');?></td>
				</tr>
			</table>
			<div align="right">
			<?php 
					echo Tag::submitButton('Refinanciar', 'class: refinanciarButton'); 
				}
			?></div>
			<?php echo Tag::hiddenField(array('sociosId', 'value' => $sociosId)) ?>
		<?php echo Tag::endForm() ?>
	</div>
</div>
