<?php

/**
 * Hotel Front-Office Solution
 *
 * LICENSE
 *
 * This source file is subject to license that is bundled
 * with this package in the file docs/LICENSE.txt.
 *
 * @package 	Back-Office
 * @copyright 	BH-TECK Inc. 2009-2010
 * @version		$Id$
 */

View::getContent();

echo '<center>',Tag::linkTo('socios/correspondencia', Tag::image("gdrive.png"), 'target: _subir'),'</center>';
?>

<!--<iframe src="socios/socios/correspondencia" width='100%'  height='100%' style='overflow:auto;'>
</iframe>-->
