
<script type="text/javascript">
/*var d1 = d2 = d3 = d4 = d5 = d6 = d7 = d8 = d9 = d10 = [];

function randomData(d, x1, x2) {
    for (var i = x1; i < x2; i += (x2 - x1) / 100)
        d.push([i, Math.sin(i * Math.sin(i))]);

    return { label: "sin(x sin(x))", data: d };
}

function linearData(d, x) {
	x = x || 10;
	for (var i = 0; i < x; i++)
	d.push([i, i*2]);
	return [{ label: "sin(x sin(x))", data: d }];
}

var d1 = [];
for(var i = 0; i < 14; i += 0.5){
	d1.push([i, 5+Math.sin(i)]);
}

var d2 = [[2, 3], [4, 8], [8, 5], [9, 13]];

var d3 = [];
for(var i = 0; i < 14; i += 0.5){
	d3.push([i, 3+Math.cos(i)]);
}

var d4 = [];
for(var i = 0; i < 14; i += 0.5){
	d4.push([i, Math.random() * 10]);
}

var d5 = [];
for(var i = 0; i < 14; i += 0.5){
	d5.push([i, Math.random() * i]);
}

var d6 = [];
for(var i = 0; i < 14; i++){
	var r = Math.floor(Math.random() * 14);
	d6.push([i, i*r]);
}

var d7 = [];
for(var i = 0; i < 14; i++){
	var r = Math.floor(Math.random() * 100);
	d7.push([i, r]);
}*/


</script>
<div id="areachart"></div>
<div class="parametrosPres">
	<table align="center">
		<tr>
			<td align="left">
				<table cellspacing="5">
					<tr>
						<td align="right"><label for="anoInicial">Mes Inicial</label></td>
						<td width="40"><?php echo Tag::selectStatic('anoInicial', range(2000, date('Year')+10)) ?></td>
						<td><?php echo Tag::monthField('mesInicial') ?></td>
						<td>&nbsp;</td>
						<td align="right"><label for="anoFinal">Mes Final</label></td>
						<td width="40"><?php echo Tag::selectStatic('anoFinal', range(2000, date('Year')+10)) ?></td>
						<td><?php echo Tag::monthField('mesFinal') ?></td>
					</tr>
					<tr>
						<td align="right"><label for="anoInicial">Centro de Costo</label></td>
						<td colspan="5"><?php echo Tag::selectStatic('centro', $centros) ?></td>
					</tr>
					<tr>
						<td align="right"><label for="anoInicial">Cuenta</label></td>
						<td colspan="5"><?php echo Tag::selectStatic('cuenta', $cuentas) ?></td>
					</tr>
				</table>
			</td>
			<td>&nbsp;</td>
			<td align="right"><?php echo Tag::submitButton('Agregar') ?></td>
		</tr>
	</table>
</div>