<?php

/**
 * Hotel Front-Office Solution
 *
 * LICENSE
 *
 * This source file is subject to license that is bundled
 * with this package in the file docs/LICENSE.txt.
 *
 * @package 	Back-Office
 * @copyright 	BH-TECK Inc. 2009-2010
 * @version		$Id$
 */

?>

<?php echo HfosTag::iconTitle('refresh.png', 'Reabrir Cierre de periodo') ?>

<?php echo Tag::form('reabrir_periodo/reabrir', 'class: reabrirForm') ?>
<table align="center">
	<tr>
		<td valign="top">
			<table>
				<tr>
					<td align="right"><label for="anteriorCierre">Fecha al Reabrir</label></td>
					<td id="anteriorCierre"><?php if (isset($fechaCierre)) { echo $fechaCierre->getLocaleDate('long');} ?></td>
				</tr>
			</table>
		</td>
	</tr>
</table>
<?php echo Tag::endForm() ?>