<?php

/**
 * Hotel Front-Office Solution
 *
 * LICENSE
 *
 * This source file is subject to license that is bundled
 * with this package in the file docs/LICENSE.txt.
 *
 * @package 	Back-Office
 * @copyright 	BH-TECK Inc. 2009-2010
 * @version		$Id$
 */

?>

<?php echo HfosTag::iconTitle('limited-edition.png', 'Cierre de Inventarios') ?>

<div class="formContent">

<table align="center" width="100%">
	<tr>
		<td valign="top" width="50%" align="center">

			<?php echo Tag::form('cerrar/process', 'class: cerrarForm', 'autocomplete: off') ?>
				<table align="center">
					<tr>
						<td align="right">
							<label for="proximoCierre">Fecha al Cerrar</label>
						</td>
						<td>
							<td id="proximoCierre"><?php echo $proximoCierre->getLocaleDate('long') ?></td>
						</td>
					</tr>
				</table>
			<?php echo Tag::endForm() ?>

			<div class="resultados"></div>
		</td>
		<td valign="top" width="50%" align="center">
			<div class="cuadro-cierre">
				<table>
					<tr>
						<td align="right"><b>Último Cierre</b></td>
						<td id="cierreActual"><?php echo $fechaCierre->getLocaleDate('long') ?></td>
					</tr>
				</table>
			</div>
		</td>
	</tr>
</table>
</div>