<?php

/**
 * Hotel Front-Office Solution
 *
 * LICENSE
 *
 * This source file is subject to license that is bundled
 * with this package in the file docs/LICENSE.txt.
 *
 * @package 	Back-Office
 * @copyright 	BH-TECK Inc. 2009-2010
 * @version		$Id$
 */

?>
	

	<p style="font-size: 14px; font-family: revert;font-weight: lighter;">Cliente: <span id='cliente'></span></p>
	<br>
	<br>

	<table cellspacing="0" width="100%" id='tbldetalle'>
		<thead>
			<tr>
				<th>Cliente</th>
				<th>Identificación</th>
				<th>prefijo</th>
				<th>Consecutivo</th>
				<th>Fecha</th>
				<th>Total</th>
				<th>Factura</th>
				<th></th>
			</tr>
		</thead>
		<tbody></tbody>
	</table>
<br/>

