<?php

/**
 * Hotel Front-Office Solution
 *
 * LICENSE
 *
 * This source file is subject to license that is bundled
 * with this package in the file docs/LICENSE.txt.
 *
 * @package 	Back-Office
 * @copyright 	BH-TECK Inc. 2009-2010
 * @version		$Id$
 */

?>

<?php echo HfosTag::iconTitle('finance-2.png', 'Consulta de Socios') ?>

<div class="formContent">

<table align="center" width="100%">
	<tr>
		<td valign="top" width="50%" align="center">

			<?php echo Tag::form('consulta_socios/generar', 'class: consultaSociosForm', 'autocomplete: off') ?>
				<table align="center">
					<tr>
						<td align="right"><label for="socios_id">Socio</label></td>
						<td> 
							<?php
								echo HfosTag::addHyperFormSpecialField(array(
									'type' => 'Socio',
									'name' => 'socios_id',
									'classForm' => 'consultaSociosForm'
								));
							?>
						</td>
					</tr>
					<tr>
						<td align="right"><label for="titulo">Titulo</label></td>
						<td> 
							<?php
								echo Tag::textField(array('titulo'));
							?>
						</td>
					</tr>
					<tr>
						<td align="right"><label for="cargo">Cargo</label></td>
						<td> 
							<?php
								echo Tag::textField(array('cargo'));
							?>
						</td>
					</tr>
					<tr>
						<td align="right"><label for="actividad">Actividad</label></td>
						<td> 
							<?php
								echo Tag::select('actividad',$actividades, 'using: id,nombre', 'useDummy: true');
							?>
						</td>
					</tr>
				</table>
			<?php echo Tag::endForm() ?>
			<?php echo HfosTag::reportTypeTag(false, false) ?>
		</td>
	</tr>
</table>
</div>
