<?php

/**
 * Hotel Front-Office Solution
 *
 * LICENSE
 *
 * This source file is subject to license that is bundled
 * with this package in the file docs/LICENSE.txt.
 *
 * @package 	Back-Office
 * @copyright 	BH-TECK Inc. 2009-2010
 * @version		$Id$
 */

$Datos->findFirst();
$DatosHotel->findFirst();

$enviroment = CoreConfig::getAppSetting('mode');

if($enviroment=='development'){

	Tag::stylesheetLink('pos2/appmenu');
	Tag::stylesheetLink('pos2/clave');
	Tag::stylesheetLink('pos2/style');
	Tag::stylesheetLink('style');

	echo Tag::javascriptInclude('pos2/windows');
	echo Tag::javascriptInclude('pos2/modal');
	echo Tag::javascriptInclude('pos2/appmenu');
	echo Tag::javascriptInclude('pos2/clave');
	echo Tag::javascriptInclude('pos2/hash');
} else {
	Tag::stylesheetLink('pos2/production/appmenu', false, 'v='.ControllerBase::APP_VERSION);
	echo Tag::javascriptInclude('pos2/production/appmenu', true, 'v='.ControllerBase::APP_VERSION);
}

View::getContent();

$fechaActual = new Date($Datos->getFecha());
$fechaHotel = new Date($DatosHotel->getFecha());

?>
<div class='appmenuup'>
	<div id='hotelname'><?php echo $Datos->getNombreHotel() ?></div>
	Hotel Front-Office Solution : Point of Sale <span class='appmenuup_fecha'>[<?php echo $fechaActual->getLocaleDate() ?>]</span>
</div>

<div class='sh_s'></div>

<div align='center'>

<?php

if(Flash::hasMessages()){
	echo '<div class="messages">';
	foreach(Flash::getMessages() as $message){
		Flash::show($message);
	}
	echo '</div>';
}
echo '<div class="appmenu_bg">';

$diaAnterior = Date::diffInterval($Datos->getFecha(), 1, Date::INTERVAL_DAY);
$devolverDiaPath = 'cal/cal'.$diaAnterior->getUsingFormat('mdd');
$cerrarDiaPath = 'cal/cal'.$Datos->getFecha()->getUsingFormat('mdd');
if(Date::isEquals($DatosHotel->getFecha(), $Datos->getFecha())==true){

 	$opts = array (
		array('pedidos', 'Pedidos en<br>Mesas/<br>Habitaciones', 'mesa.png', 'openTables()'),
		array('check', 'Revisar Pedidos', 'revisar.png', 'checkDineIn()'),
		array('status', 'Estado de<br>la Entrega', 'buscar.png', 'dineInStatus()'),
		array('cashouttro', 'Entrada/Salida<br>Cajero', 'caja.png', 'cashOuttro()'),
		array('pay', 'Pagar/Liquidar<br>Cuentas', 'pay.png', 'pay()'),
		array('cancel', 'Cancelar Pedido', 'cancelar.png', 'cancelDineIn()'),
		array('admin', 'Administración<br>Sistema', 'admin.png', 'admin()'),
		array('reports', 'Reportes', 'printer2.png', 'goReports()'),
		array('anula_factura', 'Anular Factura/Orden', 'anular.png', 'cancelFactura()'),
		array('nota_credito', 'Nota credito', 'notacredito.jpg', 'notaCredito()'),
		array('reimprimir', 'Reimprimir Factura/Orden', 'reimprimir.png', 'reimprimirFactura()'),
		array('clave', 'Cambio Clave', 'key.png', 'changePassword()'),
		array('audit', 'Auditoría Sistema', 'audit.png', 'audit()'),
		array('revert', 'Devolver Día', "$devolverDiaPath.png", 'revertDay()'),
		array('close', 'Cerrar Día', "$cerrarDiaPath.png", 'closeDay()'),
		array('reprocesar_factura_electronica', 'Reprocesar factura electrónica', 'xml_factura.jpg', 'ReprocesarFacturaraElectronica()'),
		array('reprocesar_nota_electronica', 'Reprocesar nota credito electrónica', 'xml_nota_credito.png', 'ReprocesarNotaElectronica()'),
		array('sincronizar_terceros', 'Sincronizar terceros seven', 'sincronizar_terceros.png', 'sincronizarTercerosSeven()')
	);

} else {

	$opts = array (
		array('cashouttro', 'Entrada/Salida<br>Cajero', 'caja.png', 'cashOuttro()'),
		array('admin', 'Administración<br>Sistema', 'admin.png', 'admin()'),
		array('reports', 'Reportes', 'printer2.png', 'goReports()'),
		array('anula_factura', 'Anular Factura/Orden', 'anular.png', 'cancelFactura()'),
		array('reimprimir', 'Reimprimir Factura/Orden', 'reimprimir.png', 'reimprimirFactura()'),
		array('revert', 'Devolver Día', "$devolverDiaPath.png", 'revertDay()'),
		array('close', 'Cerrar Día', "$cerrarDiaPath.png", 'closeDay()'),
		array('clave', 'Cambio Clave', 'key.png', 'changePassword()'),
		array('audit', 'Auditoría Sistema', 'audit.png', 'audit()'),
		array('reprocesar_factura_electronica', 'Reprocesar factura electrónica', 'xml_factura.jpg', 'ReprocesarFacturaraElectronica()'),
		array('reprocesar_nota_electronica', 'Reprocesar nota credito electrónica', 'xml_nota_credito.png', 'ReprocesarNotaElectronica()'),
		array('sincronizar_terceros', 'Sincronizar terceros seven', 'sincronizar_terceros.png', 'sincronizarTercerosSeven()')
	);

	echo "<div style='padding:10px'>";
	if(Date::isEarlier($DatosHotel->getFecha(), $Datos->getFecha())==false){
		echo "<table class='appmenu_adv' width='550' align='center'>
			<tr>
				<td valign='top'>".Tag::image("pos2/advert.png")."</td>
				<td width='450'>La fecha del sistema de recepción es
				".$fechaHotel->getLocaleDate().", deberá hacer
				el cierre del sistema POS antes de seguir trabajando.<br><br></td>
			</tr>
		</table>";
	} else {
		echo "<table class='appmenu_adv' width='550' align='center'>
			<tr>
				<td valign='top'>", Tag::image("pos2/advert.png"), "</td>
				<td width='450'>La fecha del sistema de recepción es
				", $fechaHotel->getLocaleDate(), ", debe esperar que se haga
				el cierre en recepción y las fechas sean iguales.<br><br></td>
			</tr>
		</table>";
	}
	echo "</div>";
}

?>
<table cellspacing="0" cellpadding="3" align='center'>
<tr>

<?php

$i = 1;
foreach($opts as $op){
	echo "<td><button class='menuButton' onclick='".$op[3]."' id='".$op[0]."'>";
	echo Tag::image("pos2/".$op[2], "width: 90")."<br>".$op[1];
	echo "</button></td>\n";
	if(($i%5)==0){
		echo '</tr><tr>';
	}
	$i++;
}

/*Compiler::setFrameworkPath('/Applications/MAMP/htdocs/back/h');
Compiler::compileFramework('../compile.php', array(
	'Library/Kumbia/ActionHelpers/Flash/Flash.php',
	'Library/Kumbia/Filter/Filter.php',
	'Library/Kumbia/ActiveRecord/Join/ActiveRecordJoin.php',
	'Library/Kumbia/ActiveRecord/Query/ActiveRecordQuery.php',
	'Library/Kumbia/ActiveRecord/Resultset/ActiveRecordResultset.php',
	'Library/Kumbia/ActiveRecord/Row/ActiveRecordRow.php',
	'Library/Kumbia/Controller/ControllerResponse.php',
	'Library/Kumbia/Controller/ControllerRequest.php',
	'Library/Kumbia/GarbageCollector/GarbageCollector.php'
));*/

//print_r(get_required_files());

?>
</tr>
</table>

</div>
</div>