<?php

/**
 * Hotel Front-Office Solution
 *
 * LICENSE
 *
 * This source file is subject to license that is bundled
 * with this package in the file docs/LICENSE.txt.
 *
 * @package 	Back-Office
 * @author 		BH-TECK Inc. 2009-2010
 * @version		$Id$
 */

echo Tag::javascriptInclude('plasticine/webcheckin') ?>

<style type="text/css">
.header {
	background-color: <?php echo JASMIN_DARK_COLOR ?>;
	background-image: url(<?php echo Core::getInstancePath() ?>img/plasticine/<?php echo Session::get('shortName') ?>-footer.png);
}
.footer {
	background-color: <?php echo JASMIN_TEXT_COLOR ?>;
	/*background-image: url(<?php echo Core::getInstancePath() ?>img/plasticine/<?php echo Session::get('shortName') ?>-header.png);*/
}
.form-checkin {
	background: <?php echo JASMIN_NORMAL_COLOR ?>;
	opacity: 0.9;
}
div.header h2 {
	color: <?php echo JASMIN_LIGHT_COLOR ?>;
}
div.indications {
	background: <?php echo JASMIN_NORMAL_COLOR ?>;
	border: 1px solid <?php echo JASMIN_LIGHT_COLOR ?>;
	color: <?php echo JASMIN_TEXT_COLOR ?>;
}
div.menuItem {
	background: <?php echo JASMIN_NORMAL_COLOR ?>;
	width: 90%;
	padding: 10px;
}
div.menuItem a {
	color: <?php echo JASMIN_TEXT_COLOR ?>;
}
input[type="submit"] {
	background-color: <?php echo JASMIN_TEXT_COLOR ?>;
	color: #ffffff;
	border: none;
	-moz-border-radius: 5px;
	-webkit-border-radius: 5px;
	border-radius: 5px;
	padding: 10px;
}
div.number {
	background-color: <?php echo JASMIN_TEXT_COLOR ?>;
}
table.rate-resume th {
	background: <?php echo JASMIN_NORMAL_COLOR ?>;
}
div.menuSelected {
	background:  <?php echo JASMIN_TEXT_COLOR ?>;
}
div.menuSelected a {
	color: #ffffff;
}
div.menuSelected div.number {
	background: <?php echo JASMIN_NORMAL_COLOR ?>;
	color:  <?php echo JASMIN_TEXT_COLOR ?>;
}
</style>
<link href='http://fonts.googleapis.com/css?family=Droid+Sans' rel='stylesheet' type='text/css'/>
<?php

if(file_exists('public/css/plasticine/'.Session::get('shortName').'.css')){
	echo Tag::stylesheetLink('plasticine/'.Session::get('shortName'));
}

?>

<div id="header" class="header">
	<table width="100%">
		<tr>
			<td width="55"><?php echo Tag::linkTo('webcheckin/index/'.$id, '<img src="/h/img/plasticine/'.Session::get('shortName').'-logo.jpg" height="42"/>') ?></td>
			<td><h2><?php echo ucwords(i18n::strtolower(JASMIN_SYSTEM_CAPTION)) ?></h2></td>
			<td align="right" valign="top">
				<?php
					if(Session::get('numeroReserva')){
						echo Tag::linkTo('webcheckin/logout/'.$id, $traslate['Salir']);
					}
				?>
			</td>
		</tr>
	</table>
</div>
<table width="100%">
	<tr>
		<?php

		$action = Router::getAction();
		if(Session::get('numeroReserva')){

		?>
		<td valign="top" width="230">
			<div class="menuItem <?php if($action=="enterInformation") echo 'menuSelected'; ?>">
				<table>
					<tr>
						<td><div class="number">1</div></td>
						<td><?php echo Tag::linkTo('webcheckin/enterInformation/'.$id, $traslate['UpdateCheckin']) ?></td>
					</tr>
				</table>
			</div>
			<div class="menuItem <?php if($action=="doPay") echo 'menuSelected'; ?>">
				<table>
					<tr>
						<td><div class="number">2</div></td>
						<td><?php echo Tag::linkTo('webcheckin/doPay/'.$id, $traslate['VerHacerDepositos']) ?></td>
					</tr>
				</table>
			</div>
			<div class="menuItem <?php if($action=="history") echo 'menuSelected'; ?>">
				<table>
					<tr>
						<td><div class="number">3</div></td>
						<td><?php echo Tag::linkTo('webcheckin/history/'.$id, $traslate['HistorialPagos']) ?></td>
					</tr>
				</table>
			</div>
		</td>
		<?php } ?>
		<td valign="top">
			<div class="content">
				<?php echo View::getContent() ?>
			</div>
		</td>
	</tr>
</table>
<div id="footer" class="footer">
	<table width="100%">
		<tr>
			<td>
				<?php echo Tag::linkTo('webcheckin/setLocale/es_CO', 'Español') ?> | <?php echo Tag::linkTo('webcheckin/setLocale/en_US', 'English') ?>
			</td>
			<td align="right"><?php echo Tag::image('plasticine/webcheckin.png') ?></td>
		</tr>
	</table>
</div>
