<?php

/**
 * Hotel Front-Office Solution
 *
 * LICENSE
 *
 * This source file is subject to license that is bundled
 * with this package in the file docs/LICENSE.txt.
 *
 * @package 	Back-Office
 * @copyright 	BH-TECK Inc. 2009-2010
 * @version		$Id$
 */

View::getContent();

?>
<div align="center">
	<div class="formExternal">
		<div class="externalHeader">
			<table width="95%" align="center" cellpadding="0" cellspacing="0">
				<tr>
					<td><h1>Imprimir<h1></td>
					<td align="right"><div class="window-close"></div></td>
				</tr>
			</table>
		</div>
		<div class="messages"></div>
		<?php echo Tag::form($controller.'/doReport', 'onbeforesubmit: return false', 'autocomplete: off') ?>
			<table align="center">
				<tr>
					<td align="right"><label for="reportType">Formato</label></td>
					<td align="left"><?php echo Tag::selectStatic('reportType', array(
						'html' => 'HTML',
						'pdf' => 'PDF',
						'text' => 'TEXTO PLANO',
					)) ?></td>
					<td align="right"><?php echo Tag::submitButton('Imprimir') ?></td>
				</tr>
			</table>
			<?php echo Tag::hiddenField(array('codigoComprobante', 'value' => $codigoComprobante)) ?>
			<?php echo Tag::hiddenField(array('codigoAlmacen', 'value' => $codigoAlmacen)) ?>
			<?php echo Tag::hiddenField(array('numero', 'value' => $numero)) ?>
		<?php echo Tag::endForm() ?>
	</div>
</div>