<?php

/**
 * Hotel Front-Office Solution
 *
 * LICENSE
 *
 * This source file is subject to license that is bundled
 * with this package in the file docs/LICENSE.txt.
 *
 * @package 	Back-Office
 * @copyright 	BH-TECK Inc. 2009-2010
 * @version		$Id$
 */

?>

<div class="resultados"></div>

<?php echo HfosTag::iconTitle('archives.png', 'Impresión Continua de Movimientos') ?>

<?php echo Tag::form('impresion/generar', 'class: impresionForm', 'autocomplete: off') ?>
<table align="center">
	<tr>
		<td valign="top">
			<table>
				<tr>
					<td align="right"><label for="tipoMovimiento">Movimiento</label></td>
					<td><?php echo Tag::selectStatic('tipoMovimiento', $tipoMovimiento) ?></td>
				</tr>
				<tr>
					<td align="right"><label for="almacen">Almacén</label></td>
					<td><?php echo Tag::select('almacen', $almacenes, 'using: codigo,nom_almacen') ?></td>
				</tr>
				<tr>
					<td align="right"><label for="fechaInicial">Fecha Inicial</label></td>
					<td><?php echo Tag::dateField('fechaInicial', 'startYear: 2000') ?></td>
				</tr>
				<tr>
					<td align="right"><label for="fechaFinal">Fecha Final</label></td>
					<td><?php echo Tag::dateField('fechaFinal', 'startYear: 2000') ?></td>
				</tr>
				<tr>
					<td align="right"><label for="numeroInicial">Consecutivo Inicial</label></td>
					<td><?php echo Tag::numericField('numeroInicial', 'size: 7') ?></td>
				</tr>
				<tr>
					<td align="right"><label for="numeroFinal">Consecutivo Final</label></td>
					<td><?php echo Tag::numericField('numeroFinal', 'size: 7') ?></td>
				</tr>
				<tr>
					<td align="right"></td>
					<td>
						<table cellspacing="0">
							<tr>
								<td>
									<input type="submit" value="Generar"/>
								</td>
								<td>
									<div class="formSpinner" style="display:none"></div>
								</td>
							</tr>
						</table>
					</td>
				</tr>
			</table>
		</td>
		<td valign="top">
			<div class="cuadro-cierre">
				<table>
					<tr>
						<td align="right"><b>Último Cierre</b></td>
						<td><?php echo $fechaCierre->getLocaleDate('long') ?></td>
					</tr>
				</table>
			</div>
		</td>
	</tr>
</table>
<?php echo HfosTag::reportTypeTag(true, false) ?>
<?php echo Tag::endForm() ?>
