<?php

/**
 * Hotel Front-Office Solution
 *
 * LICENSE
 *
 * This source file is subject to license that is bundled
 * with this package in the file docs/LICENSE.txt.
 *
 * @package 	Back-Office
 * @copyright 	BH-TECK Inc. 2009-2010
 * @version		$Id$
 */

?>
<div id="context">
	<table cellpadding="5" width="100%">
		<tr>
			<td width="32" align="center"><?php echo Tag::image("pos2/chat.png") ?></td>
			<td id="contextMessage" align="left"></td>
		</tr>
		<tr>
			<td colspan="2" align="right">
				<div align="right">
					<table>
						<tr>
							<td align='center'>
								<button  class='bigButtonOK' id='okModal'>
						 			<?php echo Tag::image("pos2/accept-pg.png", "width: 23") ?><br>
						 			<b>OK</b><br>
					 			</button>
							</td>
							<td align='center'>
								<button  class='bigButtonCancel' id='noModal'>
						 			<?php echo Tag::image("pos2/delete-pr.png", "width: 23") ?><br>
						 			<b>NO</b><br>
					 			</button>
							</td>
						</tr>
					</table>
				</div>
			</td>
		</tr>
	</table>
</div>