<?php

/**
 * Hotel Front-Office Solution
 *
 * LICENSE
 *
 * This source file is subject to license that is bundled
 * with this package in the file docs/LICENSE.txt.
 *
 * @package 	Persé
 * @copyright 	BH-TECK Inc. 2009-2010
 * @version		$Id$
 */

?>
<html>
	<head>
		<title>Persé</title>
		<meta http-equiv="Content-type" content="text/html; charset=UTF-8" />
		<?php
			if(Browser::isOperaMobile()){
				echo '<meta name="viewport" content="width=480px,height=650px" />';
			} else {
				echo '<meta name="viewport" content="width=320px,height=500px" />';
			}
			Tag::stylesheetLink('perse/mobile');
			echo Tag::stylesheetLinkTags();
		?>
	</head>
	<body>
		<?php View::getContent(); ?>
	</body>
</html>