<?php

/**
 * Hotel Front-Office Solution
 *
 * LICENSE
 *
 * This source file is subject to license that is bundled
 * with this package in the file docs/LICENSE.txt.
 *
 * @package 	Back-Office
 * @author 		BH-TECK Inc. 2009-2010
 * @version		$Id$
 */
?>
<html>
	<head>
		<title>Cheque #<?php echo $cheque->getNumeroCheque() ?></title>
		<style type="text/css">
			body {
				margin: 0px;
			}
			.page {
				position: absolute;
				top: 0px;
				left: 0px;
				z-index: 100;
				/*width: 700px;*/
			}
			table#layout {
				height: 650px;
			}
			.page td,
			.page th {
				font-size: 13px;
			}
			.firma {
				height: 50px;
			}
			.firmaf {
				border-bottom: none;
			}
			.firmac {
				border-top: none;
			}
			div.block {
				display: inline;
			}
			div.blockw {
				display: inline;
			}
			div#formato	{
				font-family: Lucida Console;
				font-size: 12px;
			}
			.resumen td {
				font-family: Lucida Console;
				font-size: 12px;
			}
			.cheque-dummy {
				position: absolute;
				z-index: 50;
				width: 700px;
				height: 1024px;
			}
		</style>
	</head>
	<body>
		<div class="page">
			<div id="formato">
			<?php

			$currency = new Currency();
			$formatoCheque = $cheque->getChequeras()->getFormatoCheque();
			$formato = array();
			$items = array('ano', 'mes', 'dia', 'valor', 'tercero', 'suma');
			foreach($items as $item){
				$rPos = (int) $formatoCheque->readAttribute('r_'.$item);
				$cPos = (int) $formatoCheque->readAttribute('p_'.$item);
				$formato[$rPos][$cPos] = $item;
			}

			$fechaCheque = $cheque->getFecha();
			$suma = $currency->getMoneyAsText($cheque->getValor(), 'PESOS', 'CENTAVOS');
			for($j=1;$j<=40;$j++){
				for($i=1;$i<=130;$i++){
					if(isset($formato[$j][$i])){
						switch($formato[$j][$i]){
							case 'ano':
								echo $fechaCheque->getYear();
								$i++;
								break;
							case 'mes':
								echo $fechaCheque->getMonth();
								break;
							case 'dia':
								echo $fechaCheque->getDay();
								break;
							case 'valor':
								echo Locale::money($cheque->getValor());
								$i+=4;
								break;
							case 'tercero':

								$value = '';
								$final = array();
								$parts = preg_split('/[ ]+/', $cheque->getBeneficiario());
								foreach($parts as $part){
									if(i18n::strlen($value.$part)<80){
										$value.=$part;
										$final[] = $part;
									}
								}
								echo join(' ', $final);

								$i+=120;
								break;
							case 'suma':

								$value = '';
								$final = array();
								$extra = array();
								$parts = preg_split('/[ ]+/', $suma);
								foreach($parts as $part){
									if(i18n::strlen($value.$part)<70){
										$value.=$part;
										$final[] = $part;
									} else {
										$extra[] = $part;
									}
								}
								if(count($extra)>0){
									$suma = join(' ', $extra);
									$formato[$j+1][$i] = 'suma';
								}

								echo join(' ', $final);
								$i+=70;
								break;
							case 'contab':
								echo '<table width="75%" class="resumen" align="center">';
								echo '<tr>';
								echo '<td align="right" colspan="3">', $cheque->getComprob(), '-', $cheque->getNumero(), '<br><br></td>';
								echo '</tr>';
								$debitos = 0;
								$creditos = 0;
								foreach($cheque->getMovi() as $movi){
									echo '<tr>';
									echo '<td>', $movi->getCuenta(), '</td>';
									echo '<td>', $movi->getDescripcion(), '</td>';
									echo '<td align="right">', Locale::money($movi->getValor()), '</td>';
									echo '</tr>';
								}
								echo '</table>';
						}
					} else {
						echo '&nbsp;';
					}
				}
				echo '<br>';
			}
		?>
		</div>
		</div>

	</body>
</html>
