<?php

/**
 * Hotel Front-Office Solution
 *
 * LICENSE
 *
 * This source file is subject to license that is bundled
 * with this package in the file docs/LICENSE.txt.
 *
 * @package 	Back-Office
 * @copyright 	BH-TECK Inc. 2009-2010
 * @version		$Id$
 */

?>

<?php echo HfosTag::iconTitle('credit-card.png', 'Consultar Recibos de Caja') ?>

<div class="formContent">

	<div class="formBusqueda formPannel">

		<?php echo Tag::form('recibo_caja/buscar', 'class: buscarReccajForm', 'autocomplete: off') ?>
			<table align="center">
				<!--<tr>
					<td align="right"><label for="comprob">Comprobante</label></td>
					<td>
						<table class="comprobCompleter" cellspacing="0">
							<tr>
								<td><?php echo Tag::textField(array('comprob', 'size' => 12)) ?></td>
								<td><?php echo Tag::textField(array('comprob_det', 'size' => 35, 'class' => 'terceroDetalle')) ?>
								</td>
							</tr>
						</table>
					</td>
				</tr>-->
				<tr>
					<td align="right"><label for="comprob">Comprobante</label></td>
					<td>
						<?php
							echo HfosTag::addHyperFormSpecialField(array(
								'type' => 'Comprob',
								'name' => 'comprob',
								'classForm' => 'buscarReccajForm'
							));
						?>
					</td>
				</tr>
				<tr>
					<td align="right"><label for="tercero">Tercero</label></td>
					<td>
						<?php
							echo HfosTag::addHyperFormSpecialField(array(
								'type' => 'Tercero',
								'name' => 'tercero',
								'classForm' => 'buscarReccajForm'
							));
						?>
					</td>
				</tr>
				<tr>
					<td align="right"><label for="numeroInicial">Consecutivo Inicial</label></td>
					<td><?php echo Tag::numericField('numeroInicial', 'size: 7') ?></td>
				</tr>
				<tr>
					<td align="right"><label for="numeroFinal">Consecutivo Final</label></td>
					<td><?php echo Tag::numericField('numeroFinal', 'size: 7') ?></td>
				</tr>
				<tr>
					<td align="right"><label for="estado">Estado</label></td>
					<td><?php echo Tag::selectStatic('estado', array(
						'C' => 'Contabilizado',
						'A' => 'Anulado'
					), 'useDummy: yes') ?></td>
				</tr>
				<tr>
					<td></td>
					<td colspan="2">
						<table cellspacing="0">
							<tr>
								<td>
									<input type="submit" value="Consultar"/>
								</td>
								<td>
									<div class="formSpinner" style="display:none"></div>
								</td>
							</tr>
						</table>
					</td>
				</tr>
			</table>
		<?php echo Tag::endForm() ?>
	</div>

	<div class="resultados"></div>

</div>
