<?php

/**
 * Hotel Front-Office Solution
 *
 * LICENSE
 *
 * This source file is subject to license that is bundled
 * with this package in the file docs/LICENSE.txt.
 *
 * @package 	Back-Office
 * @copyright 	BH-TECK Inc. 2009-2010
 * @version		$Id$
 */

?>

<div align="center">
	<div class="infoBox">
		<table align="center">
			<tr>
				<td>No se ha generado la depreciación mensual</td>
			</tr>
		</table>
	</div>
</div>