<?php

/**
 * Hotel Front-Office Solution
 *
 * LICENSE
 *
 * This source file is subject to license that is bundled
 * with this package in the file docs/LICENSE.txt.
 *
 * @package 	Back-Office
 * @copyright 	BH-TECK Inc. 2009-2010
 * @version		$Id$
 */

View::getContent();

?>
<div align="center">
	<div class="formExternal">
		<div class="externalHeader">
			<table width="95%" align="center" cellpadding="0" cellspacing="0">
				<tr>
					<td><h1>Estado de Cuenta de Prestamo <?php echo $prestamoId; ?><h1></td>
					<td align="right"><div class="window-close"></div></td>
				</tr>
			</table>
		</div>
		<div class="messages"></div>
		<?php echo Tag::form('prestamos_socios/estadoCuenta', 'onbeforesubmit: return false', 'autocomplete: off'); ?>
			<table class="hyBrowseTab zebraSt sortable" cellspacing="0" cellpadding="0" align="center">
			<?php
				if (isset($nit)) {
					echo $nit;
				}
				
				if (isset($moviObj)) {
					echo '<tr>',
							'<th class="sortcol">Comprobante</th>',
							'<th class="sortcol">Número</th>',
							'<th class="sortcol">Fecha</th>',
							'<th class="sortcol">DebCre</th>',
							'<th class="sortcol">Valor</th>',
							'<th class="sortcol">&nbsp;</th>',
						'</tr>';

					$totales = array('D'=>0,'C'=>0);
					foreach ($moviObj as $movi) 
					{
						$detDebCre = 'Credito';
						if ($movi->getDebCre()=='D') {
							$detDebCre = 'Debito';
						}
						echo '<tr>',
							'<td>',$movi->getComprob(),'</td>',
							'<td>',$movi->getNumero(),'</td>',
							'<td>',$movi->getFecha(),'</td>',
							'<td align="center">',$detDebCre,'</td>',
							'<td>',Currency::money($movi->getValor()),'</td>',
							'<td>&nbsp;</td>',
						'</tr>';
						$totales[$movi->getDebCre()]+=$movi->getValor();
					}
					$totalD = $valorInicial;
					echo '<tr>',
							'<td><b>Pagos:</b></td>',
							'<td>',Currency::money($totales['C'],0),'</td>',
							'<td><b>Total Convenio:</b></td>',
							'<td>',Currency::money($totalD,0),'</td>',
							'<td><b>Saldo:</b></td>',
							'<td>',Currency::money(abs($totales['C'] - $totalD),0),'</td>',
						'</tr>';
				}
			?>
			</table>
		<?php echo Tag::endForm() ?>
	</div>
</div>