<?php

/**
 * Hotel Front-Office Solution
 *
 * LICENSE
 *
 * This source file is subject to license that is bundled
 * with this package in the file docs/LICENSE.txt.
 *
 * @package 	Back-Office
 * @copyright 	BH-TECK Inc. 2009-2010
 * @version		$Id$
 */

?>

<?php echo HfosTag::iconTitle('hire-me.png', 'Cambiar un Tercero por Otro') ?>

<div class="formContent">

	<div class="formBusqueda formPannel">

		<table align="center">
			<tr>
				<td valign="top">

					<?php echo Tag::form('cambio_nit/cambiar', 'class: cambiarForm', 'autocomplete: off') ?>
						<table align="center">
							<tr>
								<td align="right"><label for="nitErrado">Tercero Errado</label></td>
								<td><?php echo HfosTag::terceroField('nitErrado') ?></td>
							</tr>
							<tr>
								<td align="right"><label for="nitCorrecto">Tercero Correcto</label></td>
								<td><?php echo HfosTag::terceroField('nitCorrecto', true) ?></td>
							</tr>
						</table>
						<br/>
						<fieldset>
							<legend>Rango de Fechas ó Cuentas (Opcional)</legend>
							<table align="center">
								<tr>
									<td align="right"><label for="fechaInicial">Fecha Inicial</label></td>
									<td><?php echo Tag::dateField('fechaInicial') ?></td>
								</tr>
								<tr>
									<td align="right"><label for="fechaFinal">Fecha Final</label></td>
									<td><?php echo Tag::dateField('fechaFinal') ?></td>
								</tr>
								<tr>
									<td align="right"><label for="cuentaInicial">Cuenta Inicial</label></td>
									<td><?php echo HfosTag::cuentaField('cuentaInicial') ?></td>
								</tr>
								<tr>
									<td align="right"><label for="cuentaFinal">Cuenta Final</label></td>
									<td><?php echo HfosTag::cuentaField('cuentaFinal') ?></td>
								</tr>
							</table>
						</fieldset>
					<?php echo Tag::endForm() ?>
				</td>
				<td valign="top">
					<div class="cuadro-cierre">
						<table>
							<tr>
								<td align="right"><b>Último Cierre</b></td>
								<td><?php echo $fechaCierre->getLocaleDate('short') ?></td>
							</tr>
							<tr>
								<td align="right"><b>Año Cierre</b></td>
								<td><?php echo $anoCierre ?></td>
							</tr>
						</table>
					</div>
				</td>
			</tr>
		</table>

	</div>

	<div class="resultados"></div>

</div>
