<?php

/**
 * Hotel Front-Office Solution
 *
 * LICENSE
 *
 * This source file is subject to license that is bundled
 * with this package in the file docs/LICENSE.txt.
 *
 * @package 	Back-Office
 * @copyright 	BH-TECK Inc. 2009-2010
 * @version		$Id$
 */

?>
<div align="center">
	<div class="formExternal">
		<div class="externalHeader">
			<table width="95%" align="center" cellpadding="0" cellspacing="0">
				<tr>
					<td><h1>Consultar Ordenes de Compra</h1></td>
					<td align="right"><div class="window-close"></div></td>
				</tr>
			</table>
		</div>
		<div class="messages" align="center"><?php View::getContent() ?></div>
		<?php echo Tag::form(array('ordenes/buscar', 'class' => 'ordenForm')) ?>
		<table>
			<tr>
				<td align="right" width="10%"><label for="almacenConsulta">Almacén</label></td>
				<td><?php echo Tag::select('almacenConsulta', $almacenes, 'using: codigo,nom_almacen') ?></td>
			</tr>
			<tr>
				<td align="right"><label for="estadoOrden">Estado</label></td>
				<td><?php echo Tag::selectStatic('estadoOrden', $estados) ?></td>
			</tr>
			<tr>
				<td></td>
				<td>
					<table cellspacing="0" cellpadding="0">
						<tr>
							<td><input type="button" class="consultarButton" value="Consultar"/></td>
							<td><div class="formSpinner" style="display:none"></div></td>
						</tr>
					</table>
				</td>
			</tr>
		</table>
		<?php echo Tag::endForm();

		echo '<div class="ordenes">';
		View::renderPartial('resultados');
		echo '</div>';

		?>
	</div>
</div>