<?php

/**
 * Hotel Front-Office Solution
 *
 * LICENSE
 *
 * This source file is subject to license that is bundled
 * with this package in the file docs/LICENSE.txt.
 *
 * @package 	Back-Office
 * @copyright 	BH-TECK Inc. 2009-2010
 * @version		$Id$
 */

$action = Router::getAction();

?>
<div class="abonoContrato hfosContent">

	<div class="hfosToolbar">
		<table width="99%">
			<tr>
				<td align="left">
					<table>
						<tr>
							<?php
								switch($action){
									case 'nuevo':
									case 'ver':
									case 'errores':
										echo '<td align="right">
											<input type="button" class="controlButton backButton" value="Volver"/>
										</td>';
										break;
								}
							?>
						</tr>
					</table>
				</td>
				<td align="right">
					<table>
						<tr>
							<?php
								switch($action){
									case 'index':
										echo '
										<td align="left" class="hyTdLeftControlButton">
										</td>';
										break;
									case 'ver':
									    echo '
										<td align="left" class="hyTdLeftControlButton">
											<input type="button" class="controlButton newButton" value="Hacer un Abono"/>
										</td>
										<td align="left" class="hyTdLeftControlButton">
											<input type="button" class="hyControlButton printButton" value="Imprimir"/>
										</td>
										<td align="left" class="hyTdLeftControlButton">
											<input type="button" class="hyControlButton deleteButton" value="Anular"/>
										</td>
										<td align="left">
											<div class="headerSpinner" style="display:none"></div>
										</td>';
										break;
									case 'nuevo':
										echo '<td align="left" class="hyTdLeftControlButton">
											<input type="button" class="hyControlButton saveButton" value="Grabar"/>
										</td>
										<td align="left">
											<div class="headerSpinner" style="display:none"></div>
										</td>';
										break;
								}
							?>
						</tr>
					</table>
				</td>
			</tr>
		</table>
	</div>

	<div class="messages">
		<?php
			if(isset($message)){
				echo '<div class="notice">', $message, '</div>';
			}
		?>
	</div>

	<div class="formMain">
		<?php View::getContent() ?>
	</div>

</div>
