<?php

/**
 * Hotel Front-Office Solution
 *
 * LICENSE
 *
 * This source file is subject to license that is bundled
 * with this package in the file docs/LICENSE.txt.
 *
 * @package 	Back-Office
 * @copyright 	BH-TECK Inc. 2009-2010
 * @version		$Id$
 */

?>

<?php echo HfosTag::iconTitle('refresh.png', 'Reabrir Año') ?>

<div align="center">
	<div class="infoBox">
		El último mes cerrado no es diciembre. Último cierre
		<?php echo $fechaCierre->getLocaleDate('short') ?>
	</div>
</div>