Answer The phone

<div id="pote" style="position:absolute; top: 100px; left: 100px; width: 300px; height: 300px; background: red">
	<h1>No she</h1>
	<div id="noshe" style="position: absolute; top: 0px; background: green; width: 40px; height: 40px; -moz-user-select: none; cursor: move" class="dragme"></div>
</div>

<script type="text/javascript">
new Event.observe(window, "load", function(){
	Hfos.initialize();
	try {
		/*Hfos.getAnimation().morph($('pote'), {
			duration: 10,
			style: {
				top: 50,
				left: 50,
				width: 400,
				height: 400
			}
		});*/

		new HfosDraggable($('pote'), {
			handle: $('noshe')
		});

	}
	catch(e){
		alert(e)
	}
})
</script>
