<!-- <table cellspacing="0" cellpadding="0">
	<tr>
		<td>
			<input type="text" id="cuenta1" size="12" value="" class="cuenta"/>
		</td>
		<td><input type="text" id="detalle1" size="30"/></td>
	</tr>
</table>

<script type="text/javascript">new HfosCuentasSelector('cuenta1', 'detalle1');</script>

<div style="width:100%;background:#fff;height:100px">
<?php echo Tag::dateField('fecha', 'today: yes'); ?>

<div id="calendar"></div>

</div> -->

<script type="text/javascript">

var y = {

	a: 1,
	b: 2

};



var x = function(a, b, c){
	alert(a)
	alert(b)
	alert(c)
};

z = x.bind(y, 1, 2);

z(3);


</script>