
<style type="text/css" media="screen">
	#experiment {
      -webkit-perspective: 1200;
      -webkit-perspective-origin: 50% 200px;
    }

    #cube {
      position: relative;
      margin: 0 auto;
      height: 400px;
      width: 400px;
      -webkit-transition: -webkit-transform 1s linear;
      -webkit-transform-style: preserve-3d;
    }

    .face {
      position: absolute;
      height: 360px;
      width: 360px;
      padding: 20px;
      background-color: rgba(50, 50, 50, 0.7);
      font-size: 27px;
      line-height: 1em;
      color: #fff;
      border: 1px solid #555;
      -webkit-border-radius: 3px;
    }

    #cube .one  {
      -webkit-transform: rotateX(90deg) translateZ(200px);
    }

    #cube .two {
      -webkit-transform: translateZ(200px);
    }

    #cube .three {
      -webkit-transform: rotateY(90deg) translateZ(200px);
    }

    #cube .four {
      -webkit-transform: rotateY(180deg) translateZ(200px);
    }

    #cube .five {
      -webkit-transform: rotateY(-90deg) translateZ(200px);
    }

    #cube .six {
      -webkit-transform: rotateX(-90deg) rotate(180deg) translateZ(200px) ;
    }

  </style>

  <script type="text/javascript">

  	var xAngle = 0, yAngle = 0;
	document.addEventListener('keydown', function(e)
	{
		switch(e.keyCode)
		{

			case 37: // left
				yAngle -= 90;
				break;

			case 38: // up
				xAngle += 90;
				break;

			case 39: // right
				yAngle += 90;
				break;

			case 40: // down
				xAngle -= 90;
				break;
		};

		$('userSpace').style.webkitTransform = "rotateX("+xAngle+"deg) rotateY("+yAngle+"deg)";
	}, false);

  </script>

</head>

<!--<body>
<div id="wrapper">
	<br><br><br><br><br>
	<div id="experiment">
		<div id="cube">
	        <div class="face one">
				One face
	        </div>
	        <div class="face two">
				Up, down, left, right
	        </div>
	        <div class="face three">
				Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.
	        </div>
	        <div class="face four">
				New forms of navigation are fun.
	        </div>
	        <div class="face five">
				Rotating 3D cube
	        </div>
	        <div class="face six">
				No she
	        </div>
	    </div>
	</div>

</div>-->