<?php

/**
 * Hotel Front-Office Solution
 *
 * LICENSE
 *
 * This source file is subject to license that is bundled
 * with this package in the file docs/LICENSE.txt.
 *
 * @package 	Back-Office
 * @copyright 	BH-TECK Inc. 2009-2010
 * @version		$Id$
 */

?>
<div class="kardex hfosContent">

	<div class="hfosToolbar">
		<table width="99%">
			<tr>
				<td align="left">
					<table>
						<tr>
							<td align="right" style="display:none">
								<input type="button" class="controlButton backSearchButton" value="Volver"/>
							</td>
						</tr>
					</table>
				</td>
				<td align="right">
					<table>
						<tr>
							<td colspan="3"></td>
						</tr>
					</table>
				</td>
			</tr>
		</table>
	</div>

	<div class="messages">
		<div class="notice">Ingrese un criterio de búsqueda para consultar kardex</div>
	</div>

	<div class="formMain">

		<?php View::getContent() ?>

	</div>

</div>
