a:54:{s:7:"account";a:4:{s:4:"type";s:5:"TABLE";s:3:"sql";s:1175:"CREATE TABLE `account` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `account_master_id` int(11) NOT NULL,
  `salon_mesas_id` int(11) NOT NULL,
  `comanda` int(3) DEFAULT NULL,
  `cuenta` int(11) DEFAULT NULL,
  `asiento` int(3) DEFAULT NULL,
  `menus_items_id` int(11) NOT NULL,
  `cantidad` int(10) unsigned NOT NULL,
  `cantidad_atendida` int(10) unsigned DEFAULT '0',
  `cantidad_cocina` int(10) unsigned DEFAULT '0',
  `valor` decimal(10,2) NOT NULL DEFAULT '0.00',
  `servicio` decimal(10,2) DEFAULT NULL,
  `iva` decimal(10,2) DEFAULT NULL,
  `impo` decimal(10,2) DEFAULT '0.00',
  `total` decimal(10,2) DEFAULT NULL,
  `descuento` decimal(5,2) DEFAULT NULL,
  `tiempo` char(8) DEFAULT NULL,
  `tiempo_final` char(8) DEFAULT NULL,
  `note` varchar(300) DEFAULT NULL,
  `estado` char(1) DEFAULT NULL,
  `send_kitchen` char(1) DEFAULT 'N',
  PRIMARY KEY (`id`),
  KEY `salon_mesas_id` (`salon_mesas_id`,`comanda`,`cuenta`),
  KEY `send_kitchen` (`send_kitchen`),
  KEY `account_master_id` (`account_master_id`,`cuenta`),
  KEY `salon_mesas_id_2` (`salon_mesas_id`,`estado`),
  KEY `menus_items_id` (`menus_items_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 ROW_FORMAT=DYNAMIC";s:6:"fields";a:21:{s:2:"id";s:38:"  `id` int(11) NOT NULL AUTO_INCREMENT";s:17:"account_master_id";s:38:"  `account_master_id` int(11) NOT NULL";s:14:"salon_mesas_id";s:35:"  `salon_mesas_id` int(11) NOT NULL";s:7:"comanda";s:31:"  `comanda` int(3) DEFAULT NULL";s:6:"cuenta";s:31:"  `cuenta` int(11) DEFAULT NULL";s:7:"asiento";s:31:"  `asiento` int(3) DEFAULT NULL";s:14:"menus_items_id";s:35:"  `menus_items_id` int(11) NOT NULL";s:8:"cantidad";s:38:"  `cantidad` int(10) unsigned NOT NULL";s:17:"cantidad_atendida";s:50:"  `cantidad_atendida` int(10) unsigned DEFAULT '0'";s:15:"cantidad_cocina";s:48:"  `cantidad_cocina` int(10) unsigned DEFAULT '0'";s:5:"valor";s:47:"  `valor` decimal(10,2) NOT NULL DEFAULT '0.00'";s:8:"servicio";s:39:"  `servicio` decimal(10,2) DEFAULT NULL";s:3:"iva";s:34:"  `iva` decimal(10,2) DEFAULT NULL";s:4:"impo";s:37:"  `impo` decimal(10,2) DEFAULT '0.00'";s:5:"total";s:36:"  `total` decimal(10,2) DEFAULT NULL";s:9:"descuento";s:39:"  `descuento` decimal(5,2) DEFAULT NULL";s:6:"tiempo";s:31:"  `tiempo` char(8) DEFAULT NULL";s:12:"tiempo_final";s:37:"  `tiempo_final` char(8) DEFAULT NULL";s:4:"note";s:34:"  `note` varchar(300) DEFAULT NULL";s:6:"estado";s:31:"  `estado` char(1) DEFAULT NULL";s:12:"send_kitchen";s:36:"  `send_kitchen` char(1) DEFAULT 'N'";}s:7:"indexes";a:5:{s:14:"salon_mesas_id";s:60:"  KEY `salon_mesas_id` (`salon_mesas_id`,`comanda`,`cuenta`)";s:12:"send_kitchen";s:37:"  KEY `send_kitchen` (`send_kitchen`)";s:17:"account_master_id";s:56:"  KEY `account_master_id` (`account_master_id`,`cuenta`)";s:16:"salon_mesas_id_2";s:52:"  KEY `salon_mesas_id_2` (`salon_mesas_id`,`estado`)";s:14:"menus_items_id";s:41:"  KEY `menus_items_id` (`menus_items_id`)";}}s:15:"account_cuentas";a:4:{s:4:"type";s:5:"TABLE";s:3:"sql";s:795:"CREATE TABLE `account_cuentas` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `account_master_id` int(11) NOT NULL,
  `cuenta` int(11) NOT NULL,
  `clientes_cedula` char(15) DEFAULT NULL,
  `clientes_nombre` varchar(45) DEFAULT NULL,
  `habitacion_id` int(7) DEFAULT NULL,
  `prefijo` char(4) NOT NULL,
  `numero` int(11) DEFAULT NULL,
  `nota` char(150) DEFAULT NULL,
  `tipo_venta` char(1) DEFAULT NULL,
  `propina_fija` char(1) DEFAULT 'N',
  `propina` decimal(12,2) DEFAULT NULL,
  `estado` char(1) NOT NULL DEFAULT 'A',
  PRIMARY KEY (`id`),
  KEY `prefijo` (`prefijo`,`numero`),
  KEY `habitacion_id` (`habitacion_id`),
  KEY `account_master_id` (`account_master_id`,`cuenta`),
  KEY `account_master_id_2` (`account_master_id`,`estado`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 ROW_FORMAT=DYNAMIC";s:6:"fields";a:13:{s:2:"id";s:38:"  `id` int(11) NOT NULL AUTO_INCREMENT";s:17:"account_master_id";s:38:"  `account_master_id` int(11) NOT NULL";s:6:"cuenta";s:27:"  `cuenta` int(11) NOT NULL";s:15:"clientes_cedula";s:41:"  `clientes_cedula` char(15) DEFAULT NULL";s:15:"clientes_nombre";s:44:"  `clientes_nombre` varchar(45) DEFAULT NULL";s:13:"habitacion_id";s:37:"  `habitacion_id` int(7) DEFAULT NULL";s:7:"prefijo";s:28:"  `prefijo` char(4) NOT NULL";s:6:"numero";s:31:"  `numero` int(11) DEFAULT NULL";s:4:"nota";s:31:"  `nota` char(150) DEFAULT NULL";s:10:"tipo_venta";s:35:"  `tipo_venta` char(1) DEFAULT NULL";s:12:"propina_fija";s:36:"  `propina_fija` char(1) DEFAULT 'N'";s:7:"propina";s:38:"  `propina` decimal(12,2) DEFAULT NULL";s:6:"estado";s:39:"  `estado` char(1) NOT NULL DEFAULT 'A'";}s:7:"indexes";a:4:{s:7:"prefijo";s:36:"  KEY `prefijo` (`prefijo`,`numero`)";s:13:"habitacion_id";s:39:"  KEY `habitacion_id` (`habitacion_id`)";s:17:"account_master_id";s:56:"  KEY `account_master_id` (`account_master_id`,`cuenta`)";s:19:"account_master_id_2";s:58:"  KEY `account_master_id_2` (`account_master_id`,`estado`)";}}s:16:"account_discount";a:4:{s:4:"type";s:5:"TABLE";s:3:"sql";s:368:"CREATE TABLE `account_discount` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `account_cuentas_id` int(18) unsigned NOT NULL,
  `discount_id` int(11) NOT NULL,
  `tipo` char(1) NOT NULL,
  `valor` decimal(10,2) DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `account_cuentas_id` (`account_cuentas_id`),
  KEY `discount_id` (`discount_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8";s:6:"fields";a:5:{s:2:"id";s:38:"  `id` int(11) NOT NULL AUTO_INCREMENT";s:18:"account_cuentas_id";s:48:"  `account_cuentas_id` int(18) unsigned NOT NULL";s:11:"discount_id";s:32:"  `discount_id` int(11) NOT NULL";s:4:"tipo";s:25:"  `tipo` char(1) NOT NULL";s:5:"valor";s:36:"  `valor` decimal(10,2) DEFAULT NULL";}s:7:"indexes";a:2:{s:18:"account_cuentas_id";s:49:"  KEY `account_cuentas_id` (`account_cuentas_id`)";s:11:"discount_id";s:35:"  KEY `discount_id` (`discount_id`)";}}s:12:"account_inve";a:4:{s:4:"type";s:5:"TABLE";s:3:"sql";s:479:"CREATE TABLE `account_inve` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `account_id` int(10) unsigned NOT NULL,
  `codigo` char(7) COLLATE utf8_unicode_ci NOT NULL,
  `cantidad` decimal(10,3) NOT NULL,
  `cantidad_usuario` int(10) unsigned NOT NULL,
  `tipo` char(1) COLLATE utf8_unicode_ci NOT NULL,
  `estado` char(1) COLLATE utf8_unicode_ci NOT NULL,
  PRIMARY KEY (`id`),
  KEY `account_id` (`account_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci";s:6:"fields";a:7:{s:2:"id";s:47:"  `id` int(10) unsigned NOT NULL AUTO_INCREMENT";s:10:"account_id";s:40:"  `account_id` int(10) unsigned NOT NULL";s:6:"codigo";s:51:"  `codigo` char(7) COLLATE utf8_unicode_ci NOT NULL";s:8:"cantidad";s:35:"  `cantidad` decimal(10,3) NOT NULL";s:16:"cantidad_usuario";s:46:"  `cantidad_usuario` int(10) unsigned NOT NULL";s:4:"tipo";s:49:"  `tipo` char(1) COLLATE utf8_unicode_ci NOT NULL";s:6:"estado";s:51:"  `estado` char(1) COLLATE utf8_unicode_ci NOT NULL";}s:7:"indexes";a:1:{s:10:"account_id";s:33:"  KEY `account_id` (`account_id`)";}}s:14:"account_master";a:4:{s:4:"type";s:5:"TABLE";s:3:"sql";s:596:"CREATE TABLE `account_master` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `salon_id` int(11) NOT NULL,
  `salon_mesas_id` int(11) NOT NULL,
  `usuarios_id` int(11) NOT NULL,
  `nombre` char(50) DEFAULT NULL,
  `hora` datetime DEFAULT NULL,
  `hora_atencion` datetime DEFAULT NULL,
  `numero_asientos` int(3) DEFAULT NULL,
  `send_kitchen` char(1) DEFAULT 'N',
  `estado` char(1) NOT NULL DEFAULT '',
  PRIMARY KEY (`id`),
  KEY `salon_id` (`salon_id`),
  KEY `usuarios_id` (`usuarios_id`),
  KEY `salon_mesas_id` (`salon_mesas_id`,`estado`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 ROW_FORMAT=DYNAMIC";s:6:"fields";a:10:{s:2:"id";s:38:"  `id` int(11) NOT NULL AUTO_INCREMENT";s:8:"salon_id";s:29:"  `salon_id` int(11) NOT NULL";s:14:"salon_mesas_id";s:35:"  `salon_mesas_id` int(11) NOT NULL";s:11:"usuarios_id";s:32:"  `usuarios_id` int(11) NOT NULL";s:6:"nombre";s:32:"  `nombre` char(50) DEFAULT NULL";s:4:"hora";s:30:"  `hora` datetime DEFAULT NULL";s:13:"hora_atencion";s:39:"  `hora_atencion` datetime DEFAULT NULL";s:15:"numero_asientos";s:39:"  `numero_asientos` int(3) DEFAULT NULL";s:12:"send_kitchen";s:36:"  `send_kitchen` char(1) DEFAULT 'N'";s:6:"estado";s:38:"  `estado` char(1) NOT NULL DEFAULT ''";}s:7:"indexes";a:3:{s:8:"salon_id";s:29:"  KEY `salon_id` (`salon_id`)";s:11:"usuarios_id";s:35:"  KEY `usuarios_id` (`usuarios_id`)";s:14:"salon_mesas_id";s:50:"  KEY `salon_mesas_id` (`salon_mesas_id`,`estado`)";}}s:17:"account_modifiers";a:4:{s:4:"type";s:5:"TABLE";s:3:"sql";s:329:"CREATE TABLE `account_modifiers` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `account_id` int(18) unsigned NOT NULL,
  `modifiers_id` int(11) NOT NULL DEFAULT '0',
  `valor` decimal(10,2) NOT NULL,
  PRIMARY KEY (`id`),
  KEY `account_id` (`account_id`),
  KEY `modifiers_id` (`modifiers_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8";s:6:"fields";a:4:{s:2:"id";s:38:"  `id` int(11) NOT NULL AUTO_INCREMENT";s:10:"account_id";s:40:"  `account_id` int(18) unsigned NOT NULL";s:12:"modifiers_id";s:45:"  `modifiers_id` int(11) NOT NULL DEFAULT '0'";s:5:"valor";s:32:"  `valor` decimal(10,2) NOT NULL";}s:7:"indexes";a:2:{s:10:"account_id";s:33:"  KEY `account_id` (`account_id`)";s:12:"modifiers_id";s:37:"  KEY `modifiers_id` (`modifiers_id`)";}}s:12:"acompanantes";a:2:{s:4:"type";s:4:"VIEW";s:3:"sql";s:435:"CREATE ALGORITHM=UNDEFINED DEFINER=`root`@`localhost` SQL SECURITY DEFINER VIEW `acompanantes` AS select `hotel2`.`apofol`.`numfol` AS `numfol`,`hotel2`.`apofol`.`numero` AS `numero`,`hotel2`.`apofol`.`tipdoc` AS `tipdoc`,`hotel2`.`apofol`.`cedula` AS `cedula`,`hotel2`.`apofol`.`nombre` AS `nombre`,`hotel2`.`apofol`.`lugexp` AS `lugexp`,`hotel2`.`apofol`.`codpro` AS `codpro`,`hotel2`.`apofol`.`sexo` AS `sexo` from `hotel2`.`apofol`";}s:5:"audit";a:3:{s:4:"type";s:5:"TABLE";s:3:"sql";s:369:"CREATE TABLE `audit` (
  `id` int(18) unsigned NOT NULL AUTO_INCREMENT,
  `controller` varchar(32) NOT NULL,
  `action` varchar(32) NOT NULL,
  `fecha_at` datetime NOT NULL,
  `ipaddress` char(15) NOT NULL,
  `usuarios_id` int(11) NOT NULL,
  `nombre` varchar(120) NOT NULL,
  `nota` text,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 ROW_FORMAT=COMPRESSED";s:6:"fields";a:8:{s:2:"id";s:47:"  `id` int(18) unsigned NOT NULL AUTO_INCREMENT";s:10:"controller";s:35:"  `controller` varchar(32) NOT NULL";s:6:"action";s:31:"  `action` varchar(32) NOT NULL";s:8:"fecha_at";s:30:"  `fecha_at` datetime NOT NULL";s:9:"ipaddress";s:31:"  `ipaddress` char(15) NOT NULL";s:11:"usuarios_id";s:32:"  `usuarios_id` int(11) NOT NULL";s:6:"nombre";s:32:"  `nombre` varchar(120) NOT NULL";s:4:"nota";s:13:"  `nota` text";}}s:12:"cargos_front";a:4:{s:4:"type";s:5:"TABLE";s:3:"sql";s:564:"CREATE TABLE `cargos_front` (
  `id` int(18) unsigned NOT NULL AUTO_INCREMENT,
  `numero_folio` int(18) unsigned NOT NULL,
  `numero_cuenta` int(3) unsigned NOT NULL,
  `item` int(3) unsigned NOT NULL,
  `codigo_cargo` int(11) DEFAULT NULL,
  `prefijo_facturacion` char(5) NOT NULL,
  `numero` int(18) unsigned NOT NULL,
  `es_propina` char(1) NOT NULL,
  `estado` char(1) NOT NULL,
  PRIMARY KEY (`id`),
  KEY `numero_folio` (`numero_folio`,`numero_cuenta`,`item`),
  KEY `prefijo_facturacion` (`prefijo_facturacion`,`numero`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8";s:6:"fields";a:9:{s:2:"id";s:47:"  `id` int(18) unsigned NOT NULL AUTO_INCREMENT";s:12:"numero_folio";s:42:"  `numero_folio` int(18) unsigned NOT NULL";s:13:"numero_cuenta";s:42:"  `numero_cuenta` int(3) unsigned NOT NULL";s:4:"item";s:33:"  `item` int(3) unsigned NOT NULL";s:12:"codigo_cargo";s:37:"  `codigo_cargo` int(11) DEFAULT NULL";s:19:"prefijo_facturacion";s:40:"  `prefijo_facturacion` char(5) NOT NULL";s:6:"numero";s:36:"  `numero` int(18) unsigned NOT NULL";s:10:"es_propina";s:31:"  `es_propina` char(1) NOT NULL";s:6:"estado";s:27:"  `estado` char(1) NOT NULL";}s:7:"indexes";a:2:{s:12:"numero_folio";s:60:"  KEY `numero_folio` (`numero_folio`,`numero_cuenta`,`item`)";s:19:"prefijo_facturacion";s:60:"  KEY `prefijo_facturacion` (`prefijo_facturacion`,`numero`)";}}s:20:"cargos_front_detalle";a:4:{s:4:"type";s:5:"TABLE";s:3:"sql";s:313:"CREATE TABLE `cargos_front_detalle` (
  `id` int(18) unsigned NOT NULL AUTO_INCREMENT,
  `cargos_front_id` int(18) unsigned NOT NULL,
  `account_id` int(18) unsigned NOT NULL,
  PRIMARY KEY (`id`),
  KEY `cargos_front_id` (`cargos_front_id`),
  KEY `account_id` (`account_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8";s:6:"fields";a:3:{s:2:"id";s:47:"  `id` int(18) unsigned NOT NULL AUTO_INCREMENT";s:15:"cargos_front_id";s:45:"  `cargos_front_id` int(18) unsigned NOT NULL";s:10:"account_id";s:40:"  `account_id` int(18) unsigned NOT NULL";}s:7:"indexes";a:2:{s:15:"cargos_front_id";s:43:"  KEY `cargos_front_id` (`cargos_front_id`)";s:10:"account_id";s:33:"  KEY `account_id` (`account_id`)";}}s:10:"cash_money";a:3:{s:4:"type";s:5:"TABLE";s:3:"sql";s:225:"CREATE TABLE `cash_money` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `cash_tray_id` int(11) NOT NULL,
  `cantidad` int(11) NOT NULL,
  `valor` decimal(10,2) NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8";s:6:"fields";a:4:{s:2:"id";s:38:"  `id` int(11) NOT NULL AUTO_INCREMENT";s:12:"cash_tray_id";s:33:"  `cash_tray_id` int(11) NOT NULL";s:8:"cantidad";s:29:"  `cantidad` int(11) NOT NULL";s:5:"valor";s:32:"  `valor` decimal(10,2) NOT NULL";}}s:9:"cash_tray";a:3:{s:4:"type";s:5:"TABLE";s:3:"sql";s:336:"CREATE TABLE `cash_tray` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `descripcion` char(50) NOT NULL,
  `usuarios_id` int(11) DEFAULT NULL,
  `estado` char(1) DEFAULT 'N',
  `fecha` date DEFAULT NULL,
  `hora_abierta` char(8) DEFAULT NULL,
  `hora_cerrada` char(8) DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8";s:6:"fields";a:7:{s:2:"id";s:38:"  `id` int(11) NOT NULL AUTO_INCREMENT";s:11:"descripcion";s:33:"  `descripcion` char(50) NOT NULL";s:11:"usuarios_id";s:36:"  `usuarios_id` int(11) DEFAULT NULL";s:6:"estado";s:30:"  `estado` char(1) DEFAULT 'N'";s:5:"fecha";s:27:"  `fecha` date DEFAULT NULL";s:12:"hora_abierta";s:37:"  `hora_abierta` char(8) DEFAULT NULL";s:12:"hora_cerrada";s:37:"  `hora_cerrada` char(8) DEFAULT NULL";}}s:8:"clientes";a:2:{s:4:"type";s:4:"VIEW";s:3:"sql";s:381:"CREATE ALGORITHM=UNDEFINED DEFINER=`root`@`localhost` SQL SECURITY DEFINER VIEW `clientes` AS select `c`.`cedula` AS `id`,`c`.`nombre` AS `nombre`,`c`.`direccion` AS `direccion`,`c`.`telefono1` AS `telefono` from `hotel2`.`clientes` `c` union select `e`.`nit` AS `id`,`e`.`nombre` AS `nombre`,`e`.`direccion` AS `direccion`,`e`.`telefono` AS `telefono` from `hotel2`.`empresas` `e`";}s:9:"conceptos";a:2:{s:4:"type";s:4:"VIEW";s:3:"sql";s:345:"CREATE ALGORITHM=UNDEFINED DEFINER=`root`@`localhost` SQL SECURITY DEFINER VIEW `conceptos` AS select `hotel2`.`cargos`.`codcar` AS `id`,`hotel2`.`cargos`.`descripcion` AS `descripcion` from `hotel2`.`cargos` where ((`hotel2`.`cargos`.`tipmov` = _utf8'D') and (`hotel2`.`cargos`.`descaj` <> _utf8'S') and (`hotel2`.`cargos`.`estado` = _utf8'A'))";}s:21:"conceptos_cancelacion";a:3:{s:4:"type";s:5:"TABLE";s:3:"sql";s:170:"CREATE TABLE `conceptos_cancelacion` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `nombre` varchar(100) NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8";s:6:"fields";a:2:{s:2:"id";s:38:"  `id` int(11) NOT NULL AUTO_INCREMENT";s:6:"nombre";s:32:"  `nombre` varchar(100) NOT NULL";}}s:7:"cuentas";a:2:{s:4:"type";s:4:"VIEW";s:3:"sql";s:492:"CREATE ALGORITHM=UNDEFINED DEFINER=`root`@`localhost` SQL SECURITY DEFINER VIEW `cuentas` AS select `f`.`numfol` AS `numfol`,`c`.`numcue` AS `numcue`,`t`.`detalle` AS `nombre`,`f`.`numhab` AS `habitacion_id`,`c`.`estado` AS `estado` from ((`hotel2`.`carghab` `c` join `hotel2`.`folio` `f`) join `hotel2`.`tipcue` `t`) where ((`f`.`numfol` = `c`.`numfol`) and (`f`.`estado` in (_utf8'I',_utf8'C',_utf8'F')) and (`c`.`numcue` = `t`.`numcue`) and (`c`.`estado` = _utf8'N')) order by `f`.`numhab`";}s:9:"customers";a:3:{s:4:"type";s:5:"TABLE";s:3:"sql";s:278:"CREATE TABLE `customers` (
  `identification_type` char(3) NOT NULL DEFAULT '',
  `number` varchar(40) NOT NULL DEFAULT '',
  `nombre` varchar(120) DEFAULT NULL,
  `status` char(1) DEFAULT NULL,
  PRIMARY KEY (`identification_type`,`number`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8";s:6:"fields";a:4:{s:19:"identification_type";s:51:"  `identification_type` char(3) NOT NULL DEFAULT ''";s:6:"number";s:42:"  `number` varchar(40) NOT NULL DEFAULT ''";s:6:"nombre";s:36:"  `nombre` varchar(120) DEFAULT NULL";s:6:"status";s:31:"  `status` char(1) DEFAULT NULL";}}s:5:"datos";a:3:{s:4:"type";s:5:"TABLE";s:3:"sql";s:730:"CREATE TABLE `datos` (
  `id` int(11) NOT NULL,
  `documento` char(10) NOT NULL,
  `nit` char(13) NOT NULL,
  `nombre_hotel` char(50) NOT NULL,
  `nombre_cadena` char(50) NOT NULL,
  `direccion` char(70) NOT NULL DEFAULT '',
  `telefonos` char(40) NOT NULL DEFAULT '',
  `fax` char(30) NOT NULL,
  `po_box` char(30) NOT NULL,
  `ciudad` char(40) NOT NULL,
  `pais` char(30) NOT NULL,
  `entidad` char(10) NOT NULL,
  `moneda` char(15) NOT NULL,
  `centavos` char(15) NOT NULL,
  `nota_contribuyentes` varchar(80) NOT NULL DEFAULT '',
  `fecha` date NOT NULL,
  `print_type` char(1) DEFAULT NULL,
  `print_server` varchar(15) DEFAULT NULL,
  `version` varchar(10) NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8";s:6:"fields";a:19:{s:2:"id";s:23:"  `id` int(11) NOT NULL";s:9:"documento";s:31:"  `documento` char(10) NOT NULL";s:3:"nit";s:25:"  `nit` char(13) NOT NULL";s:12:"nombre_hotel";s:34:"  `nombre_hotel` char(50) NOT NULL";s:13:"nombre_cadena";s:35:"  `nombre_cadena` char(50) NOT NULL";s:9:"direccion";s:42:"  `direccion` char(70) NOT NULL DEFAULT ''";s:9:"telefonos";s:42:"  `telefonos` char(40) NOT NULL DEFAULT ''";s:3:"fax";s:25:"  `fax` char(30) NOT NULL";s:6:"po_box";s:28:"  `po_box` char(30) NOT NULL";s:6:"ciudad";s:28:"  `ciudad` char(40) NOT NULL";s:4:"pais";s:26:"  `pais` char(30) NOT NULL";s:7:"entidad";s:29:"  `entidad` char(10) NOT NULL";s:6:"moneda";s:28:"  `moneda` char(15) NOT NULL";s:8:"centavos";s:30:"  `centavos` char(15) NOT NULL";s:19:"nota_contribuyentes";s:55:"  `nota_contribuyentes` varchar(80) NOT NULL DEFAULT ''";s:5:"fecha";s:23:"  `fecha` date NOT NULL";s:10:"print_type";s:35:"  `print_type` char(1) DEFAULT NULL";s:12:"print_server";s:41:"  `print_server` varchar(15) DEFAULT NULL";s:7:"version";s:32:"  `version` varchar(10) NOT NULL";}}s:15:"detalle_factura";a:4:{s:4:"type";s:5:"TABLE";s:3:"sql";s:936:"CREATE TABLE `detalle_factura` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `prefijo_facturacion` char(12) NOT NULL DEFAULT '',
  `consecutivo_facturacion` int(11) NOT NULL DEFAULT '0',
  `tipo` char(1) NOT NULL DEFAULT '',
  `account_id` int(10) unsigned NOT NULL,
  `menus_items_id` int(11) NOT NULL DEFAULT '0',
  `menus_items_nombre` text NOT NULL,
  `porcentaje_iva` int(3) NOT NULL,
  `porcentaje_impoconsumo` int(3) DEFAULT '0',
  `cantidad` int(11) NOT NULL DEFAULT '0',
  `descuento` int(3) NOT NULL,
  `valor` decimal(10,2) NOT NULL DEFAULT '0.00',
  `iva` decimal(10,2) NOT NULL,
  `impo` decimal(10,2) DEFAULT '0.00',
  `servicio` decimal(10,2) NOT NULL,
  `total` decimal(10,2) NOT NULL DEFAULT '0.00',
  PRIMARY KEY (`id`),
  KEY `prefijo_facturacion` (`prefijo_facturacion`,`consecutivo_facturacion`,`tipo`),
  KEY `account_id` (`account_id`),
  KEY `menus_items_id` (`menus_items_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8";s:6:"fields";a:16:{s:2:"id";s:38:"  `id` int(11) NOT NULL AUTO_INCREMENT";s:19:"prefijo_facturacion";s:52:"  `prefijo_facturacion` char(12) NOT NULL DEFAULT ''";s:23:"consecutivo_facturacion";s:56:"  `consecutivo_facturacion` int(11) NOT NULL DEFAULT '0'";s:4:"tipo";s:36:"  `tipo` char(1) NOT NULL DEFAULT ''";s:10:"account_id";s:40:"  `account_id` int(10) unsigned NOT NULL";s:14:"menus_items_id";s:47:"  `menus_items_id` int(11) NOT NULL DEFAULT '0'";s:18:"menus_items_nombre";s:36:"  `menus_items_nombre` text NOT NULL";s:14:"porcentaje_iva";s:34:"  `porcentaje_iva` int(3) NOT NULL";s:22:"porcentaje_impoconsumo";s:45:"  `porcentaje_impoconsumo` int(3) DEFAULT '0'";s:8:"cantidad";s:41:"  `cantidad` int(11) NOT NULL DEFAULT '0'";s:9:"descuento";s:29:"  `descuento` int(3) NOT NULL";s:5:"valor";s:47:"  `valor` decimal(10,2) NOT NULL DEFAULT '0.00'";s:3:"iva";s:30:"  `iva` decimal(10,2) NOT NULL";s:4:"impo";s:37:"  `impo` decimal(10,2) DEFAULT '0.00'";s:8:"servicio";s:35:"  `servicio` decimal(10,2) NOT NULL";s:5:"total";s:47:"  `total` decimal(10,2) NOT NULL DEFAULT '0.00'";}s:7:"indexes";a:3:{s:19:"prefijo_facturacion";s:84:"  KEY `prefijo_facturacion` (`prefijo_facturacion`,`consecutivo_facturacion`,`tipo`)";s:10:"account_id";s:33:"  KEY `account_id` (`account_id`)";s:14:"menus_items_id";s:41:"  KEY `menus_items_id` (`menus_items_id`)";}}s:8:"discount";a:4:{s:4:"type";s:5:"TABLE";s:3:"sql";s:273:"CREATE TABLE `discount` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `nombre` char(40) NOT NULL,
  `tipo` char(1) NOT NULL,
  `valor` decimal(10,2) NOT NULL,
  `estado` char(1) DEFAULT 'A',
  PRIMARY KEY (`id`),
  KEY `estado` (`estado`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8";s:6:"fields";a:5:{s:2:"id";s:38:"  `id` int(11) NOT NULL AUTO_INCREMENT";s:6:"nombre";s:28:"  `nombre` char(40) NOT NULL";s:4:"tipo";s:25:"  `tipo` char(1) NOT NULL";s:5:"valor";s:32:"  `valor` decimal(10,2) NOT NULL";s:6:"estado";s:30:"  `estado` char(1) DEFAULT 'A'";}s:7:"indexes";a:1:{s:6:"estado";s:25:"  KEY `estado` (`estado`)";}}s:8:"empresa1";a:2:{s:4:"type";s:4:"VIEW";s:3:"sql";s:348:"CREATE ALGORITHM=UNDEFINED DEFINER=`root`@`localhost` SQL SECURITY DEFINER VIEW `empresa1` AS select `ramocol`.`empresa1`.`f_cierref` AS `f_cierref`,`ramocol`.`empresa1`.`f_cierrep` AS `f_cierrep`,`ramocol`.`empresa1`.`ano_c` AS `ano_c`,`ramocol`.`empresa1`.`base_ret` AS `base_ret`,`ramocol`.`empresa1`.`otros` AS `otros` from `ramocol`.`empresa1`";}s:7:"factura";a:4:{s:4:"type";s:5:"TABLE";s:3:"sql";s:2473:"CREATE TABLE `factura` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `prefijo_facturacion` char(12) DEFAULT NULL,
  `consecutivo_facturacion` int(11) NOT NULL DEFAULT '0',
  `resolucion` varchar(30) NOT NULL,
  `fecha_resolucion` date NOT NULL,
  `numero_inicial` int(10) unsigned NOT NULL,
  `numero_final` int(10) unsigned NOT NULL,
  `account_master_id` int(11) DEFAULT NULL,
  `cuenta` int(3) unsigned NOT NULL,
  `comanda` varchar(120) NOT NULL,
  `documento` char(10) NOT NULL DEFAULT '',
  `nit` char(13) NOT NULL DEFAULT '',
  `nombre_hotel` char(50) NOT NULL DEFAULT '',
  `nombre_cadena` char(50) NOT NULL DEFAULT '',
  `direccion` char(70) NOT NULL DEFAULT '',
  `telefonos` char(40) NOT NULL DEFAULT '',
  `fax` char(30) NOT NULL DEFAULT '',
  `po_box` char(30) NOT NULL DEFAULT '',
  `ciudad` char(40) NOT NULL DEFAULT '',
  `pais` char(30) NOT NULL DEFAULT '',
  `entidad` char(10) NOT NULL DEFAULT '',
  `moneda` char(15) NOT NULL DEFAULT '',
  `centavos` char(15) NOT NULL DEFAULT '',
  `nota_contribuyentes` varchar(300) NOT NULL DEFAULT '',
  `cedula` char(13) NOT NULL DEFAULT '',
  `nombre` char(60) NOT NULL DEFAULT '',
  `clientes_direccion` char(60) DEFAULT NULL,
  `clientes_telefono` char(30) DEFAULT NULL,
  `habitacion_id` int(11) NOT NULL,
  `habitacion_numero` varchar(6) NOT NULL,
  `salon_id` int(11) DEFAULT NULL,
  `salon_nombre` char(40) NOT NULL DEFAULT '',
  `salonmesas_numero` varchar(5) NOT NULL,
  `numero_personas` int(10) unsigned DEFAULT '1',
  `usuarios_id` int(11) DEFAULT NULL,
  `usuarios_nombre` char(30) NOT NULL DEFAULT '',
  `fecha` date NOT NULL,
  `hora` char(5) NOT NULL,
  `tipo` char(1) NOT NULL DEFAULT '',
  `tipo_venta` char(1) DEFAULT NULL,
  `leyenda_propina` char(1) NOT NULL DEFAULT 'N',
  `texto_propina` text,
  `texto_impresion` text,
  `propina` decimal(10,2) DEFAULT NULL,
  `total_alimentos` decimal(10,2) NOT NULL,
  `total_bebidas` decimal(10,2) NOT NULL,
  `subtotal` decimal(10,2) NOT NULL,
  `total` decimal(10,2) NOT NULL DEFAULT '0.00',
  `total_iva` decimal(10,2) NOT NULL DEFAULT '0.00',
  `total_impoconsumo` decimal(10,2) DEFAULT '0.00',
  `total_servicio` decimal(10,2) NOT NULL DEFAULT '0.00',
  `estado` char(1) NOT NULL DEFAULT '',
  PRIMARY KEY (`id`),
  KEY `salon_id` (`salon_id`),
  KEY `prefijo_facturacion` (`prefijo_facturacion`,`consecutivo_facturacion`,`tipo`),
  KEY `estado` (`estado`),
  KEY `account_master_id` (`account_master_id`,`cuenta`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8";s:6:"fields";a:52:{s:2:"id";s:38:"  `id` int(11) NOT NULL AUTO_INCREMENT";s:19:"prefijo_facturacion";s:45:"  `prefijo_facturacion` char(12) DEFAULT NULL";s:23:"consecutivo_facturacion";s:56:"  `consecutivo_facturacion` int(11) NOT NULL DEFAULT '0'";s:10:"resolucion";s:35:"  `resolucion` varchar(30) NOT NULL";s:16:"fecha_resolucion";s:34:"  `fecha_resolucion` date NOT NULL";s:14:"numero_inicial";s:44:"  `numero_inicial` int(10) unsigned NOT NULL";s:12:"numero_final";s:42:"  `numero_final` int(10) unsigned NOT NULL";s:17:"account_master_id";s:42:"  `account_master_id` int(11) DEFAULT NULL";s:6:"cuenta";s:35:"  `cuenta` int(3) unsigned NOT NULL";s:7:"comanda";s:33:"  `comanda` varchar(120) NOT NULL";s:9:"documento";s:42:"  `documento` char(10) NOT NULL DEFAULT ''";s:3:"nit";s:36:"  `nit` char(13) NOT NULL DEFAULT ''";s:12:"nombre_hotel";s:45:"  `nombre_hotel` char(50) NOT NULL DEFAULT ''";s:13:"nombre_cadena";s:46:"  `nombre_cadena` char(50) NOT NULL DEFAULT ''";s:9:"direccion";s:42:"  `direccion` char(70) NOT NULL DEFAULT ''";s:9:"telefonos";s:42:"  `telefonos` char(40) NOT NULL DEFAULT ''";s:3:"fax";s:36:"  `fax` char(30) NOT NULL DEFAULT ''";s:6:"po_box";s:39:"  `po_box` char(30) NOT NULL DEFAULT ''";s:6:"ciudad";s:39:"  `ciudad` char(40) NOT NULL DEFAULT ''";s:4:"pais";s:37:"  `pais` char(30) NOT NULL DEFAULT ''";s:7:"entidad";s:40:"  `entidad` char(10) NOT NULL DEFAULT ''";s:6:"moneda";s:39:"  `moneda` char(15) NOT NULL DEFAULT ''";s:8:"centavos";s:41:"  `centavos` char(15) NOT NULL DEFAULT ''";s:19:"nota_contribuyentes";s:56:"  `nota_contribuyentes` varchar(300) NOT NULL DEFAULT ''";s:6:"cedula";s:39:"  `cedula` char(13) NOT NULL DEFAULT ''";s:6:"nombre";s:39:"  `nombre` char(60) NOT NULL DEFAULT ''";s:18:"clientes_direccion";s:44:"  `clientes_direccion` char(60) DEFAULT NULL";s:17:"clientes_telefono";s:43:"  `clientes_telefono` char(30) DEFAULT NULL";s:13:"habitacion_id";s:34:"  `habitacion_id` int(11) NOT NULL";s:17:"habitacion_numero";s:41:"  `habitacion_numero` varchar(6) NOT NULL";s:8:"salon_id";s:33:"  `salon_id` int(11) DEFAULT NULL";s:12:"salon_nombre";s:45:"  `salon_nombre` char(40) NOT NULL DEFAULT ''";s:17:"salonmesas_numero";s:41:"  `salonmesas_numero` varchar(5) NOT NULL";s:15:"numero_personas";s:48:"  `numero_personas` int(10) unsigned DEFAULT '1'";s:11:"usuarios_id";s:36:"  `usuarios_id` int(11) DEFAULT NULL";s:15:"usuarios_nombre";s:48:"  `usuarios_nombre` char(30) NOT NULL DEFAULT ''";s:5:"fecha";s:23:"  `fecha` date NOT NULL";s:4:"hora";s:25:"  `hora` char(5) NOT NULL";s:4:"tipo";s:36:"  `tipo` char(1) NOT NULL DEFAULT ''";s:10:"tipo_venta";s:35:"  `tipo_venta` char(1) DEFAULT NULL";s:15:"leyenda_propina";s:48:"  `leyenda_propina` char(1) NOT NULL DEFAULT 'N'";s:13:"texto_propina";s:22:"  `texto_propina` text";s:15:"texto_impresion";s:24:"  `texto_impresion` text";s:7:"propina";s:38:"  `propina` decimal(10,2) DEFAULT NULL";s:15:"total_alimentos";s:42:"  `total_alimentos` decimal(10,2) NOT NULL";s:13:"total_bebidas";s:40:"  `total_bebidas` decimal(10,2) NOT NULL";s:8:"subtotal";s:35:"  `subtotal` decimal(10,2) NOT NULL";s:5:"total";s:47:"  `total` decimal(10,2) NOT NULL DEFAULT '0.00'";s:9:"total_iva";s:51:"  `total_iva` decimal(10,2) NOT NULL DEFAULT '0.00'";s:17:"total_impoconsumo";s:50:"  `total_impoconsumo` decimal(10,2) DEFAULT '0.00'";s:14:"total_servicio";s:56:"  `total_servicio` decimal(10,2) NOT NULL DEFAULT '0.00'";s:6:"estado";s:38:"  `estado` char(1) NOT NULL DEFAULT ''";}s:7:"indexes";a:4:{s:8:"salon_id";s:29:"  KEY `salon_id` (`salon_id`)";s:19:"prefijo_facturacion";s:84:"  KEY `prefijo_facturacion` (`prefijo_facturacion`,`consecutivo_facturacion`,`tipo`)";s:6:"estado";s:25:"  KEY `estado` (`estado`)";s:17:"account_master_id";s:56:"  KEY `account_master_id` (`account_master_id`,`cuenta`)";}}s:11:"formas_pago";a:2:{s:4:"type";s:4:"VIEW";s:3:"sql";s:202:"CREATE ALGORITHM=UNDEFINED DEFINER=`root`@`localhost` SQL SECURITY DEFINER VIEW `formas_pago` AS select `hotel2`.`forpag`.`forpag` AS `id`,`hotel2`.`forpag`.`detalle` AS `detalle` from `hotel2`.`forpag`";}s:10:"habitacion";a:2:{s:4:"type";s:4:"VIEW";s:3:"sql";s:1060:"CREATE ALGORITHM=UNDEFINED DEFINER=`root`@`localhost` SQL SECURITY DEFINER VIEW `habitacion` AS select `hotel2`.`folio`.`numfol` AS `id`,`hotel2`.`clientes`.`tipdoc` AS `tipdoc`,if((`hotel2`.`folio`.`cedula` = _utf8'0'),`hotel2`.`folio`.`nit`,`hotel2`.`folio`.`cedula`) AS `cedula`,if((`hotel2`.`folio`.`cedula` = _utf8'0'),`hotel2`.`empresas`.`nombre`,`hotel2`.`clientes`.`nombre`) AS `nombre`,`hotel2`.`folio`.`nit` AS `nit`,`hotel2`.`folio`.`numhab` AS `numhab`,`hotel2`.`folio`.`numadu` AS `numero_adultos`,`hotel2`.`folio`.`numnin` AS `numero_ninos`,`hotel2`.`folio`.`numinf` AS `numero_infantes`,`hotel2`.`folio`.`notaayb` AS `nota` from ((`hotel2`.`folio` join `hotel2`.`clientes`) join `hotel2`.`empresas`) where ((`hotel2`.`folio`.`cedula` = `hotel2`.`clientes`.`cedula`) and (`hotel2`.`folio`.`nit` = `hotel2`.`empresas`.`nit`) and (`hotel2`.`folio`.`estado` in (_utf8'I',_utf8'F')) and (`hotel2`.`folio`.`corregir` = _utf8'N')) order by concat(convert(repeat(_latin1' ',(6 - length(`hotel2`.`folio`.`numhab`))) using utf8),`hotel2`.`folio`.`numhab`)";}s:20:"habitacion_historico";a:2:{s:4:"type";s:4:"VIEW";s:3:"sql";s:917:"CREATE ALGORITHM=UNDEFINED DEFINER=`root`@`localhost` SQL SECURITY DEFINER VIEW `habitacion_historico` AS select `hotel2`.`folio`.`numfol` AS `id`,`hotel2`.`tipdoc`.`tipcoa` AS `tipdoc`,if((`hotel2`.`clientes`.`cedula` <> _utf8'0'),`hotel2`.`clientes`.`cedula`,`hotel2`.`empresas`.`nit`) AS `cedula`,if((`hotel2`.`clientes`.`cedula` <> _utf8'0'),`hotel2`.`clientes`.`nombre`,`hotel2`.`empresas`.`nombre`) AS `nombre`,`hotel2`.`folio`.`numhab` AS `numhab`,`hotel2`.`folio`.`numadu` AS `numero_adultos`,`hotel2`.`folio`.`numnin` AS `numero_ninos`,`hotel2`.`folio`.`numinf` AS `numero_infantes`,`hotel2`.`folio`.`notaayb` AS `nota` from (((`hotel2`.`folio` join `hotel2`.`clientes`) join `hotel2`.`empresas`) join `hotel2`.`tipdoc`) where ((`hotel2`.`tipdoc`.`tipdoc` = `hotel2`.`clientes`.`tipdoc`) and (`hotel2`.`clientes`.`cedula` = `hotel2`.`folio`.`cedula`) and (`hotel2`.`empresas`.`nit` = `hotel2`.`folio`.`nit`))";}s:12:"habitaciones";a:2:{s:4:"type";s:4:"VIEW";s:3:"sql";s:398:"CREATE ALGORITHM=UNDEFINED DEFINER=`root`@`localhost` SQL SECURITY DEFINER VIEW `habitaciones` AS select `hotel2`.`habitacion`.`numhab` AS `id`,`hotel2`.`clahab`.`clase` AS `clase`,`hotel2`.`habitacion`.`piso` AS `piso` from (`hotel2`.`habitacion` join `hotel2`.`clahab`) where ((`hotel2`.`habitacion`.`codcla` = `hotel2`.`clahab`.`codcla`) and (`hotel2`.`habitacion`.`tipo` = _utf8'V')) order by 1";}s:7:"invepos";a:3:{s:4:"type";s:5:"TABLE";s:3:"sql";s:519:"CREATE TABLE `invepos` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `prefac` char(5) NOT NULL,
  `numfac` int(10) unsigned NOT NULL,
  `fecha` date NOT NULL,
  `almacen` int(10) unsigned NOT NULL,
  `centro_costo` int(10) unsigned NOT NULL,
  `tipo` char(1) NOT NULL,
  `codigo` char(15) NOT NULL,
  `menus_items_id` int(10) unsigned NOT NULL,
  `cantidad` int(10) unsigned NOT NULL,
  `cantidadu` int(10) unsigned NOT NULL,
  `estado` char(1) NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8";s:6:"fields";a:12:{s:2:"id";s:47:"  `id` int(10) unsigned NOT NULL AUTO_INCREMENT";s:6:"prefac";s:27:"  `prefac` char(5) NOT NULL";s:6:"numfac";s:36:"  `numfac` int(10) unsigned NOT NULL";s:5:"fecha";s:23:"  `fecha` date NOT NULL";s:7:"almacen";s:37:"  `almacen` int(10) unsigned NOT NULL";s:12:"centro_costo";s:42:"  `centro_costo` int(10) unsigned NOT NULL";s:4:"tipo";s:25:"  `tipo` char(1) NOT NULL";s:6:"codigo";s:28:"  `codigo` char(15) NOT NULL";s:14:"menus_items_id";s:44:"  `menus_items_id` int(10) unsigned NOT NULL";s:8:"cantidad";s:38:"  `cantidad` int(10) unsigned NOT NULL";s:9:"cantidadu";s:39:"  `cantidadu` int(10) unsigned NOT NULL";s:6:"estado";s:27:"  `estado` char(1) NOT NULL";}}s:5:"menus";a:4:{s:4:"type";s:5:"TABLE";s:3:"sql";s:314:"CREATE TABLE `menus` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `nombre` varchar(45) NOT NULL,
  `nombre_pedido` varchar(45) NOT NULL,
  `image` varchar(40) DEFAULT NULL,
  `estado` char(1) NOT NULL DEFAULT 'A',
  PRIMARY KEY (`id`),
  KEY `estado` (`estado`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 ROW_FORMAT=FIXED";s:6:"fields";a:5:{s:2:"id";s:38:"  `id` int(11) NOT NULL AUTO_INCREMENT";s:6:"nombre";s:31:"  `nombre` varchar(45) NOT NULL";s:13:"nombre_pedido";s:38:"  `nombre_pedido` varchar(45) NOT NULL";s:5:"image";s:34:"  `image` varchar(40) DEFAULT NULL";s:6:"estado";s:39:"  `estado` char(1) NOT NULL DEFAULT 'A'";}s:7:"indexes";a:1:{s:6:"estado";s:25:"  KEY `estado` (`estado`)";}}s:11:"menus_items";a:4:{s:4:"type";s:5:"TABLE";s:3:"sql";s:895:"CREATE TABLE `menus_items` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `menus_id` int(11) NOT NULL,
  `nombre` varchar(45) NOT NULL,
  `nombre_pedido` varchar(45) NOT NULL,
  `tipo` char(1) DEFAULT NULL,
  `image` char(40) DEFAULT NULL,
  `valor` decimal(16,2) DEFAULT NULL,
  `costo` decimal(7,2) DEFAULT NULL,
  `porcentaje_iva` decimal(5,2) DEFAULT NULL,
  `porcentaje_impoconsumo` decimal(5,2) DEFAULT '0.00',
  `porcentaje_servicio` decimal(5,2) DEFAULT NULL,
  `tipo_costo` char(1) NOT NULL DEFAULT 'N',
  `codigo_referencia` char(15) DEFAULT NULL,
  `descontar` char(1) NOT NULL DEFAULT 'N',
  `cambio_precio` char(1) DEFAULT NULL,
  `estado` char(1) NOT NULL DEFAULT 'A',
  `cubierto` char(1) DEFAULT 'N',
  PRIMARY KEY (`id`),
  KEY `estado` (`estado`),
  KEY `menus_id` (`menus_id`),
  KEY `codigo_referencia` (`codigo_referencia`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 ROW_FORMAT=FIXED";s:6:"fields";a:17:{s:2:"id";s:38:"  `id` int(11) NOT NULL AUTO_INCREMENT";s:8:"menus_id";s:29:"  `menus_id` int(11) NOT NULL";s:6:"nombre";s:31:"  `nombre` varchar(45) NOT NULL";s:13:"nombre_pedido";s:38:"  `nombre_pedido` varchar(45) NOT NULL";s:4:"tipo";s:29:"  `tipo` char(1) DEFAULT NULL";s:5:"image";s:31:"  `image` char(40) DEFAULT NULL";s:5:"valor";s:36:"  `valor` decimal(16,2) DEFAULT NULL";s:5:"costo";s:35:"  `costo` decimal(7,2) DEFAULT NULL";s:14:"porcentaje_iva";s:44:"  `porcentaje_iva` decimal(5,2) DEFAULT NULL";s:22:"porcentaje_impoconsumo";s:54:"  `porcentaje_impoconsumo` decimal(5,2) DEFAULT '0.00'";s:19:"porcentaje_servicio";s:49:"  `porcentaje_servicio` decimal(5,2) DEFAULT NULL";s:10:"tipo_costo";s:43:"  `tipo_costo` char(1) NOT NULL DEFAULT 'N'";s:17:"codigo_referencia";s:43:"  `codigo_referencia` char(15) DEFAULT NULL";s:9:"descontar";s:42:"  `descontar` char(1) NOT NULL DEFAULT 'N'";s:13:"cambio_precio";s:38:"  `cambio_precio` char(1) DEFAULT NULL";s:6:"estado";s:39:"  `estado` char(1) NOT NULL DEFAULT 'A'";s:8:"cubierto";s:32:"  `cubierto` char(1) DEFAULT 'N'";}s:7:"indexes";a:3:{s:6:"estado";s:25:"  KEY `estado` (`estado`)";s:8:"menus_id";s:29:"  KEY `menus_id` (`menus_id`)";s:17:"codigo_referencia";s:47:"  KEY `codigo_referencia` (`codigo_referencia`)";}}s:15:"menus_items_day";a:3:{s:4:"type";s:5:"TABLE";s:3:"sql";s:225:"CREATE TABLE `menus_items_day` (
  `id` int(18) unsigned NOT NULL AUTO_INCREMENT,
  `salon_id` int(18) unsigned NOT NULL,
  `menus_items_id` int(18) unsigned NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8";s:6:"fields";a:3:{s:2:"id";s:47:"  `id` int(18) unsigned NOT NULL AUTO_INCREMENT";s:8:"salon_id";s:38:"  `salon_id` int(18) unsigned NOT NULL";s:14:"menus_items_id";s:44:"  `menus_items_id` int(18) unsigned NOT NULL";}}s:21:"menus_items_modifiers";a:4:{s:4:"type";s:5:"TABLE";s:3:"sql";s:308:"CREATE TABLE `menus_items_modifiers` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `menus_items_id` int(18) unsigned NOT NULL,
  `modifiers_id` int(18) unsigned NOT NULL,
  PRIMARY KEY (`id`),
  KEY `menus_items_id` (`menus_items_id`),
  KEY `modifiers_id` (`modifiers_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8";s:6:"fields";a:3:{s:2:"id";s:38:"  `id` int(11) NOT NULL AUTO_INCREMENT";s:14:"menus_items_id";s:44:"  `menus_items_id` int(18) unsigned NOT NULL";s:12:"modifiers_id";s:42:"  `modifiers_id` int(18) unsigned NOT NULL";}s:7:"indexes";a:2:{s:14:"menus_items_id";s:41:"  KEY `menus_items_id` (`menus_items_id`)";s:12:"modifiers_id";s:37:"  KEY `modifiers_id` (`modifiers_id`)";}}s:9:"modifiers";a:3:{s:4:"type";s:5:"TABLE";s:3:"sql";s:410:"CREATE TABLE `modifiers` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `nombre` varchar(45) NOT NULL,
  `nombre_pedido` varchar(45) NOT NULL,
  `tipo` char(1) NOT NULL,
  `valor` decimal(10,2) DEFAULT NULL,
  `tipo_costo` char(1) DEFAULT 'N',
  `descontar` char(1) DEFAULT 'N',
  `codigo_referencia` char(15) DEFAULT NULL,
  `estado` char(1) DEFAULT 'A',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8";s:6:"fields";a:9:{s:2:"id";s:38:"  `id` int(11) NOT NULL AUTO_INCREMENT";s:6:"nombre";s:31:"  `nombre` varchar(45) NOT NULL";s:13:"nombre_pedido";s:38:"  `nombre_pedido` varchar(45) NOT NULL";s:4:"tipo";s:25:"  `tipo` char(1) NOT NULL";s:5:"valor";s:36:"  `valor` decimal(10,2) DEFAULT NULL";s:10:"tipo_costo";s:34:"  `tipo_costo` char(1) DEFAULT 'N'";s:9:"descontar";s:33:"  `descontar` char(1) DEFAULT 'N'";s:17:"codigo_referencia";s:43:"  `codigo_referencia` char(15) DEFAULT NULL";s:6:"estado";s:30:"  `estado` char(1) DEFAULT 'A'";}}s:16:"movimiento_folio";a:2:{s:4:"type";s:4:"VIEW";s:3:"sql";s:280:"CREATE ALGORITHM=UNDEFINED DEFINER=`root`@`localhost` SQL SECURITY DEFINER VIEW `movimiento_folio` AS select `hotel2`.`valcar`.`numfol` AS `folio`,`hotel2`.`valcar`.`numcue` AS `cuenta`,(max(`hotel2`.`valcar`.`item`) + 1) AS `item` from `hotel2`.`valcar` group by 1,2 order by 1,2";}s:13:"pagos_factura";a:4:{s:4:"type";s:5:"TABLE";s:3:"sql";s:542:"CREATE TABLE `pagos_factura` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `prefijo_facturacion` char(5) DEFAULT NULL,
  `consecutivo_facturacion` int(11) DEFAULT NULL,
  `tipo` char(1) NOT NULL,
  `formas_pago_id` int(11) DEFAULT NULL,
  `pago` decimal(16,2) DEFAULT NULL,
  `cargo_plan` char(1) DEFAULT NULL,
  `habitacion_id` int(11) DEFAULT NULL,
  `cuenta` int(11) DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `prefijo_facturacion` (`prefijo_facturacion`,`consecutivo_facturacion`,`tipo`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 ROW_FORMAT=FIXED";s:6:"fields";a:9:{s:2:"id";s:38:"  `id` int(11) NOT NULL AUTO_INCREMENT";s:19:"prefijo_facturacion";s:44:"  `prefijo_facturacion` char(5) DEFAULT NULL";s:23:"consecutivo_facturacion";s:48:"  `consecutivo_facturacion` int(11) DEFAULT NULL";s:4:"tipo";s:25:"  `tipo` char(1) NOT NULL";s:14:"formas_pago_id";s:39:"  `formas_pago_id` int(11) DEFAULT NULL";s:4:"pago";s:35:"  `pago` decimal(16,2) DEFAULT NULL";s:10:"cargo_plan";s:35:"  `cargo_plan` char(1) DEFAULT NULL";s:13:"habitacion_id";s:38:"  `habitacion_id` int(11) DEFAULT NULL";s:6:"cuenta";s:31:"  `cuenta` int(11) DEFAULT NULL";}s:7:"indexes";a:1:{s:19:"prefijo_facturacion";s:84:"  KEY `prefijo_facturacion` (`prefijo_facturacion`,`consecutivo_facturacion`,`tipo`)";}}s:8:"permisos";a:4:{s:4:"type";s:5:"TABLE";s:3:"sql";s:333:"CREATE TABLE `permisos` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `usuarios_id` int(11) DEFAULT NULL,
  `salon_id` int(11) DEFAULT NULL,
  `estado` char(1) DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `salon_id` (`salon_id`),
  KEY `salon_id_2` (`salon_id`,`usuarios_id`,`estado`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 ROW_FORMAT=FIXED";s:6:"fields";a:4:{s:2:"id";s:38:"  `id` int(11) NOT NULL AUTO_INCREMENT";s:11:"usuarios_id";s:36:"  `usuarios_id` int(11) DEFAULT NULL";s:8:"salon_id";s:33:"  `salon_id` int(11) DEFAULT NULL";s:6:"estado";s:31:"  `estado` char(1) DEFAULT NULL";}s:7:"indexes";a:2:{s:8:"salon_id";s:29:"  KEY `salon_id` (`salon_id`)";s:10:"salon_id_2";s:54:"  KEY `salon_id_2` (`salon_id`,`usuarios_id`,`estado`)";}}s:6:"planes";a:2:{s:4:"type";s:4:"VIEW";s:3:"sql";s:376:"CREATE ALGORITHM=UNDEFINED DEFINER=`root`@`localhost` SQL SECURITY DEFINER VIEW `planes` AS select `hotel2`.`plafol`.`numfol` AS `numfol`,`hotel2`.`planes`.`descripcion` AS `descripcion`,`hotel2`.`plafol`.`fecini` AS `fecini`,`hotel2`.`plafol`.`fecfin` AS `fecfin` from (`hotel2`.`plafol` join `hotel2`.`planes`) where (`hotel2`.`planes`.`codpla` = `hotel2`.`plafol`.`codpla`)";}s:12:"planificador";a:4:{s:4:"type";s:5:"TABLE";s:3:"sql";s:328:"CREATE TABLE `planificador` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `fecha` date NOT NULL,
  `tipo_servicio_id` int(10) unsigned NOT NULL,
  `salon_id` int(10) unsigned NOT NULL,
  PRIMARY KEY (`id`),
  KEY `fecha` (`fecha`,`tipo_servicio_id`,`salon_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci";s:6:"fields";a:4:{s:2:"id";s:47:"  `id` int(10) unsigned NOT NULL AUTO_INCREMENT";s:5:"fecha";s:23:"  `fecha` date NOT NULL";s:16:"tipo_servicio_id";s:46:"  `tipo_servicio_id` int(10) unsigned NOT NULL";s:8:"salon_id";s:38:"  `salon_id` int(10) unsigned NOT NULL";}s:7:"indexes";a:1:{s:5:"fecha";s:53:"  KEY `fecha` (`fecha`,`tipo_servicio_id`,`salon_id`)";}}s:20:"planificador_detalle";a:3:{s:4:"type";s:5:"TABLE";s:3:"sql";s:369:"CREATE TABLE `planificador_detalle` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `planificador_id` int(10) unsigned NOT NULL,
  `menus_items_id` int(10) unsigned NOT NULL,
  `cantidad` int(10) unsigned NOT NULL,
  `costo` decimal(10,2) NOT NULL,
  `valor` decimal(10,2) NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci";s:6:"fields";a:6:{s:2:"id";s:47:"  `id` int(10) unsigned NOT NULL AUTO_INCREMENT";s:15:"planificador_id";s:45:"  `planificador_id` int(10) unsigned NOT NULL";s:14:"menus_items_id";s:44:"  `menus_items_id` int(10) unsigned NOT NULL";s:8:"cantidad";s:38:"  `cantidad` int(10) unsigned NOT NULL";s:5:"costo";s:32:"  `costo` decimal(10,2) NOT NULL";s:5:"valor";s:32:"  `valor` decimal(10,2) NOT NULL";}}s:11:"popularidad";a:3:{s:4:"type";s:5:"TABLE";s:3:"sql";s:225:"CREATE TABLE `popularidad` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `cantidad` int(11) NOT NULL,
  `valor` decimal(22,2) NOT NULL,
  `costo` decimal(22,2) NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8";s:6:"fields";a:4:{s:2:"id";s:38:"  `id` int(11) NOT NULL AUTO_INCREMENT";s:8:"cantidad";s:29:"  `cantidad` int(11) NOT NULL";s:5:"valor";s:32:"  `valor` decimal(22,2) NOT NULL";s:5:"costo";s:32:"  `costo` decimal(22,2) NOT NULL";}}s:8:"printers";a:3:{s:4:"type";s:5:"TABLE";s:3:"sql";s:242:"CREATE TABLE `printers` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `nombre` varchar(40) DEFAULT NULL,
  `ubicacion` varchar(120) DEFAULT NULL,
  `estado` char(1) NOT NULL DEFAULT 'A',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8";s:6:"fields";a:4:{s:2:"id";s:38:"  `id` int(11) NOT NULL AUTO_INCREMENT";s:6:"nombre";s:35:"  `nombre` varchar(40) DEFAULT NULL";s:9:"ubicacion";s:39:"  `ubicacion` varchar(120) DEFAULT NULL";s:6:"estado";s:39:"  `estado` char(1) NOT NULL DEFAULT 'A'";}}s:7:"recetas";a:2:{s:4:"type";s:4:"VIEW";s:3:"sql";s:633:"CREATE ALGORITHM=UNDEFINED DEFINER=`root`@`localhost` SQL SECURITY DEFINER VIEW `recetas` AS select `ramocol`.`recetap`.`almacen` AS `almacen`,`ramocol`.`recetap`.`numero_rec` AS `numero_rec`,`ramocol`.`recetap`.`nombre` AS `nombre`,`ramocol`.`recetap`.`num_personas` AS `num_personas`,`ramocol`.`recetap`.`tipo` AS `tipo`,`ramocol`.`recetap`.`porc_varios` AS `porc_varios`,`ramocol`.`recetap`.`precio_venta` AS `precio_venta`,`ramocol`.`recetap`.`iva` AS `iva`,`ramocol`.`recetap`.`precio_costo` AS `precio_costo`,`ramocol`.`recetap`.`porc_costo` AS `porc_costo`,`ramocol`.`recetap`.`costoent` AS `costoent` from `ramocol`.`recetap`";}s:11:"referencias";a:2:{s:4:"type";s:4:"VIEW";s:3:"sql";s:693:"CREATE ALGORITHM=UNDEFINED DEFINER=`root`@`localhost` SQL SECURITY DEFINER VIEW `referencias` AS select trim(`ramocol`.`inve`.`item`) AS `id`,`ramocol`.`inve`.`descripcion` AS `nombre`,concat(`ramocol`.`inve`.`item`,_latin1' : ',`ramocol`.`inve`.`descripcion`,_latin1' - REFERENCIA') AS `nombre_unido`,_utf8'I' AS `tipo` from `ramocol`.`inve` where (`ramocol`.`inve`.`estado` = _latin1'A') union select `ramocol`.`recetap`.`numero_rec` AS `id`,`ramocol`.`recetap`.`nombre` AS `nombre`,concat(`ramocol`.`recetap`.`numero_rec`,' : ',`ramocol`.`recetap`.`nombre`,' - RECETA ') AS `nombre_unido`,_utf8'R' AS `tipo` from `ramocol`.`recetap` where (`ramocol`.`recetap`.`almacen` = 1) order by `tipo`";}s:5:"salon";a:4:{s:4:"type";s:5:"TABLE";s:3:"sql";s:1340:"CREATE TABLE `salon` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `nombre` varchar(50) NOT NULL,
  `autorizacion` char(25) DEFAULT NULL,
  `fecha_autorizacion` date DEFAULT NULL,
  `prefijo_facturacion` char(12) NOT NULL,
  `consecutivo_inicial` int(10) unsigned NOT NULL,
  `consecutivo_final` int(10) unsigned NOT NULL,
  `consecutivo_facturacion` int(10) unsigned NOT NULL,
  `consecutivo_orden` int(10) unsigned NOT NULL,
  `tipo_comanda` char(1) DEFAULT NULL,
  `consecutivo_comanda` int(11) DEFAULT NULL,
  `usuarios_hotel_id` int(10) unsigned NOT NULL,
  `conceptos_id` int(10) unsigned NOT NULL,
  `centro_costo` int(10) unsigned DEFAULT NULL,
  `porcentaje_servicio` int(3) DEFAULT NULL,
  `pide_asientos` char(1) NOT NULL DEFAULT 'S',
  `pide_personas` char(1) NOT NULL DEFAULT 'S',
  `leyenda_propina` char(1) DEFAULT NULL,
  `texto_propina` text,
  `propina_automatica` char(1) DEFAULT NULL,
  `venta_a` char(1) DEFAULT NULL,
  `texto_impresion` text,
  `descarga_online` char(1) DEFAULT 'N',
  `ancho_mesas` int(3) unsigned NOT NULL,
  `alto_mesas` int(3) unsigned NOT NULL,
  `cierre_pedidos` char(1) DEFAULT 'N',
  `estado` char(1) NOT NULL DEFAULT 'A',
  PRIMARY KEY (`id`),
  KEY `estado` (`estado`),
  KEY `conceptos_id` (`conceptos_id`),
  KEY `usuarios_hotel_id` (`usuarios_hotel_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8";s:6:"fields";a:27:{s:2:"id";s:38:"  `id` int(11) NOT NULL AUTO_INCREMENT";s:6:"nombre";s:31:"  `nombre` varchar(50) NOT NULL";s:12:"autorizacion";s:38:"  `autorizacion` char(25) DEFAULT NULL";s:18:"fecha_autorizacion";s:40:"  `fecha_autorizacion` date DEFAULT NULL";s:19:"prefijo_facturacion";s:41:"  `prefijo_facturacion` char(12) NOT NULL";s:19:"consecutivo_inicial";s:49:"  `consecutivo_inicial` int(10) unsigned NOT NULL";s:17:"consecutivo_final";s:47:"  `consecutivo_final` int(10) unsigned NOT NULL";s:23:"consecutivo_facturacion";s:53:"  `consecutivo_facturacion` int(10) unsigned NOT NULL";s:17:"consecutivo_orden";s:47:"  `consecutivo_orden` int(10) unsigned NOT NULL";s:12:"tipo_comanda";s:37:"  `tipo_comanda` char(1) DEFAULT NULL";s:19:"consecutivo_comanda";s:44:"  `consecutivo_comanda` int(11) DEFAULT NULL";s:17:"usuarios_hotel_id";s:47:"  `usuarios_hotel_id` int(10) unsigned NOT NULL";s:12:"conceptos_id";s:42:"  `conceptos_id` int(10) unsigned NOT NULL";s:12:"centro_costo";s:46:"  `centro_costo` int(10) unsigned DEFAULT NULL";s:19:"porcentaje_servicio";s:43:"  `porcentaje_servicio` int(3) DEFAULT NULL";s:13:"pide_asientos";s:46:"  `pide_asientos` char(1) NOT NULL DEFAULT 'S'";s:13:"pide_personas";s:46:"  `pide_personas` char(1) NOT NULL DEFAULT 'S'";s:15:"leyenda_propina";s:40:"  `leyenda_propina` char(1) DEFAULT NULL";s:13:"texto_propina";s:22:"  `texto_propina` text";s:18:"propina_automatica";s:43:"  `propina_automatica` char(1) DEFAULT NULL";s:7:"venta_a";s:32:"  `venta_a` char(1) DEFAULT NULL";s:15:"texto_impresion";s:24:"  `texto_impresion` text";s:15:"descarga_online";s:39:"  `descarga_online` char(1) DEFAULT 'N'";s:11:"ancho_mesas";s:40:"  `ancho_mesas` int(3) unsigned NOT NULL";s:10:"alto_mesas";s:39:"  `alto_mesas` int(3) unsigned NOT NULL";s:14:"cierre_pedidos";s:38:"  `cierre_pedidos` char(1) DEFAULT 'N'";s:6:"estado";s:39:"  `estado` char(1) NOT NULL DEFAULT 'A'";}s:7:"indexes";a:3:{s:6:"estado";s:25:"  KEY `estado` (`estado`)";s:12:"conceptos_id";s:37:"  KEY `conceptos_id` (`conceptos_id`)";s:17:"usuarios_hotel_id";s:47:"  KEY `usuarios_hotel_id` (`usuarios_hotel_id`)";}}s:17:"salon_menus_items";a:4:{s:4:"type";s:5:"TABLE";s:3:"sql";s:674:"CREATE TABLE `salon_menus_items` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `salon_id` int(11) NOT NULL,
  `menus_items_id` int(11) NOT NULL,
  `valor` decimal(16,2) DEFAULT NULL,
  `descarga` char(1) NOT NULL DEFAULT 'S',
  `almacen` int(11) DEFAULT NULL,
  `conceptos_id` int(11) DEFAULT NULL,
  `printers_id` int(11) DEFAULT NULL,
  `printers_id2` int(11) DEFAULT NULL,
  `screens_id` int(10) unsigned NOT NULL,
  `estado` char(1) DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `salon_id` (`salon_id`),
  KEY `menus_items_id` (`menus_items_id`),
  KEY `salon_id_2` (`salon_id`,`menus_items_id`,`estado`),
  KEY `screens_id` (`screens_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8";s:6:"fields";a:11:{s:2:"id";s:38:"  `id` int(11) NOT NULL AUTO_INCREMENT";s:8:"salon_id";s:29:"  `salon_id` int(11) NOT NULL";s:14:"menus_items_id";s:35:"  `menus_items_id` int(11) NOT NULL";s:5:"valor";s:36:"  `valor` decimal(16,2) DEFAULT NULL";s:8:"descarga";s:41:"  `descarga` char(1) NOT NULL DEFAULT 'S'";s:7:"almacen";s:32:"  `almacen` int(11) DEFAULT NULL";s:12:"conceptos_id";s:37:"  `conceptos_id` int(11) DEFAULT NULL";s:11:"printers_id";s:36:"  `printers_id` int(11) DEFAULT NULL";s:12:"printers_id2";s:37:"  `printers_id2` int(11) DEFAULT NULL";s:10:"screens_id";s:40:"  `screens_id` int(10) unsigned NOT NULL";s:6:"estado";s:31:"  `estado` char(1) DEFAULT NULL";}s:7:"indexes";a:4:{s:8:"salon_id";s:29:"  KEY `salon_id` (`salon_id`)";s:14:"menus_items_id";s:41:"  KEY `menus_items_id` (`menus_items_id`)";s:10:"salon_id_2";s:57:"  KEY `salon_id_2` (`salon_id`,`menus_items_id`,`estado`)";s:10:"screens_id";s:33:"  KEY `screens_id` (`screens_id`)";}}s:11:"salon_mesas";a:4:{s:4:"type";s:5:"TABLE";s:3:"sql";s:388:"CREATE TABLE `salon_mesas` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `salon_id` int(11) NOT NULL,
  `vpos` char(2) NOT NULL DEFAULT '',
  `hpos` char(2) NOT NULL DEFAULT '',
  `numero` varchar(5) DEFAULT NULL,
  `estado` char(1) DEFAULT 'N',
  PRIMARY KEY (`id`),
  KEY `salon_id` (`salon_id`,`vpos`,`hpos`),
  KEY `salon_id_2` (`salon_id`,`estado`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8";s:6:"fields";a:6:{s:2:"id";s:38:"  `id` int(11) NOT NULL AUTO_INCREMENT";s:8:"salon_id";s:29:"  `salon_id` int(11) NOT NULL";s:4:"vpos";s:36:"  `vpos` char(2) NOT NULL DEFAULT ''";s:4:"hpos";s:36:"  `hpos` char(2) NOT NULL DEFAULT ''";s:6:"numero";s:34:"  `numero` varchar(5) DEFAULT NULL";s:6:"estado";s:30:"  `estado` char(1) DEFAULT 'N'";}s:7:"indexes";a:2:{s:8:"salon_id";s:43:"  KEY `salon_id` (`salon_id`,`vpos`,`hpos`)";s:10:"salon_id_2";s:40:"  KEY `salon_id_2` (`salon_id`,`estado`)";}}s:16:"salon_tipo_venta";a:4:{s:4:"type";s:5:"TABLE";s:3:"sql";s:336:"CREATE TABLE `salon_tipo_venta` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `salon_id` int(10) unsigned NOT NULL,
  `tipo_venta_id` char(1) COLLATE utf8_unicode_ci NOT NULL,
  PRIMARY KEY (`id`),
  KEY `salon_id` (`salon_id`),
  KEY `tipo_venta_id` (`tipo_venta_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci";s:6:"fields";a:3:{s:2:"id";s:47:"  `id` int(10) unsigned NOT NULL AUTO_INCREMENT";s:8:"salon_id";s:38:"  `salon_id` int(10) unsigned NOT NULL";s:13:"tipo_venta_id";s:58:"  `tipo_venta_id` char(1) COLLATE utf8_unicode_ci NOT NULL";}s:7:"indexes";a:2:{s:8:"salon_id";s:29:"  KEY `salon_id` (`salon_id`)";s:13:"tipo_venta_id";s:39:"  KEY `tipo_venta_id` (`tipo_venta_id`)";}}s:7:"screens";a:3:{s:4:"type";s:5:"TABLE";s:3:"sql";s:265:"CREATE TABLE `screens` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `nombre` varchar(70) COLLATE utf8_unicode_ci NOT NULL,
  `estado` char(1) COLLATE utf8_unicode_ci NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci";s:6:"fields";a:3:{s:2:"id";s:47:"  `id` int(10) unsigned NOT NULL AUTO_INCREMENT";s:6:"nombre";s:55:"  `nombre` varchar(70) COLLATE utf8_unicode_ci NOT NULL";s:6:"estado";s:51:"  `estado` char(1) COLLATE utf8_unicode_ci NOT NULL";}}s:13:"socios_actual";a:2:{s:4:"type";s:4:"VIEW";s:3:"sql";s:472:"CREATE ALGORITHM=UNDEFINED DEFINER=`root`@`localhost` SQL SECURITY DEFINER VIEW `socios_actual` AS select `hotel2`.`clientes`.`accion` AS `accion`,`hotel2`.`folio`.`numfol` AS `numfol`,`hotel2`.`folio`.`numhab` AS `numhab`,`hotel2`.`clientes`.`nombre` AS `nombre`,`hotel2`.`folio`.`estado` AS `estado` from (`hotel2`.`folio` join `hotel2`.`clientes`) where ((`hotel2`.`folio`.`cedula` = `hotel2`.`clientes`.`cedula`) and (`hotel2`.`folio`.`estado` in (_utf8'I',_utf8'F')))";}s:13:"tipo_servicio";a:3:{s:4:"type";s:5:"TABLE";s:3:"sql";s:271:"CREATE TABLE `tipo_servicio` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `nombre` varchar(35) COLLATE utf8_unicode_ci NOT NULL,
  `estado` char(1) COLLATE utf8_unicode_ci NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci";s:6:"fields";a:3:{s:2:"id";s:47:"  `id` int(10) unsigned NOT NULL AUTO_INCREMENT";s:6:"nombre";s:55:"  `nombre` varchar(35) COLLATE utf8_unicode_ci NOT NULL";s:6:"estado";s:51:"  `estado` char(1) COLLATE utf8_unicode_ci NOT NULL";}}s:10:"tipo_venta";a:3:{s:4:"type";s:5:"TABLE";s:3:"sql";s:172:"CREATE TABLE `tipo_venta` (
  `id` char(1) NOT NULL,
  `detalle` varchar(45) NOT NULL,
  `costo` char(1) NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8";s:6:"fields";a:3:{s:2:"id";s:23:"  `id` char(1) NOT NULL";s:7:"detalle";s:32:"  `detalle` varchar(45) NOT NULL";s:5:"costo";s:26:"  `costo` char(1) NOT NULL";}}s:8:"usuarios";a:4:{s:4:"type";s:5:"TABLE";s:3:"sql";s:296:"CREATE TABLE `usuarios` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `clave` char(40) NOT NULL,
  `nombre` char(50) NOT NULL DEFAULT '',
  `perfil` varchar(24) DEFAULT NULL,
  `estado` char(1) DEFAULT 'A',
  PRIMARY KEY (`id`),
  KEY `clave` (`clave`,`estado`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8";s:6:"fields";a:5:{s:2:"id";s:38:"  `id` int(11) NOT NULL AUTO_INCREMENT";s:5:"clave";s:27:"  `clave` char(40) NOT NULL";s:6:"nombre";s:39:"  `nombre` char(50) NOT NULL DEFAULT ''";s:6:"perfil";s:35:"  `perfil` varchar(24) DEFAULT NULL";s:6:"estado";s:30:"  `estado` char(1) DEFAULT 'A'";}s:7:"indexes";a:1:{s:5:"clave";s:32:"  KEY `clave` (`clave`,`estado`)";}}s:14:"usuarios_hotel";a:2:{s:4:"type";s:4:"VIEW";s:3:"sql";s:257:"CREATE ALGORITHM=UNDEFINED DEFINER=`root`@`localhost` SQL SECURITY DEFINER VIEW `usuarios_hotel` AS select `hotel2`.`usuarios`.`codusu` AS `id`,`hotel2`.`usuarios`.`nombre` AS `nombre` from `hotel2`.`usuarios` where (`hotel2`.`usuarios`.`estado` = _utf8'A')";}s:12:"usuarios_pos";a:4:{s:4:"type";s:5:"TABLE";s:3:"sql";s:300:"CREATE TABLE `usuarios_pos` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `clave` char(40) NOT NULL,
  `nombre` char(50) NOT NULL DEFAULT '',
  `perfil` varchar(24) DEFAULT NULL,
  `estado` char(1) DEFAULT 'A',
  PRIMARY KEY (`id`),
  KEY `clave` (`clave`,`estado`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8";s:6:"fields";a:5:{s:2:"id";s:38:"  `id` int(11) NOT NULL AUTO_INCREMENT";s:5:"clave";s:27:"  `clave` char(40) NOT NULL";s:6:"nombre";s:39:"  `nombre` char(50) NOT NULL DEFAULT ''";s:6:"perfil";s:35:"  `perfil` varchar(24) DEFAULT NULL";s:6:"estado";s:30:"  `estado` char(1) DEFAULT 'A'";}s:7:"indexes";a:1:{s:5:"clave";s:32:"  KEY `clave` (`clave`,`estado`)";}}s:14:"ventas_default";a:4:{s:4:"type";s:5:"TABLE";s:3:"sql";s:289:"CREATE TABLE `ventas_default` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `tipo_venta_id` char(1) NOT NULL,
  `cedula` varchar(15) NOT NULL,
  `valor_minimo` decimal(10,2) NOT NULL,
  PRIMARY KEY (`id`),
  KEY `tipo_venta_id` (`tipo_venta_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8";s:6:"fields";a:4:{s:2:"id";s:47:"  `id` int(10) unsigned NOT NULL AUTO_INCREMENT";s:13:"tipo_venta_id";s:34:"  `tipo_venta_id` char(1) NOT NULL";s:6:"cedula";s:31:"  `cedula` varchar(15) NOT NULL";s:12:"valor_minimo";s:39:"  `valor_minimo` decimal(10,2) NOT NULL";}s:7:"indexes";a:1:{s:13:"tipo_venta_id";s:39:"  KEY `tipo_venta_id` (`tipo_venta_id`)";}}}