<?php

/**
 * Hotel Front-Office Solution
 *
 * LICENSE
 *
 * This source file is subject to license that is bundled
 * with this package in the file docs/LICENSE.txt.
 *
 * @package 	Back-Office
 * @copyright 	BH-TECK Inc. 2009-2010
 * @version		$Id$
 */

View::getContent();

?>
<div align="center">
	<div class="formExternal">
		<div class="externalHeader">
			<table width="95%" align="center" cellpadding="0" cellspacing="0">
				<tr>
					<td><h1>Imprimir<h1></td>
					<td align="right"><div class="window-close"></div></td>
				</tr>
			</table>
		</div>
		<div class="messages"></div>
		<?php echo Tag::form('cargos_socios/reporteCargosGenerados', 'onbeforesubmit: return false', 'autocomplete: off') ?>
			<table align="center">
				<tr>
					<td align="right"><label for="dateIni">Fecha de Factura (yyyy-mm-dd)</label></td>
					<td align="left">
						<?php
							echo Tag::select('dateIni',$movimientoObj,'using: fecha_at,fecha_at','class: dateIni');
						?>
					</td>
				</tr>
				<tr>
					<td align="right"><label for="reportType">Formato</label></td>
					<td align="left"><?php echo Tag::selectStatic('reportType', array(
						'html'	=> 'HTML',
						'excel'	=> 'EXCEL',
						'pdf'	=> 'PDF',
						'text'	=> 'TEXTO PLANO',
					)) ?></td>
				</tr>
				<tr>
					<td align="center" colspan="3">
						<?php 
							echo Tag::submitButton(array('Imprimir','class'=>'printButton2 printReport'));
						?>
						<td align="left">
							<div class="formSpinner" style="display:none"></div>
						</td>
					</td>
				</tr>
			</table>
		<?php echo Tag::endForm() ?>
	</div>
</div>
