<?php

/**
 * Hotel Front-Office Solution
 *
 * LICENSE
 *
 * This source file is subject to license that is bundled
 * with this package in the file docs/LICENSE.txt.
 *
 * @package 	Back-Office
 * @copyright 	BH-TECK Inc. 2009-2015
 * @version		$Id$
 */

?>

<div class="resultados"></div>

<?php echo HfosTag::iconTitle('issue.png', 'Interface SIIGO Facturación') ?>

<?php echo Tag::form(array('interface_siigo/generar', 'class' => 'interfaseSiigoForm', 'autocomplete' => 'off')) ?>
<table align="center">
	<tr>
		<td valign="top">
			<table>
				<tr>
					<td align="right"><label for="fecha">Fecha</label></td>
					<td><?php echo Tag::dateField('fecha') ?></td>
				</tr>
				<tr>
					<td align="right"><label for="tipo">Tipo</label></td>
					<td><?php echo Tag::selectStatic('tipo', array(
						'F' => 'FACTURACION',
						'T' => 'TERCEROS',
						'P' => 'PROVEEDORES'
					)) ?></td>
				</tr>
				<tr>
					<td align="right"></td>
					<td>
						<table cellspacing="0">
							<tr>
								<td>
									<input type="submit" value="Generar"/>
								</td>
								<td>
									<div class="formSpinner" style="display:none"></div>
								</td>
							</tr>
						</table>
					</td>
				</tr>
			</table>
		</td>
	</tr>
</table>
<?php echo Tag::endForm() ?>
