<?php

/**
 * Hotel Front-Office Solution
 *
 * LICENSE
 *
 * This source file is subject to license that is bundled
 * with this package in the file docs/LICENSE.txt.
 *
 * @package 	Back-Office
 * @copyright 	BH-TECK Inc. 2009-2010
 * @version		$Id$
 */

?>

<?php echo HfosTag::iconTitle('limited-edition.png', 'Cierre de Periodo') ?>

<?php echo Tag::form('cierre_periodo/cierre', 'class: cierreForm') ?>
<table align="center">
	<tr>
		<td valign="top">
			<table>
				<tr>
					<td align="right"><label for="proximoPeriodo">Periodo al Cerrar</label></td>
					<td id="proximoPeriodo"><?php echo $proximoPeriodo ?></td>
				</tr>
				<tr>
					<td align="right"><label for="periodoActual">Periodo Actual</label></td>
					<td id="periodoActual"><?php echo $periodoActual ?></td>
				</tr>
			</table>
		</td>
	</tr>
</table>
<?php //echo HfosTag::reportTypeTag(true, false) ?>
<?php echo Tag::endForm() ?>