<?php

/**
 * Hotel Front-Office Solution
 *
 * LICENSE
 *
 * This source file is subject to license that is bundled
 * with this package in the file docs/LICENSE.txt.
 *
 * @package 	Back-Office
 * @copyright 	BH-TECK Inc. 2009-2010
 * @version		$Id$
 */

View::getContent();

echo HfosTag::iconTitle('attibutes.png', 'Generación de Cuentas de Cobro');

echo Tag::form('cuenta_cobro/generar', 'class: cuentaCobroForm', 'target: _new');

$periodoObj = EntityManager::get('Periodo')->find(array('order'=>'periodo DESC'));

?>
<table align="center">
	<tr>
		<td align="left"><b>Periodo Inicial</b></td>
		<td>
			<?php 				
				echo Tag::select('periodoIni',$periodoObj,'using: id,periodo');
			?>
		</td>
	</tr>
	<tr>
		<td align="left"><b>Periodo Final</b></td>
		<td>
			<?php 
				echo Tag::select('periodoFin',$periodoObj,'using: id,periodo');
			?>
		</td>
	</tr>
	<tr>
		<td align="left"><b>Tipos de Contrato</b></td>
		<td>
			<?php 
				$tipoContratoObj = EntityManager::get('TipoContrato')->find(array('order'=>'nombre ASC'));
				echo Tag::select('tipoContrato',$tipoContratoObj,'using: id,nombre', 'useDummy: true'); 
			?>
		</td>		
	</tr>
	<tr>
	    <td align="left"><label for="sociosId"><b>Contrato</b></label></td>
		<td>
			<?php
				echo HfosTag::addHyperFormSpecialField(array(
					'type' => 'SocioTc',
					'name' => 'sociosId',
					'classForm' => 'cuentaCobroForm'
				));
			?>
		</td>
	</tr>
</table>
<?php echo HfosTag::reportTypeTag(true, false, array('showHtml'=>true, 'showPdf'=>true)) ?>
<?php echo Tag::endForm() ?>
