<?php

/**
 * Hotel Front-Office Solution
 *
 * LICENSE
 *
 * This source file is subject to license that is bundled
 * with this package in the file docs/LICENSE.txt.
 *
 * @package 	Back-Office
 * @copyright 	BH-TECK Inc. 2009-2010
 * @version		$Id$
 */

echo HfosTag::iconTitle('attibutes.png', 'Generar Abono a una Reserva') ?>

<div class="formContent">

	<div class="formPannel" align="right">

		<?php echo Tag::form('abono_reserva/abono', 'autocomplete: off', 'class: formGrabar') ?>
			<fieldset class="tabbed">
				<legend>Maestro de Pago</legend>
				<?php echo Tag::hiddenField(array('reservasId','value' => $reservasId)); ?>
				<table align="center">
					<tr>
						<td align="right"><label for="reciboProvisional">Recibo Provisional</label></td>
						<td><?php echo Tag::numericField(array('reciboProvisional', 'size' => 10)) ?></td>
					</tr>
					<tr>
						<td align="right"><label for="fechaPago">Fecha de Pago</label></td>
						<td><?php echo Tag::dateField(array('fechaPago', 'class' => 'date-field')) ?><span class="notNullMark">!</span></td>
					</tr>
					<tr>
						<td align="right"><label for="cuentasId">Cuenta Bancaria</label></td>
						<td><?php echo Tag::select('cuentasId', $cuentas, 'using: id,banco') ?><span class="notNullMark">!</span></td>
					</tr>
				</table>
			</fieldset>
			<fieldset class="tabbed">
				<legend>Detalle de Pago</legend>
				<table class="sortable abonos-contrato-grid" cellspacing="0" align="center">
					<thead>
						<tr>
							<th class="sortcol sortasc" colspan="2"></th>
							<th class="sortcol">Forma de Pago</th>
							<th class="sortcol">Número</th>
							<th class="sortcol">Valor</th>
						</tr>
					</thead>
					<tbody class="abonos-reserva-body">
					<?php
						echo '<tr class="linea1 orden-linea">
							<td class="numero">1</td>
							<td>',
							Tag::checkboxField(array(
								'itemCheck[]',
								'class' => 'itemCheck'
							)),
							'</td><td>',
							Tag::select(array(
								'formaPago[]',
								$formasPago,
								'class' => 'formaPago',
								'using' => 'id,nombre'
							)),
							'</td><td>',
							Tag::numericField(array(
								'numeroForma[]',
								'class' => 'numeroForma numeric',
								'size' => 5
							)),
							'</td><td>',
							Tag::numericField(array(
								'valor[]',
								'class' => 'valor numeric',
								'size' => 12
							)),
							'</td>
						</tr>';
					?>
					</tbody>
				</table>
			</fieldset>
		<?php echo Tag::endForm() ?>

	</div>

</div>
