<?php

/**
 * Hotel Front-Office Solution
 *
 * LICENSE
 *
 * This source file is subject to license that is bundled
 * with this package in the file docs/LICENSE.txt.
 *
 * @package 	Back-Office
 * @copyright 	BH-TECK Inc. 2009-2010
 * @version		$Id$
 */

Core::importFromLibrary('Hfos/Tpc', 'TpcHelper.php');

View::getContent();

?>

<?php echo HfosTag::iconTitle('attibutes.png', 'Estados de Cuenta de Reserva '.$reserva->getNumeroContrato()) ?>

<div>
    <table align="center">
		<tr>
		  <td align="right"><label for="identificacion">Cédula: </label></td>
		  <td><?php echo $reserva->getIdentificacion(); ?></td>

		  <td align="right"><label for="nombres">Nombres: </label></td>
		  <td><?php echo $reserva->getNombres(); ?></td>

		  <td align="right"><label for="apellidos">Apellidos: </label></td>
		  <td><?php echo $reserva->getApellidos(); ?></td>
		</tr>
	</table>
	<?php echo Tag::hiddenField(array('estadoReserva', 'value'=>$reserva->getEstadoContrato())); ?>
	<br/><br/>
</div>

<fieldset class="tabbed">
	<legend>Recibos de pago</legend>
	<?php echo TpcHelper::generaListaRecibosPagos(array('reservasId' => $reserva->getId())); ?>
</fieldset>
<fieldset class="tabbed">
	<legend>Historia de Reserva</legend>
	<table align="center">
	<?php echo TpcHelper::generaListaHistoria(array('reservasId' => $reserva->getId())); ?>
	</table>
</fieldset>
