<?php

/**
 * Hotel Front-Office Solution
 *
 * LICENSE
 *
 * This source file is subject to license that is bundled
 * with this package in the file docs/LICENSE.txt.
 *
 * @package 	Back-Office
 * @copyright 	BH-TECK Inc. 2009-2010
 * @version		$Id$
 */

?>

<div class="resultados"></div>

<?php echo HfosTag::iconTitle('archives.png', 'Consumos/Pedidos por Centro de Costo') ?>

<?php echo Tag::form('consumos/generar', 'class: consumosForm', 'autocomplete: off') ?>
<table align="center">
	<tr>
		<td valign="top">
			<table>
				<tr>
					<td align="right"><label for="tipoMovimiento">Movimiento</label></td>
					<td><?php echo Tag::selectStatic('tipoMovimiento', $tipoMovimiento) ?></td>
				</tr>
				<tr>
					<td align="right"><label for="nitErrado">Tercero Convención</label></td>
					<td><?php echo HfosTag::terceroField('nitTercero') ?></td>
				</tr>
				<tr>
					<td align="right"><label for="almacenInicial">Almacén Inicial</label></td>
					<td><?php echo Tag::select(array('almacenInicial', $almacenes, 'using' => 'codigo,nom_almacen')) ?></td>
				</tr>
				<tr>
					<td align="right"><label for="almacenFinal">Almacén Final</label></td>
					<td><?php echo Tag::select(array('almacenFinal', $almacenes, 'using' => 'codigo,nom_almacen')) ?></td>
				</tr>
				<tr>
					<td align="right"><label for="fechaInicial">Fecha Inicial</label></td>
					<td><?php echo Tag::dateField(array('fechaInicial', 'startYear' => '2000')) ?></td>
				</tr>
				<tr>
					<td align="right"><label for="fechaFinal">Fecha Final</label></td>
					<td><?php echo Tag::dateField(array('fechaFinal', 'startYear' => '2000')) ?></td>
				</tr>
				<tr>
					<td align="right"><label for="numeroInicial">Consecutivo Inicial</label></td>
					<td><?php echo Tag::numericField(array('numeroInicial', 'size' => '7')) ?></td>
				</tr>
				<tr>
					<td align="right"><label for="numeroFinal">Consecutivo Final</label></td>
					<td><?php echo Tag::numericField(array('numeroFinal', 'size' => '7')) ?></td>
				</tr>
				<tr>
					<td align="right"><label for="centroInicial">Centro Costo Inicial</b></td>
					<td><?php echo Tag::select('centroInicial', $centros, 'using: codigo,nom_centro') ?></td>
				</tr>
				<tr>
					<td align="right"><label for="centroFinal">Centro Costo Final</label></td>
					<td><?php echo Tag::select('centroFinal', $centros, 'using: codigo,nom_centro') ?></td>
				</tr>
				<tr>
					<td></td>
					<td>
						<table>
							<tr>
								<td><input type="checkbox" name="consolidado" id="consolidado" value="S"/></td>
								<td><label for="consolidado">Consolidado</label></td>
							</tr>
						</table>
					</td>
				</tr>
				<tr>
					<td align="right"></td>
					<td>
						<table cellspacing="0">
							<tr>
								<td>
									<input type="submit" value="Generar"/>
								</td>
								<td>
									<div class="formSpinner" style="display:none"></div>
								</td>
							</tr>
						</table>
					</td>
				</tr>
			</table>
		</td>
		<td valign="top">
			<div class="cuadro-cierre">
				<table>
					<tr>
						<td align="right"><b>Último Cierre</b></td>
						<td><?php echo $fechaCierre->getLocaleDate('long') ?></td>
					</tr>
				</table>
			</div>
		</td>
	</tr>
</table>
<?php echo HfosTag::reportTypeTag(true, false) ?>
<?php echo Tag::endForm() ?>
