<?php

/**
 * Hotel Front-Office Solution
 *
 * LICENSE
 *
 * This source file is subject to license that is bundled
 * with this package in the file docs/LICENSE.txt.
 *
 * @package 	Back-Office
 * @copyright 	BH-TECK Inc. 2009-2010
 * @version		$Id$
 */

View::getContent();


echo '<h1>Regenerar Clave</h1><div align="center">';
echo Tag::form('regenerar_clave/cambiar');
	echo Tag::select('usuarioId', $UsuariosPos->find('estado="A"', 'order: nombre'), 'using: id,nombre');
	echo Tag::submitButton('Cambiar', 'class: controlButton');
echo Tag::endForm();
echo '</div>';