<?php

/**
 * Hotel Front-Office Solution
 *
 * LICENSE
 *
 * This source file is subject to license that is bundled
 * with this package in the file docs/LICENSE.txt.
 *
 * @package 	Back-Office
 * @copyright 	BH-TECK Inc. 2009-2010
 * @version		$Id$
 */

?>
<div align="center">
	<?php View::getContent() ?>

	<div id='loginDiv' align="right">
		<?php echo Tag::form('admin/login', 'onsubmit: $("pass").hide(); $("pass").value = hex_sha1($("pass").value);') ?>

		<table id='login-table'>
			<tr>
				<td align="left" colspan="4" id='loginTip' style="color:#c0c0c0">
					Iniciar Sesión Administrativa
				</td>
			</tr>
			<tr>
				<td align='right'><label for="login">Usuario</label></td>
				<td><?php echo Tag::textField('login', 'autocomplete: off') ?></td>
				<td align='right'><label for="pass">Contraseña</label></td>
				<td><?php echo Tag::passwordField('pass') ?></td>
				<td>
					<?php echo Tag::submitButton('Entrar', 'enviar') ?>
				</td>
			</tr>
		</table>
		<?php echo Tag::endForm() ?>

		<div id='footer'>
			<?php echo Tag::linkTo("appmenu", "Volver al Menú Principal") ?> | Todos los derechos reservados <?php echo date('Y') ?>
		</div>

	</div>
</div>


<script type='text/javascript'>
	new Event.observe(window, "load", function(){
		$("login").activate();
	})
</script>

<br>
