<?php

/**
 * Hotel Front-Office Solution
 *
 * LICENSE
 *
 * This source file is subject to license that is bundled
 * with this package in the file docs/LICENSE.txt.
 *
 * @package 	Persé
 * @copyright 	BH-TECK Inc. 2009-2010
 * @version		$Id$
 */

$guestInfo = SessionNamespace::get('guestInfo');
$fecha = new Date();

$currencyFactor = Session::get('currencyFactor');
if(Session::get('currencyId')!=18){
	Flash::notice($traslate['convUse'].' 1 COP = '.$currencyFactor.' '.Session::get('convSymbol').'. '.$traslate['convAldia']);
}

?>
<table width="100%">
	<tr>
		<td>
			<h1 class="no-screen"><?php echo $guestInfo->getHotel(); ?></h1>
			<h2 class="no-screen"><?php echo $guestInfo->getCliente(), ' / ', $guestInfo->getHabitacion() ?></h1>
			<h2><?php echo $traslate['detalleCuenta']; ?></h2>
			<h3 class="no-screen"><?php echo $fecha->getLocaleDate().', '.date('H:i'); ?></h3>
		</td>
		<td align="right" width="170" valign="top">
			<div id="pay-button" class="no-print">
				<table align="center">
					<tr>
						<td width="18" align="center"><?php echo Tag::image('perse/currencyb.png', 'height: 20') ?></td>
						<td align="left"><?php echo Tag::linkTo('accounts/doPay/'.$id, $traslate['RealizarAbono']) ?></td>
					</tr>
				</table>
			</div>
		</td>
		<td align="right" width="100" valign="top">
			<div id="print-button" class="no-print">
				<table align="center">
					<tr>
						<td width="27"><?php echo Tag::image('perse/print.png', 'height: 20') ?></td>
						<td align="left"><a href="#" onclick="window.print(); return false"><?php echo $traslate['Imprimir'] ?></a></td>
					</tr>
				</table>
			</div>
		</td>
		<td align="right" width="100" valign="top">
			<div id="money-button" class="no-print">
				<table align="center">
					<tr>
						<td width="27"><?php echo $traslate['Moneda'] ?></td>
						<td align="left"><?php

							if(substr(Session::get('locale'), 0, 2)=='es'){
								echo Tag::select(array('currencyId', $Currencies->find('order: name_es'), 'using' => 'id,name_es', 'value' => Session::get('currencyId')));
							} else {
								echo Tag::select(array('currencyId', $Currencies->find('order: name'), 'using' => 'id,name', 'value' => Session::get('currencyId')));
							}

						?></td>
					</tr>
				</table>
			</div>
		</td>
	</tr>
</table>

<div id="accounts-details" align="center">
	<table cellspacing="0" width="95%" class="table-white">
		<?php
			$balance = 0;
			if(count($movimientos)){
				foreach($movimientos as $fecha => $movimientosFecha){
					$date = new Date($fecha);
					echo '<tr>
						<td colspan="7" align="left" class="date-cell">', $date->getLocaleDate('long'), '</td>
					</tr>
					<tr>
						<td class="th-cell">', $traslate['concepto'], '</td>
						<td class="th-cell">', $traslate['valor'], '</td>
						<td class="th-cell">', $traslate['iva'], '</td>
						<td class="th-cell">', $traslate['servicio'], '</td>
						<td class="th-cell">', $traslate['subtotal'], '</td>
						<td class="th-cell">', $traslate['abonos'], '</td>
						<td class="th-cell">', $traslate['saldos'], '</td>
					</tr>';
					foreach($movimientosFecha as $movimiento){
						if(isset($movimiento['iva'])){
							$balance+=($movimiento['total']/$currencyFactor);
							echo '<tr>
								<td align="left">', $movimiento['concepto'], '</td>
								<td align="right">', Currency::money($movimiento['valor']/$currencyFactor), '</td>
								<td align="right">', Currency::money($movimiento['iva']/$currencyFactor), '</td>
								<td align="right">', Currency::money($movimiento['servicio']/$currencyFactor), '</td>
								<td align="right">', Currency::money($movimiento['total']/$currencyFactor), '</td>
								<td>&nbsp;</td>
								<td align="right">', Currency::money($balance), '</td>
							</tr>';
						} else {
							$balance-=($movimiento['total']/$currencyFactor);
							echo '<tr class="payment">
								<td align="left">', $movimiento['concepto'], '</td>
								<td align="right">&nbsp;</td>
								<td align="right">&nbsp;</td>
								<td align="right">&nbsp;</td>
								<td align="right">&nbsp;</td>
								<td align="right">', Currency::money($movimiento['total']/$currencyFactor), '</td>
								<td align="right">', Currency::money($balance), '</td>
							</tr>';
						}
					}
					echo '<tr>
						<td colspan="7" align="left" class="spacer-cell"></td>
					</tr>';
				}
			} else {
				echo '<tr><td colspan="7" align="center" class="no-has">', $traslate['NoMovimiento'], '</td></tr>';
			}
		?>
		<tr>
			<td colspan="6"  id="total-td" align="right"><?php echo $traslate['PagosAFavor'] ?></td>
			<td align="right" id="total-sum"><?php echo Currency::money($abonos/$currencyFactor) ?></td>
		</tr>
		<tr>
			<td colspan="6"  id="total-td" align="right"><?php echo $traslate['TotalConsumos'] ?></td>
			<td align="right" id="total-sum"><?php echo Currency::money($consumos/$currencyFactor) ?></td>
		</tr>
		<tr>
			<td colspan="6"  id="total-td" align="right" style="color:#000"><?php echo $traslate['SaldoFinal'] ?></td>
			<td align="right" id="total-sum" style="color:#000"><?php echo Currency::money(($consumos-$abonos)/$currencyFactor) ?></td>
		</tr>
	</table>
</div>

<?php if(count($cuentas)){ ?>
	<div class="no-print">

		<h3><?php echo $traslate['OtrasCuentas']; ?></h3>

		<div id="accounts-resume" align="center">
			<table cellspacing="0" class="border-b">
				<tr>
					<th><?php echo $traslate['cuenta'] ?></th>
					<th><?php echo $traslate['impuestos'] ?></th>
					<th><?php echo $traslate['cons/desc'] ?></th>
					<th><?php echo $traslate['abon/dev'] ?></th>
					<th><?php echo $traslate['saldo'] ?></th>
				</tr>
				<?php
					foreach($cuentas as $n => $cuenta){
						echo '<tr>
							<td align="center">', $n, '</td>
							<td align="right">', Currency::money($cuenta['iva']/$currencyFactor), '</td>
							<td align="right">', Currency::money($cuenta['total']/$currencyFactor), '</td>
							<td align="right">', Currency::money($cuenta['abonos']/$currencyFactor), '</td>
							<td align="right"><b>', Currency::money(($cuenta['total']-$cuenta['abonos'])/$currencyFactor), '</b></td>
							<td align="center" class="border-top">', Tag::linkTo('accounts/details/'.$n , $traslate['details']), '</td>
						</tr>';
					}
				?>
			</table>
		</div>

	</div>
<?php } ?>